import json,re
from pathlib import Path
BASE=Path(__file__).parent
CACHE=BASE/'research_cache'
PORTAL='https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search'
ROWS=[]
def add(id,title,source,what,who,group='UE',company='Nu',ngo='Nu',person='Nu',public='Nu',mode='Direct la Comisia Europeană / agenția UE',instrument='Grant',amount='Conform apelului',budget='',rate='Conform apelului',partnership='Conform apelului',status='Program activ; verificare la nivel de apel',deadline='',apply=PORTAL,note='',parent=''):
    p=CACHE/(source+'.json')
    s=json.loads(p.read_text(encoding='utf8')) if p.exists() else {'url':source,'ok':False}
    ROWS.append(dict(id=id,title=title,source_key=source,source=s.get('url_final',s['url']),what=what,who=who,group=group,company=company,ngo=ngo,person=person,public=public,mode=mode,instrument=instrument,amount=amount,budget=budget,rate=rate,partnership=partnership,status=status,deadline=deadline,apply=apply,note=note,parent=parent))
add('EU01','Horizon Europe – proiecte de cercetare și inovare','Horizon_WP','Cercetare, demonstrare și inovare în domeniile apelurilor','Firme, universități, institute, ONG-uri și autorități eligibile',company='Da',ngo='Condiționat',person='Prin instituția gazdă',public='Da',partnership='De regulă consorțiu internațional; excepții pe schemă',note='Program-cadru; liniile următoare sunt componente și nu bugete suplimentare.')
for n,name,what in [(1,'Sănătate','Medicină, prevenție, tehnologii și sisteme de sănătate'),(2,'Cultură, creativitate și societate incluzivă','Patrimoniu, industrii creative, democrație și transformări sociale'),(3,'Securitate civilă pentru societate','Rezistență la dezastre, securitate și protecția societății'),(4,'Digital, industrie și spațiu','Industrie, materiale, AI, tehnologii digitale și spațiale'),(5,'Climă, energie și mobilitate','Energie curată, eficiență, baterii și transport'),(6,'Alimentație, bioeconomie, agricultură și mediu','Sisteme alimentare, bioeconomie, resurse și biodiversitate')]:
    add('HCL'+str(n),'Horizon – Cluster '+str(n)+' '+name,'Horizon_WP',what,'Entități juridice eligibile din UE; profilul depinde de topic',company='Da',ngo='Condiționat',public='Da',partnership='De regulă minimum 3 entități independente din 3 țări eligibile; verificare în topic',parent='EU01')
for id,title,what in [('HINF','Horizon – Infrastructuri de cercetare','Infrastructuri și servicii pentru cercetare'),('HEIE','Horizon – European Innovation Ecosystems','Ecosisteme de inovare, colaborare și creșterea companiilor'),('HWID','Horizon – Widening / ERA','Consolidarea cercetării în țările widening, inclusiv România'),('HMIS','Horizon – Misiuni UE','Adaptare climatică, cancer, ape, orașe și soluri'),('HNEB','Horizon – New European Bauhaus','Construcții și comunități sustenabile, incluzive și de calitate'),('HHOR','Horizon – Acțiuni orizontale','Clean Industrial Deal, AI în știință și alte priorități orizontale')]:
    add(id,title,'Horizon_WP',what,'Firme, cercetare, organizații și autorități potrivit topicului',company='Condiționat',ngo='Condiționat',public='Da',parent='EU01')
for id,title,what,who,pers in [('MSPF','MSCA Postdoctoral Fellowships','Mobilitatea și formarea cercetătorilor postdoctorali','Cercetător împreună cu instituția gazdă','Prin instituția gazdă'),('MSDN','MSCA Doctoral Networks','Programe doctorale în consorțiu','Universități, institute și companii; doctoranzi selectați ulterior','Recrutare în proiect'),('MSSE','MSCA Staff Exchanges','Schimburi de personal între instituții și firme','Organizații academice și neacademice; personal participant','Prin angajator'),('MSCF','MSCA COFUND','Cofinanțarea programelor doctorale și postdoctorale','Instituții care gestionează programe de formare / recrutare','Recrutare în program'),('MSCZ','MSCA and Citizens','Comunicarea cercetării și European Researchers’ Night','Organizații, universități și parteneri relevanți','Prin organizație')]:
    add(id,title,'Horizon_WP',what,who,company='Condiționat',ngo='Condiționat',person=pers,public='Da',parent='EU01')
for id,title,amount,who in [('ERCST','ERC Starting Grant','Până la 1,5 mil. EUR; suplimentări potrivit WP','Cercetător și instituție gazdă eligibilă'),('ERCCO','ERC Consolidator Grant','Până la 2 mil. EUR; suplimentări potrivit WP','Cercetător și instituție gazdă eligibilă'),('ERCAD','ERC Advanced Grant','Până la 2,5 mil. EUR; suplimentări potrivit WP','Cercetător consacrat și instituție gazdă eligibilă'),('ERCSY','ERC Synergy Grant','Până la 10 mil. EUR; suplimentări potrivit WP','Grup de 2–4 cercetători principali cu instituțiile gazdă'),('ERCPO','ERC Proof of Concept','Conform WP și apelului','Beneficiari ERC eligibili; verificare grant ERC de bază')]:
    add(id,title,'ERC','Cercetare de frontieră / valorificarea rezultatelor ERC',who,company='Condiționat',person='Prin instituția gazdă',public='Da',amount=amount,note='Condițiile de experiență se verifică în WP al anului apelului; 2027 are reguli actualizate.',parent='EU01')
add('EICA','EIC Accelerator','EIC_Accelerator','Dezvoltare și scalare deep tech','Start-up-uri și IMM-uri; persoane care vor înființa o firmă eligibilă',company='Da',person='Condiționat: înființare firmă',instrument='Grant / investiție de capital / finanțare mixtă',amount='Grant sub 2,5 mil. EUR; capital 0,5–10 mil. EUR',partnership='Solicitant individual',rate='Grant de regulă 70%; verificare WP',note='Grantul și capitalul sunt instrumente diferite. Condiții tehnologice și comerciale stricte.',parent='EU01')
add('EICP','EIC Pathfinder','EIC_Pathfinder','Cercetare pentru tehnologii radical noi','Consorții de cercetare; firme și institute eligibile',company='Da',public='Da',amount='Până la 4 mil. EUR potrivit WP 2026',parent='EU01')
add('EICT','EIC Transition','EIC_Transition','Transformarea rezultatelor de cercetare în inovații','Entități cu rezultate eligibile din proiecte anterioare',company='Da',public='Da',amount='Până la 2,5 mil. EUR',note='Accesul presupune rezultate eligibile; nu este o schemă generală pentru orice start-up.',parent='EU01')
add('EICS','EIC STEP Scale Up','EIC_STEP','Scalarea tehnologiilor strategice','IMM, start-up, spin-off și small mid-cap eligibile',company='Da',instrument='Investiție de capital',amount='10–30 mil. EUR',note='Necesită condițiile STEP și mobilizarea unei runde mari de investiții.',parent='EU01')
add('EICD','EIC STEP Scale Up Defence','EIC_Defence','Capacități industriale pentru tehnologii de apărare','Companii eligibile din domeniile apelului',company='Da',instrument='Investiție de capital',amount='Până la 30 mil. EUR',deadline='2026-10-28',status='Deschis conform paginii oficiale',parent='EU01')
add('EICCH','EIC Advanced Innovation Challenges','EIC','Inovație deep tech cu risc ridicat, orientată spre cerere','Entități eligibile din provocările WP 2026',company='Condiționat',public='Condiționat',amount='300.000 EUR în etapa pilot indicată de WP',parent='EU01')
for id,title,source,what in [('JUCH','Chips Joint Undertaking','Chips','Microelectronică și semiconductori'),('JUHP','EuroHPC Joint Undertaking','EuroHPC','Calcul de înaltă performanță și tehnologii asociate'),('JUHY','Clean Hydrogen Joint Undertaking','CleanHydrogen','Hidrogen curat'),('JUBB','Circular Bio-based Europe Joint Undertaking','CBE','Bioeconomie circulară și bioproducție'),('JUHI','Innovative Health Initiative','IHI','Inovație și cercetare în sănătate'),('JUCA','Clean Aviation Joint Undertaking','CleanAviation','Aviație sustenabilă'),('JUSR','SESAR 3 Joint Undertaking','SESAR','Managementul traficului aerian'),('JURA','Europe’s Rail Joint Undertaking','Rail','Inovare în transportul feroviar'),('JUSN','Smart Networks and Services Joint Undertaking','SmartNetworks','Rețele și servicii 5G / 6G')]:
    add(id,title,source,what,'Firme și organizații de cercetare eligibile; restricții specifice JU',company='Condiționat',public='Da',partnership='De regulă consorțiu; condiții specifice fiecărui JU',parent='EU01')
add('EIT','EIT – comunități de cunoaștere și inovare','EIT','Accelerare, antreprenoriat, inovare, educație și competiții','Companii, start-up-uri, instituții și persoane potrivit KIC',company='Da',ngo='Condiționat',person='Condiționat',mode='Prin EIT / KIC / operatorul apelului',instrument='Grant / premiu / sprijin / uneori capital',note='Apelurile KIC sunt separate; participarea și costurile se verifică în documentele fiecăruia.')
add('EURATOM','Euratom Research and Training','Euratom','Cercetare nucleară, siguranță și radioprotecție','Firme și organizații de cercetare eligibile',company='Condiționat',public='Da')
add('RFCS','Research Fund for Coal and Steel','RFCS','Cercetare și tranziție în sectoarele cărbune și oțel','Firme, universități și institute din sectoarele eligibile',company='Da',public='Da')
for id,title,what in [('LIFEN','LIFE – Natură și biodiversitate','Conservare, biodiversitate și restaurare'),('LIFEE','LIFE – Economie circulară și calitatea vieții','Economie circulară, reducerea poluării și mediu'),('LIFEC','LIFE – Atenuare și adaptare climatică','Atenuare, adaptare și guvernanță climatică'),('LIFET','LIFE – Tranziție energetică curată','Eliminarea barierelor și accelerarea tranziției energetice')]:
    add(id,title,'LIFE',what,'Entități juridice UE eligibile; persoanele fizice nu depun',company='Da',ngo='Da',public='Da',status='Majoritatea apelurilor 2026 închise; etape ulterioare distincte',note='SAP 2026: termen 22.09.2026. Termenul 04.03.2027 al proiectelor strategice nu redeschide etapa inițială.')
for id,title,source,what in [('CEFT','CEF Transport','CEF_Transport','Infrastructură TEN-T și mobilitate'),('CEFE','CEF Energy','CEF_Energy','Infrastructură energetică transfrontalieră eligibilă'),('CEFD','CEF Digital','CEF_Digital','Infrastructură digitală și conectivitate transfrontalieră')]:
    add(id,title,source,what,'Promotori de infrastructură, companii și autorități eligibile',company='Condiționat',public='Da',note='Nu finanțează orice investiție locală; se verifică rețeaua / proiectul eligibil și aprobările necesare.')
add('DIG','Digital Europe','Digital_WP','AI, date, competențe digitale, implementare și capacități digitale','Firme, institute, organizații și autorități eligibile',company='Da',ngo='Condiționat',public='Da')
add('DIGECCC','Digital Europe – Cybersecurity / ECCC','Digital_WP','Securitate cibernetică și capacități europene','Entități eligibile; restricții de control / securitate potrivit apelului',company='Condiționat',public='Da',parent='DIG')
add('EU4H','EU4Health','EU4Health','Sănătate publică și consolidarea sistemelor medicale','Organizații de sănătate, firme, ONG-uri și instituții eligibile',company='Condiționat',ngo='Da',public='Da')
add('SMP','Single Market Programme – IMM, turism, clustere','SMP','Competitivitate, piață unică și servicii pentru IMM','Organizații suport, consorții și firme potrivit apelului',company='Condiționat',ngo='Condiționat',public='Da')
add('SMPFOOD','Single Market – Alimente, siguranță și risipă alimentară','SMP','Siguranță alimentară și reducerea risipei','Organizații și operatori eligibili din apel',company='Condiționat',ngo='Condiționat',public='Da',parent='SMP')
add('I3','Interregional Innovation Investments – I3','I3','Investiții interregionale în inovare, TRL 6–9','IMM, clustere, institute și autorități din consorții eligibile',company='Da',ngo='Condiționat',public='Da',amount='Până la 10 mil. EUR / proiect',rate='70% pentru investiții; reguli distincte FSTP',deadline='2026-11-12',status='Deschis – INV1 și INV2a',partnership='Minimum de parteneri și regiuni potrivit strandului')
add('CERV','Citizens, Equality, Rights and Values – CERV','CERV','Democrație, valori UE, egalitate, drepturi și prevenirea violenței','ONG-uri, autorități și alte entități eligibile potrivit apelului',company='Condiționat',ngo='Da',public='Da')
add('JUST','Justice Programme','Justice','Cooperare judiciară, formare și acces la justiție','Organizații și autorități eligibile',company='Condiționat',ngo='Da',public='Da')
add('ERASMUS','Erasmus+ – acțiuni centralizate EACEA','Erasmus','Educație, formare, tineret și sport','Instituții, ONG-uri și companii eligibile; beneficiari individuali prin proiect',company='Condiționat',ngo='Da',person='Prin instituție / proiect',public='Da',mode='Direct EACEA numai pentru acțiunile centralizate',note='Mobilitățile și numeroase parteneriate sunt administrate de agențiile naționale; nu toate sunt finanțare directă CE.')
add('EMUNDUS','Erasmus Mundus – burse de master','Erasmus','Mastere comune internaționale și burse','Candidați individuali la masterele finanțate',person='Da, prin consorțiul masterului',mode='Selecție și plată prin consorțiul universitar',instrument='Bursă',apply='https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',parent='ERASMUS')
add('ESC','European Solidarity Corps','Solidarity','Voluntariat, solidaritate și ajutor umanitar','Organizații eligibile și tineri participanți',ngo='Da',person='Prin organizație / grup eligibil',public='Da',mode='Agenții naționale sau EACEA, potrivit acțiunii',instrument='Grant / sprijin pentru participare')
for id,title,what in [('CREAC','Creative Europe – Culture','Cooperare culturală, rețele, platforme și literatură'),('CREAM','Creative Europe – MEDIA','Film, audiovizual, jocuri video și distribuție'),('CREAX','Creative Europe – Cross-sectoral / Journalism','Cooperare între sectoare, media și jurnalism')]:
    add(id,title,'Creative_Docs',what,'Organizații și companii din sectoarele culturale / creative eligibile',company='Da',ngo='Da',public='Condiționat')
add('CME','Culture Moves Europe','Culture_Mobility','Mobilitatea artiștilor și profesioniștilor culturali','Artiști / profesioniști culturali și gazde de rezidențe eligibile',company='Condiționat',ngo='Da',person='Da',mode='Prin Goethe-Institut, operatorul schemei UE',instrument='Grant de mobilitate',note='Rezidența și disciplina artistică se verifică în apel; sprijinul individual nu este o investiție în firmă.')
add('EASI','ESF+ – EaSI, componenta directă','EaSI','Ocupare, incluziune, inovare socială și mobilitate','Organizații, parteneri sociali și instituții eligibile',company='Condiționat',ngo='Da',public='Da')
add('SOCPL','Dialog social și politici sociale – SOCPL','EaSI','Informare, reprezentare și cooperarea partenerilor sociali','Sindicate, patronate și organizații eligibile',ngo='Condiționat',public='Condiționat',deadline='2026-11-12',status='Apel SOCPL-2026-INFO-REPR deschis')
add('INNOV','Innovation Fund','Innovation_Calls','Implementarea tehnologiilor industriale cu emisii reduse','Companii și promotori de proiecte eligibile',company='Da',public='Condiționat',instrument='Grant / licitație competitivă de sprijin',note='Apelurile grant și licitațiile pentru hidrogen / decarbonizare au reguli distincte.')
add('EMFAF','EMFAF – componenta directă CINEA','EMFAF','Economie albastră, inovare și politici maritime','Firme, ONG-uri, cercetare și autorități eligibile',company='Condiționat',ngo='Condiționat',public='Da',note='Componenta națională de pescuit este gestionată separat în România.')
add('AGRIP','Promovarea produselor agricole – AGRIP','Agri','Promovarea produselor agricole pe piețele UE și externe','Organizații profesionale, interprofesionale și grupuri eligibile',company='Prin organizație eligibilă',ngo='Condiționat',mode='REA pentru programe MULTI; programele SIMPLE prin statul membru',note='O fermă sau societate individuală nu este automat solicitant eligibil.')
for id,title,src,what,who in [('UCPM','Union Civil Protection Mechanism','UCPM','Prevenire, pregătire și răspuns la dezastre','Autorități și organizații eligibile în protecție civilă'),('AMIF','AMIF – acțiunile Uniunii','AMIF','Migrație, azil și integrare','Organizații și instituții eligibile'),('ISF','Internal Security Fund – acțiunile Uniunii','ISF','Criminalitate, securitate și amenințări','Autorități și organizații eligibile'),('ANTIF','Union Anti-Fraud Programme','Antifraud','Protejarea intereselor financiare UE','Autorități, cercetare și alte entități eligibile'),('PERIC','Pericles IV','Pericles','Protecția euro împotriva falsificării','Autorități naționale competente')]:
    add(id,title,src,what,who,company='Condiționat' if id!='PERIC' else 'Nu',ngo='Condiționat' if id not in ['PERIC','ANTIF'] else 'Nu',public='Da',note='Fondurile naționale ale programelor mixte nu sunt granturi directe de la CE.')
add('EDIP','European Defence Industry Programme – EDIP','EDIP','Industrie de apărare și achiziții / capacități comune','Consorții și entități eligibile, cu cerințe stricte de securitate',company='Condiționat',public='Da')
add('EDF','European Defence Fund – EDF','EDF','Cercetare și dezvoltare colaborativă în apărare','Companii și institute eligibile',company='Da',public='Da',partnership='Consorțiu eligibil; restricții privind țara și controlul',note='EDIP și EDF au reguli și bugete diferite.')
add('JTM','Just Transition – Public Sector Loan Facility','EU_catalog','Investiții publice în teritorii cu planuri de tranziție eligibile','Entități publice / entități mandatate eligibile',public='Da',instrument='Grant CE asociat unui împrumut BEI',mode='CINEA + BEI',note='Nu este grant general pentru IMM; verificare teritoriu și împrumut.')
add('EFSA','Granturi EFSA – organisme competente','SMP','Cooperare științifică în siguranța alimentară','Organisme competente eligibile în rețeaua EFSA',public='Condiționat',ngo='Condiționat',note='Nu este acces general pentru SRL; trebuie îndeplinite condițiile EFSA și ale apelului.')
add('PPPA','Proiecte-pilot și acțiuni pregătitoare – PPPA','EU_catalog','Teme punctuale ale bugetului UE','Entități eligibile potrivit apelului',company='Condiționat',ngo='Condiționat',public='Condiționat')
add('EUIPO','EUIPO SME Fund 2026 – vouchere PI','EUIPO','Mărci, desene, brevete și servicii de proprietate intelectuală','IMM-uri stabilite în UE, inclusiv România',company='Da',mode='Direct EUIPO',instrument='Voucher / rambursare',deadline='2026-12-04',status='Perioadă de aplicare; verificare disponibilitate voucher',note='Aprobarea voucherului precede cheltuiala; plafon și rambursare diferite pe voucher.')

# Norvegia / SEE: memorandumurile stabilesc programe, nu termene de apel.
new_n=[('N01','Green Transition',84_000_000,'Ministerul Mediului, Apelor și Pădurilor','Tranziție verde, economie circulară, biodiversitate și guvernanță'),('N02','Clean Energy Transition',40_000_000,'Innovation Norway / FMO','Energie curată, comunități energetice și proiecte inovatoare'),('N03','Green Business and Innovation',50_000_000,'Innovation Norway / FMO','Afaceri verzi, inovare și antreprenoriat'),('N04','Research and Innovation',45_000_000,'UEFISCDI','Cercetare și inovare'),('N05','Local Development',93_600_000,'Fondul Român de Dezvoltare Socială','Dezvoltare locală, incluziune, sănătate și educație'),('N06','Culture',40_000_000,'Ministerul Culturii','Patrimoniu, diversitate și participare culturală'),('N07','Justice',51_000_000,'Ministerul Justiției','Justiție, drepturi și servicii corecționale'),('N08','Home Affairs',43_400_000,'Ministerul Afacerilor Interne','Siguranță, migrație și protecție civilă'),('N09','Institutional Cooperation and Capacity Building',32_000_000,'MIPE','Cooperare instituțională, transparență și combaterea dezinformării')]
for id,title,budget,operator,what in new_n:
    add(id,'SEE / Norvegia 2021–2028 – '+title,'Norway_New',what,'Categorii finale de solicitanți de stabilit în ghidurile apelurilor',group='SEE',company='Condiționat' if id in ['N01','N02','N03','N04','N06'] else 'Nu',ngo='Condiționat',public='Condiționat',mode='Operator: '+operator,budget=f'{budget:,} EUR – alocare de program',status='Program convenit; apel deschis neconfirmat',apply='https://eeagrants.org/en/fmo/news/renewed-cooperation-romania',note='Memorandum / alocare confirmate. Nu echivalează cu apel deschis. Ghid specific neidentificat la verificare.')
csf_titles=['Democrație și stat de drept','Participare civică în comunități insuficient deservite','Drepturi ale omului și justiție socială','Diversitate, egalitate și combaterea violenței de gen','Incluziunea romilor și comunități interetnice','Drepturi ale omului prin acțiuni de mediu și climă','Dezvoltare organizațională pentru ONG-uri și federații experimentate']
for i,title in enumerate(csf_titles,1):
    key='CSF_'+str(i);d=json.loads((CACHE/(key+'.json')).read_text(encoding='utf8'));t=d['text']
    def field(label):
        m=re.search(re.escape(label)+r'\s*\n([^\n]+)',t);return m.group(1) if m else ''
    add('CSF'+str(i),'EEA Civil Society Fund – Apel '+str(i)+' '+title,key,title,'ONG-uri nonprofit constituite legal în România; condiții suplimentare în ghid',group='SEE',ngo='Da',mode='FDSC și consorțiul operator, independent de autoritățile naționale',amount=field('Grant amount from')+' – '+field('Grant amount to'),budget=field('Amount available')+' – buget apel',deadline='2026-10-08',status='Deschis',partnership='Potrivit ghidului; Apel 7: fără parteneriat',apply='https://finantaripublice.fdsc.ro/',note='Persoanele fizice și SRL-urile nu sunt solicitanți direcți. Ghiduri RO și EN plus anexe publicate.')

# Cele 11 programe elvețiene; alocările nu sunt plafoane per beneficiar.
swiss=[('CH01','Învățământ dual – Dual VET','Școli și firme participante în sistemul dual','Condiționat','Da'),('CH02','Cooperare internațională în cercetare','Instituții / echipe de cercetare; componente MAPS și ELI-NP','Condiționat','Da'),('CH03','Infrastructură de cercetare și monitorizare a emisiilor','Instituții de cercetare desemnate','Nu','Da'),('CH04','SME ECO-TECH – finanțare pentru IMM','IMM-uri private de producție eligibile','Da','Nu'),('CH05','Siguranță publică – Afaceri interne','Instituții desemnate din afaceri interne','Nu','Da'),('CH06','Siguranță publică – Justiție','Instituții desemnate din justiție','Nu','Da'),('CH07','Eficiență energetică și energie regenerabilă','Orașe selectate și instituții desemnate','Nu','Da'),('CH08','Acces la rețeaua de metrou București','Instituții desemnate / Metrorex','Nu','Da'),('CH09','Sănătate','Instituții și operatori desemnați în program','Nu','Da'),('CH10','Incluziune socială','Instituții și organizații eligibile în implementare','Nu','Da'),('CH11','Implicare civică și transparență','ONG-uri nonprofit eligibile','Nu','Condiționat')]
for id,title,who,co,pu in swiss:
    add(id,'Elveția – '+title,'Swiss_RO',title,who,group='CH',company=co,ngo='Da' if id=='CH11' else 'Condiționat' if id=='CH10' else 'Nu',person='Beneficiar indirect',public=pu,mode='Operator român / consorțiu / bănci, potrivit programului',instrument='Grant + credit' if id=='CH04' else 'Grant / program desemnat',rate='Grant până la 40%; credit minimum 60%' if id=='CH04' else 'Conform componentei / apelului',status='Program în implementare; accesul se verifică la operator',apply='https://www.swiss-contribution.ro/',note='Perioada de eligibilitate a cheltuielilor până la 03.12.2029 nu este termen de depunere. Nu toate programele au apel competitiv pentru firme.')
add('CHMAPS','Elveția – MAPS, Multilateral Academic Projects','Swiss_MAPS','Proiecte comune de cercetare','Echipe de cercetare din Elveția și țările participante, inclusiv România',group='CH',public='Da',person='Prin instituție',mode='SNSF + UEFISCDI',status='Apel închis; proiecte în implementare',deadline='2024-07-01',note='Componentă a CH02; nu dublează bugetul programului.',parent='CH02')
for i,am in [(1,'500.000–1.500.000 CHF'),(2,'50.000–200.000 CHF')]:
    add('CHC'+str(i),'Elveția – Implicare civică, Apel '+str(i),'Swiss_Civic_'+str(i),'Proiecte strategice' if i==1 else 'Proiecte locale','ONG-uri eligibile potrivit ghidului',group='CH',ngo='Da',mode='FDSC / Fundația pentru Parteneriat / KEK-CDC',amount=am,status='Închis; selecție / implementare',deadline='2025-12-17' if i==2 else '',apply='https://finantaripublice.fdsc.ro/',note='Ghid și anexe păstrate în arhivă; nu este apel nou deschis.',parent='CH11')
add('CHSCH','Burse de excelență ale Guvernului Elveției 2027–2028','Swiss_Scholarship','Cercetare / formare în Elveția','Candidați individuali din țările eligibile; oferta pentru România se verifică separat',group='CH',person='Condiționat',mode='Confederația Elvețiană / FCS',instrument='Bursă',amount='Conform tipului bursei și ofertei de țară',status='Ediție 2027–2028 publicată; termen România neconfirmat',apply='https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships',note='Finanțarea unui cetățean român pentru activitate în Elveția; nu este grant pentru investiție în România.')

# Alte organisme europene și instrumente cu intermediere declarată.
add('EUROSTARS','Eureka / Eurostars','Eureka','CDI transnațională condusă de IMM inovatoare','IMM inovatoare și parteneri eligibili; România participantă',group='ALTE',company='Da',public='Condiționat',mode='Evaluare Eureka; finanțare prin organismul național',partnership='Minimum 2 parteneri independenți din 2 țări Eurostars',status='Apel septembrie 2026 închis',deadline='2026-09-10',apply='https://www.eurekanetwork.org/programmes/eurostars/',note='Nu este grant plătit direct de CE către firma română; verificare buget și reguli naționale.')
add('INNOWWIDE','Eureka – Innowwide','Innowwide_Call','Fezabilitate de piață internațională pentru soluții inovatoare','IMM-uri din UE / țări eligibile; partener local pe piața-țintă',group='ALTE',company='Da',mode='Eureka, cu finanțare UE',amount='60.000 EUR / proiect; verificare ghid ediția 5',status='Apel ediția 5 – verificare termen pe pagina oficială',apply='https://www.eurekanetwork.org/programmes/innowwide/')
add('COST','COST – rețele, mobilități și networking','COST','Rețele științifice, vizite, școli de formare și conferințe','Cercetători și inovatori; instituții participante',group='ALTE',company='Condiționat',person='Da, prin acțiune / rambursare',public='Da',mode='COST Association / titularul grantului acțiunii',instrument='Grant de networking / rambursare',deadline='2026-10-28',status='Deschis – OC-2026-1',partnership='Rețea eligibilă potrivit ghidului COST',note='COST nu finanțează cercetarea propriu-zisă.')
add('ESABASS','ESA – Business Applications and Space Solutions','ESA_BASS','Aplicații comerciale care folosesc tehnologii / date spațiale','Companii și organizații din statele participante; România inclusă',group='ALTE',company='Da',ngo='Condiționat',mode='Direct ESA; acordul delegației naționale unde este cerut',instrument='Cofinanțare de proiect',status='Open competition; ferestre tematice separate',apply='https://business.esa.int/funding',note='Participarea țării la programul ESA și acordul delegației se verifică înainte de depunere.')
add('ESAINC','ESA InCubed','ESA_Incubed','Produse și servicii comerciale de observare a Pământului','Companii din țări participante; disponibilitatea bugetului pentru România de verificat',group='ALTE',company='Condiționat',mode='Direct ESA, cu susținerea delegației naționale',instrument='Cofinanțare',apply='https://incubed.esa.int/additional-application-information/')
add('EIBLOAN','BEI – împrumuturi directe pentru investiții','EIB','Investiții eligibile ale companiilor și sectorului public','Companii / promotori și autorități eligibile',group='ALTE',company='Da',public='Da',mode='Direct BEI pentru proiecte eligibile',instrument='Împrumut',apply='https://www.eib.org/en/products/loans/index',note='Finanțare rambursabilă; nu grant. IMM-urile pot accesa separat finanțare prin bănci.')
add('ELENA','BEI / CE – ELENA','EIB_ELENA','Pregătirea investițiilor în eficiență energetică și mobilitate','Entități publice și private eligibile',group='ALTE',company='Da',public='Da',mode='Direct BEI',instrument='Grant de asistență tehnică',rate='Până la 90% din costul eligibil de pregătire',apply='https://www.eib.org/en/products/advisory-services/elena/index',note='Finanțează pregătirea investiției; nu costul lucrărilor.')
add('EIF','FEI / InvestEU – finanțare prin intermediari','EIF','Credite, garanții, capital și microfinanțare','IMM, mid-cap, microîntreprinderi și întreprinderi sociale eligibile',group='ALTE',company='Da',mode='Bănci / fonduri / intermediari financiari',instrument='Credit / garanție / capital',apply='https://www.eif.org/',note='Accesul beneficiarului final este prin intermediar, nu cerere de grant la FEI.')
add('EBRD','BERD – Advice for Small Businesses','EBRD','Consultanță și transformarea IMM','IMM eligibile în țările de operare, inclusiv România; condiții la biroul local',group='ALTE',company='Condiționat',mode='BERD / program de consultanță local',instrument='Cofinanțare de consultanță',apply='https://www.ebrd.com/home/work-with-us/advice-for-small-businesses.html',note='Disponibilitatea efectivă și contribuția beneficiarului se confirmă pentru România.')
add('EYF','Consiliul Europei – European Youth Foundation','EYF','Proiecte și activități ale organizațiilor de tineret','ONG-uri de tineret eligibile / înregistrate',group='ALTE',ngo='Da',mode='Direct Consiliul Europei',instrument='Grant',apply='https://www.coe.int/en/web/european-youth-foundation',status='Program existent; apel curent neconfirmat',note='Reguli și termene de verificat; descărcarea paginii a fost blocată de server.')
add('EYE','Erasmus for Young Entrepreneurs','EYE','Schimburi între antreprenori noi și experimentați','Antreprenori noi / aspiranți și antreprenori gazdă eligibili',group='ALTE',company='Da',person='Da, ca antreprenor eligibil',mode='Prin organizații intermediare ale programului',instrument='Sprijin pentru mobilitate',apply='https://www.erasmus-entrepreneurs.eu/',note='Nu finanțează achiziția de utilaje sau investiția inițială a firmei.')

def topic_program(identifier):
    u=identifier.upper()
    for token,id in [('HORIZON-HLTH','HCL1'),('HORIZON-NATURE','HHOR'),('HORIZON-BRIDGING','HHOR'),('HORIZON-EURATOM','EURATOM'),('HORIZON-EIC-2026-DEFENCE','EICD'),('HORIZON-EIT-2026-PRIZE','EIT'),('HORIZON-EIC-2026-PRIZE','EIT')]:
        if u.startswith(token):return id
    for token,id in [('HORIZON-JU-IHI','JUHI'),('HORIZON-JU-CBE','JUBB'),('HORIZON-JU-CLEANH2','JUHY'),('HORIZON-JU-CLEAN-AVIATION','JUCA'),('HORIZON-JU-ER','JURA'),('HORIZON-JU-SNS','JUSN'),('HORIZON-SESAR','JUSR'),('HORIZON-JU-CHIPS','JUCH'),('HORIZON-JU-EUROHPC','JUHP'),('HORIZON-EIC-ACCELERATOR','EICA'),('HORIZON-EIC-2026-ACCELERATOR','EICA'),('HORIZON-EIC-2026-STEP','EICS'),('HORIZON-EIC-2026-PATHFINDER','EICP'),('HORIZON-EIC-2026-TRANSITION','EICT')]:
        if u.startswith(token):return id
    for i in range(1,7):
        if u.startswith('HORIZON-CL'+str(i)):return 'HCL'+str(i)
    for token,id in [('HORIZON-MSCA','MSCF' if 'COFUND' in u else 'MSDN' if 'DN' in u else 'MSPF' if 'PF' in u else 'MSSE' if 'SE-' in u else 'MSCZ'),('HORIZON-WIDERA','HWID'),('HORIZON-EIE','HEIE'),('HORIZON-INFRA','HINF'),('HORIZON-MISS','HMIS'),('HORIZON-NEB','HNEB'),('HORIZON-RAISE','HHOR'),('HORIZON-CID','HHOR'),('HORIZON-BIODIV','HHOR'),('ERC','ERCST' if '-STG' in u else 'ERCCO' if '-COG' in u else 'ERCAD' if '-ADG' in u else 'ERCSY' if '-SYG' in u else 'ERCPO'),('DIGITAL-ECCC','DIGECCC'),('DIGITAL-JU-CHIPS','JUCH'),('DIGITAL','DIG'),('CEF-T','CEFT'),('CEF-DIG','CEFD'),('CEF-E','CEFE'),('CREA-MEDIA','CREAM'),('CREA-CULT','CREAC'),('CREA','CREAX'),('CERV','CERV'),('JUST','JUST'),('ISF','ISF'),('AMIF','AMIF'),('EDF-EDIP','EDIP'),('EDF','EDF'),('I3','I3'),('JTM','JTM'),('LIFE','LIFEN' if '-NAT-' in u else 'LIFEC' if '-CLIMA-' in u else 'LIFEE'),('ERASMUS','ERASMUS'),('ESF','EASI'),('SOCPL','SOCPL'),('PPPA','PPPA'),('EUBA-EFSA','EFSA'),('SMP-FOOD','SMPFOOD'),('SMP','SMP')]:
        if u.startswith(token):return id
    return 'EU01'

if __name__=='__main__':
    (BASE/'catalogue.json').write_text(json.dumps(ROWS,ensure_ascii=False,indent=2),encoding='utf8')
    print('Programe / scheme',len(ROWS))
