from pathlib import Path
from copy import deepcopy
import json, shutil, hashlib
from docx import Document
from docx.shared import Pt
from docx.oxml import OxmlElement
from docx.text.paragraph import Paragraph
from docx.table import Table

ROOT=Path('D:/00. Downloads/Apartamente Viena/00. Cladire 1 Schallergasse 35, 1120 Wien (Meidling)')
BASE=ROOT/'04. Firme + Executie/01. Verificator (Pruefingenieur)/TOMS'
OUT=BASE/'2026-10-01 Contract v3 - propunere'
OUT.mkdir(exist_ok=True)
WORK=OUT/'_lucru'; WORK.mkdir(exist_ok=True)
d=Document(next(BASE.glob('*v2.2).docx')))
ps=list(d.paragraphs); ts=list(d.tables)
def p(i,text):
    x=ps[i]
    for r in x.runs:r.text=''
    if x.runs:x.runs[0].text=text
    else:x.add_run(text)
def remove(x):
    e=x._element;e.getparent().remove(e)
def table(j,rows):
    t=ts[j]
    template=deepcopy(t.rows[1]._tr if len(t.rows)>1 else t.rows[0]._tr)
    while len(t.rows)>1:t._tbl.remove(t.rows[-1]._tr)
    for k,vals in enumerate(rows):
        if k:t._tbl.append(deepcopy(template))
        for c,v in zip(t.rows[k].cells,vals):c.text=str(v)
    for ri,r in enumerate(t.rows):
        for c in r.cells:
            for pp in c.paragraphs:
                pp.paragraph_format.space_after=Pt(4)
                for run in pp.runs:run.font.size=Pt(9);run.bold=(ri==0)
        pr=r._tr.get_or_add_trPr()
        no=OxmlElement('w:cantSplit');pr.append(no)
    return t

p(1,'Tragwerksplanung / Ausführungsstatik, statische Betreuung, Prüfingenieur-Leistungen und Bauwerksbuch')
p(9,'(1) Der AN erbringt für das Bauvorhaben Wohnhaus Schallergasse 35, 1120 Wien (Gründerzeithaus, Baujahr 1905, Keller, Erdgeschoss, drei Obergeschosse, zweigeschossiger Dachgeschossausbau und Aufzugszubau) die Leistungen gemäß §§ 2 bis 7 und den Anlagen dieses Vertrages.')
p(11,'(3) Planungsgrundlage sind die genehmigten Einreichpläne P2041 (20.04.2023) sowie die von der AG bei Vertragsunterzeichnung im privaten Projektportal https://www.ac-wohnart.at/portal bereitgestellten Architektur-, Bestands- und Fachplanungen, insbesondere der Architekturstand 08.09.2026 und die dort hinterlegten Dachgeschosspläne. Dieser Stand wird durch eine gemeinsame Planliste mit Dateinamen, Index und Datum festgehalten und als Anlage 7 dokumentiert. Er ersetzt als Bearbeitungsgrundlage den früheren Architekturstand 12.08.2026; die bewilligten Unterlagen bleiben für den Bewilligungsabgleich maßgeblich.')
p(13,'1. dieser Werkvertrag vom 01.10.2026 samt Anlagen 1 bis 4, 6 und 7;')
p(14,'2. die unterzeichnete, korrigierte Reinschrift vom 23.09.2026 (Anlage 5) sowie der unterzeichnete Fragenkatalog 2 vom 28.09.2026 (Anlage 5b), soweit sie den hier beauftragten Leistungsumfang betreffen; bei Widersprüchen zwischen diesen beiden Unterlagen geht die spätere Erklärung vor; der Original-Scan vom 18.09.2026 (Anlage 5a) dient ergänzend der Dokumentation;')
p(15,'3. die schriftliche Bestätigung der Angebotsgültigkeit durch TOMS vom 23.09.2026;')
p(16,'4. die Angebote ANG 855 vom 03.09.2026, ANG 839 vom 20.08.2026 und ANG 891 vom 23.09.2026;')
p(18,'(5) Bei Widersprüchen gelten die ausdrücklichen Regelungen dieses Werkvertrages und seiner Anlagen 1 bis 4 vorrangig. Die früheren Fragebögen und Angebote erweitern den hier vereinbarten Auftrag nicht um andere Leistungsbereiche. Die vorliegende Fassung ist ein Vertragsangebot der AG; sie wird erst durch beiderseitige Unterzeichnung verbindlich.')
p(26,'zweigeschossiger Dachgeschossausbau nach der Planungsgrundlage gemäß § 1 Abs. 3: Tragkonstruktion Holz/Stahl samt Führungsplanung, Dachstuhl, Gaupen, Attika und Terrassen;')
p(29,'Stiegen (Bestand und neu), Stiegenhauswände, Podeste und Anschlüsse Neu/Alt innerhalb des in § 3 und Anlage 2 festgelegten Detaillierungsgrades;')
p(41,'(2) Der AN übernimmt die Statische Vorbemessung samt Fundierungskonzept und Mauerwerksgutachten (Ausfertigung Jänner 2022), einschließlich Lastannahmen, statischem System, Mauerwerkskennwerten und Fundierungskonzept, als Grundlage. Er prüft und schreibt sie in eigener Verantwortung zu einer neuen, unterfertigten Ausführungsstatik auf den Planstand gemäß § 1 Abs. 3 fort. Diese Fortschreibung ist im Pauschalpreis enthalten.')
p(44,'(1) Die vom AN geschuldeten Unterlagen müssen für den vereinbarten Leistungsumfang prüffähig, nachvollziehbar und aufeinander abgestimmt sein. Dabei gilt:')
p(45,'Die ausführenden Firmen erhalten die statische Bemessung und Führungsplanung als Grundlage für ihre Werkstatt- und Abbundplanung; die Abgrenzung der gesonderten Detailplanung richtet sich nach § 6 Abs. 1 und Anlage 2.')
p(46,'Vor Ausführung eines Bauteils müssen auch die dafür erforderlichen, gesondert beauftragten Detail- und Werkstattpläne vorliegen und im vereinbarten Umfang vom AN freigegeben sein.')
p(47,'Die Prüfung und Freigabe der von Dritten erstellten Werkstattpläne und Nachweise bleibt Bestandteil der Leistung des AN.')
p(49,'(3) Die Anschluss-, Auflager- und Verankerungskräfte je Knoten (Normal-, Quer- und Zugkräfte sowie Momente) sind vom AN sowohl in der statischen Berechnung als auch unmittelbar auf den zugehörigen Führungs-, Positions- bzw. Lastplänen eindeutig und positionsbezogen einzutragen. Ein bloßer Verweis auf die statische Berechnung genügt nicht. Gesonderte Bauteillisten im Plan sind hiervon nicht umfasst.')
p(50,'(4) Im Pauschalhonorar von EUR 25.000,00 netto sind ohne zusätzliches Entgelt enthalten: die Bemessung sämtlicher Knoten und Anschlüsse im Stahl- und Holzbau; die Bemessung und Spezifikation der Dübel und Anker in Mauerwerk bzw. Beton mit Typ, Größe, Anzahl sowie Rand- und Achsabständen; die Festlegung der erforderlichen Blechdicken sowie der Art und Dicke der Schweißnähte. Die Ergebnisse sind in der prüffähigen statischen Berechnung eindeutig den jeweiligen Positionen zuzuordnen. Die darüber hinausgehende zeichnerische Detailausarbeitung und die allgemeine Verbindungsmittelspezifikation sind nach § 6 Abs. 1 abgegrenzt; die hier ausdrücklich eingeschlossenen Dübel-, Anker-, Blech- und Schweißnahtangaben bleiben enthalten.')
p(51,'(5) Fehlende oder fehlerhafte Angaben innerhalb des vereinbarten Leistungsumfangs ergänzt oder berichtigt der AN binnen fünf Werktagen ohne gesondertes Honorar. Die nach § 6 ausdrücklich ausgeschlossenen Zusatzleistungen werden dadurch nicht in das Pauschalhonorar einbezogen; ihre Erbringung bedarf einer gesonderten schriftlichen Beauftragung.')
p(89,'(4) Der Pauschalpreis von ANG 839 beträgt unverändert EUR 8.000,00 netto. Die bis 31.12.2026 verlängerte Angebotsgültigkeit wurde durch TOMS mit E-Mail vom 23.09.2026 bestätigt.')
p(91,'(1) Nicht im Pauschalhonorar enthalten sind folgende Leistungen. Die unter lit. a beschriebenen Zusatzleistungen können gegen gesondertes Entgelt erbracht werden; der AN legt hierfür auf Anfrage ein positionsweise bepreistes Angebot vor. Eine Ausführung oder Vergütung setzt die vorherige schriftliche Beauftragung durch die AG voraus:')
p(92,'a) Zusätzliche Detailplanung Stahl-/Holzbau: zeichnerische Knoten- und Anschlussdetails (Prinzip- und Ausführungsdetails, insbesondere 1:10/1:20); allgemeine Spezifikation von Verbindungsmitteln nach Art, Größe, Anzahl und Anordnung, soweit nicht ausdrücklich von § 3 Abs. 4 erfasst; Bauteillisten auf den Plänen mit Werkstoffgüten, Querschnitten/Profilen, Längen, Stückzahlen und Positionsnummern; Detailausarbeitung der Anschlüsse von Aussteifungen und Windverbänden; besondere Vorgaben zu Korrosions- und Holzschutz sowie Nutzungs- und Festigkeitsklassen nach Abschnitt A Z 11 des Fragenkatalogs 2. Die statisch notwendigen Bemessungsannahmen und Materialkennwerte der Berechnung bleiben Teil der Grundleistung. Werkstatt- und Abbundpläne sowie gesonderte Werkstattstücklisten werden durch die ausführenden Firmen oder nach gesonderter Beauftragung erstellt; Prüfung und Freigabe durch den AN sind enthalten.')
p(106,'(2) Die Ausschlüsse nach Abs. 1 sind abschließend. Die ausdrücklich eingeschlossenen Leistungen nach § 3 Abs. 3 und 4 werden durch die allgemeine Abgrenzung nicht eingeschränkt. Für die übrigen ausgeschlossenen Fachleistungen sorgt die AG durch geeignete Dritte. Vor Ausführung eines Bauteils stimmen AG, AN und ausführende Firma die Vollständigkeit der notwendigen Unterlagen ab.')
p(116,'(5) Die AG stellt die vorhandenen Bestands-, Baugrund-, Bewilligungs- und Planarchivunterlagen über das Projektportal bereit. Der AN bestätigt den erfolgreichen Zugriff und benennt bis 06.10.2026 konkret fehlende oder unleserliche Unterlagen. Entsprechend seiner Mitteilung vom 24.09.2026 sind vollständige historische Planblätter von der Ersteinreichung bis zum aktuellen Stand erforderlich; Planköpfe allein genügen nicht. Die gemeinsame Bestands- und Planliste gemäß Anlage 7 dokumentiert Empfang und Bearbeitungsgrundlage.')
p(118,'§ 7  Bauwerksbuch gemäß § 128a BO für Wien')
p(119,'(1) Mit diesem Vertrag wird auch die Erstellung des Bauwerksbuchs für das gesamte Gebäude einschließlich Bestand sowie Zu- und Umbau auf Grundlage von ANG 891 zum unveränderten Pauschalpreis von EUR 3.400,00 netto beauftragt. Enthalten sind die in Anlage 1 genannten Inhalte, die erforderliche Erstprüfung, die gesetzlich erforderlichen Bestätigungen und die Registrierung bei der MA 37 einschließlich Übermittlung des Registrierungsnachweises an die AG.')
p(120,'(2) Der AN erstellt das Bauwerksbuch baubegleitend. Die AG teilt den vorgesehenen Abschluss- und Anzeigetermin mindestens sechs Wochen vorher mit; der AN benennt fehlende Unterlagen binnen fünf Werktagen. Eine prüffähige Vorfassung ist 20 Werktage, die endgültige digitale Fassung samt erforderlichen Bestätigungen und Nachweis der Registrierung spätestens zehn Werktage vor der vorgesehenen Fertigstellungsanzeige zu übergeben. Der Termin wird mit Endbeschau und Abnahme abgestimmt. Soweit Endbefunde erst bei der Endbeschau entstehen, sind sie binnen fünf Werktagen danach, jedenfalls vor Erstattung der Fertigstellungsanzeige, einzuarbeiten. Eine früher eintretende gesetzliche Frist geht vor; insbesondere sind Erstellung und Registrierung für den Bestand Baujahr 1905 spätestens bis 31.12.2027 sicherzustellen, auch wenn die Bauarbeiten später enden. Notwendige Aktualisierungen bis zur Fertigstellungsanzeige sind im Honorar enthalten. Ausgenommen sind die gesonderte Foto-/Rissdokumentation vor und nach dem Umbau sowie ein zusätzliches umfassendes Plan- und Dokumentenverzeichnis mit Ablageorten; die gesetzlich notwendigen Inhalte und die Übernahme von der AG beigestellter erforderlicher Unterlagen bleiben geschuldet.')
p(122,'(1) Vertragsdatum und Ausgangspunkt der vereinbarten Fristen ist der 01.10.2026 bei beiderseitiger Unterzeichnung an diesem Tag. Bearbeitungsbeginn ist der 01.10.2026, spätestens jedoch der 06.10.2026 (drei Werktage danach). Die Unterfertigung erfolgt mit dem tatsächlichen Unterschriftsdatum. Erfolgt sie später, ist ein entsprechend angepasster Terminplan schriftlich gemeinsam festzulegen; ein Bearbeitungsbeginn wird nicht rückwirkend fingiert. Werktage sind Montag bis Freitag, ausgenommen gesetzliche Feiertage in Wien.')
p(123,'(2) Die vollständige prüffähige statische Berechnung einschließlich Bemessungsgrundlagen für sämtliche Dossiers ist binnen drei Kalenderwochen ab beiderseitiger Unterzeichnung, bei Unterzeichnung am 01.10.2026 somit bis 22.10.2026, zu liefern. Frühere Teillieferungen und die gesonderten Plantermine ergeben sich aus Anlagen 3 und 4: D1 bis 09.10., D2 bis 16.10., D3 bis 23.10. sowie D4 und D5 bis 28.10.2026. Die späteren Plantermine verschieben die Frist für die statische Berechnung nicht.')
p(124,'(3) Die Objektbegehung durch Dipl.-Ing. Ferdinand Toms erfolgt spätestens bis 08.10.2026; sofern bereits erfolgt, ist das Protokoll bis zu diesem Termin nachzureichen. Der AN schlägt bei Vertragsunterzeichnung zwei Termine vor. Die Koordination vor Ort übernimmt Frau Anastasia Covaciu; bevorzugt morgens um 08:00 Uhr oder nach 16:00 Uhr.')
p(129,'(1) Übergabe als unterfertigte, behördentaugliche und prüffähige PDF-Dateien, zusätzlich DWG (AutoCAD 2018 oder älter), DXF und IFC-Export (IFC 2x3 oder IFC 4). Die Führungsplanung wird im Darstellungsmaßstab 1:50 übergeben. Zeichnungseinheiten und Maßbezug sind eindeutig anzugeben, damit die CAD-Daten maßhaltig weiterverarbeitet werden können. DWG-Dateien werden mit jeder Planrevision geliefert. Nicht vereinbart sind getrennte Layer nach Gewerken mit sämtlichen Positionsangaben als Text, die native Berechnungsmodelldatei, zusätzliche Bewehrungs-/Biegelisten in Excel/CSV sowie BTL/BVX- und NC/DSTV-Daten.')
p(137,'(3) Fehlende Positionen innerhalb des vereinbarten Dossierumfangs ergänzt der AN binnen fünf Werktagen; erst nach vollständiger Lieferung und Freigabe beginnt die Zahlungsfrist für die betreffende Rate.')
p(141,'(1) Die Beträge sind Festpreise für die in §§ 2 bis 7 sowie Anlagen 1 und 2 vereinbarten Leistungen. Sie bleiben über die Vertragsdauer unverändert. Der Gesamtpreis beträgt EUR 37.900,00 netto zuzüglich 20 % USt, somit EUR 45.480,00 brutto. Zusatzleistungen gemäß § 6 sind darin nicht enthalten.')
p(142,'(2) Die Mehraufwandsklausel „mehr als 10 % Aufwand“ der Angebote begründet keine automatische Preiserhöhung. Änderungen außerhalb des vereinbarten Umfangs bedürfen vor Ausführung einer schriftlichen Beschreibung, Preisvereinbarung und Freigabe der AG. Für eigene Korrekturen des AN, Ergänzungen nach § 3 Abs. 5, die in § 14 eingeschlossene Änderungsschleife, Behördenrückfragen und Abstimmungen innerhalb des vereinbarten Umfangs sowie die bestätigten Anpassungen im Zuge des Abbruchs entsteht kein Mehrhonorar.')
p(146,'(6) Rechnungsanschrift: A&C Wohnart Immobilien GmbH, Schallergasse 35, 1120 Wien, FN 668224h. Die irrtümlich zugestellte Rechnung 77260142 über EUR 540,00 der Toms Consult ZT GmbH betrifft das Objekt Wurmbstraße 48 und weder die AG noch dieses Bauvorhaben; die Richtigstellung wurde von TOMS am 22.09.2026 per E-Mail bestätigt.')
p(149,'(2) Die aufrechte Befugnis der Gesellschaft und von Dipl.-Ing. Ferdinand Toms sowie der Firmenbuchstand werden durch die Unterlagen in Anlage 7 dokumentiert. Die bereits am 23.09.2026 übermittelten Unterlagen werden berücksichtigt; der AN wird höflich um Ergänzung der noch fehlenden Nachweise vor Unterzeichnung gebeten.')
p(155,'(1) Grundlage des vereinbarten Versicherungsnachweises ist die Generali-Bestätigung vom 03.03.2026 zur Berufshaftpflichtversicherung, Polizze 381-8983-5485, für die Toms Ziviltechniker GmbH, einschließlich der dort genannten mitversicherten Personen und Gesellschaft. Maßgeblich sind der bestätigte Deckungsumfang und die zugrunde liegenden Versicherungsbedingungen; dieser Vertrag erweitert die Deckungszusage des Versicherers nicht.')
p(156,'(2) Akzeptiert wird die bestätigte Pauschalversicherungssumme von EUR 1.500.000,00 für Personen-, Sach- und reine Vermögensschäden zusammen, mit zweifachem Jahresaggregat. Der vom AN angegebene Selbstbehalt von EUR 10.000,00 geht zu seinen Lasten; diese Angabe ist von der Deckungsbestätigung des Versicherers zu unterscheiden.')
p(157,'(3) Die AG akzeptiert die vorliegende Bestätigung vom 03.03.2026 mit Versicherungszeitraum 01.01.2026 bis 01.01.2027 und laut Bestätigung bis 01.01.2027 bezahlter Prämie; eine Neuausstellung allein wegen des Ausstellungsdatums wird nicht verlangt. Der AN wird höflich gebeten, vor Unterzeichnung die Bestätigung samt zugehörigen Deckungs-/Polizzenunterlagen nochmals beizulegen bzw. deren unveränderten Bestand zu bestätigen. Für die Dauer der Leistungserbringung hält der AN die Versicherung aufrecht und übermittelt vor Ablauf den Fortführungsnachweis; wesentliche Änderungen werden der AG unverzüglich mitgeteilt.')
p(158,'(4) Die Nachdeckung wird entsprechend der vorliegenden Generali-Bestätigung als unbegrenzt dokumentiert, jeweils nach Maßgabe der Versicherungsbedingungen.')
p(162,'(2) Nach der von der AG über das Projektportal bereitgestellten Planung der Architektin sind eine Reduktion von Wänden und der Anzahl der Wohnungen vorgesehen. Eine Erweiterung des strukturellen Baukonzepts ist nach dieser Planungsvorgabe nicht beabsichtigt. Die AG bezeichnet die bei Unterzeichnung bereitgestellten Pläne als zu rund 99 % abgeschlossen. Weitere Änderungen sollen sich nur aus der Abstimmung mit dem AN ergeben, wenn dessen Berechnungen eine Anpassung erforderlich machen, oder aus behördlichen Anforderungen. Die technische Beurteilung der Auswirkungen auf Tragwerk und Bewilligung bleibt Aufgabe der befugten Planer; die Beschreibung ersetzt keinen statischen Nachweis. Im Pauschalhonorar enthalten ist eine einmalige zusammengefasste Planwechsel-/Änderungsbearbeitung für die genannten Reduktionen, die aus den Berechnungen erforderlichen Anpassungen innerhalb dieses Konzepts oder entsprechende Anforderungen der Behörde. Der AN stellt dafür die statischen Unterlagen bereit und stimmt sie mit der Architektin ab; diese übernimmt die architektonische Einreichplanung. Weitere von der AG gewünschte Konzeptänderungen oder zusätzliche selbständige Änderungsverfahren werden vorab nach § 11 Abs. 2 vereinbart. Die Behebung eigener Planungsfehler gilt nicht als zusätzliche Änderungsschleife. Zwingende behördliche Anforderungen bleiben zu erfüllen und sind unverzüglich mit der AG hinsichtlich Umfang und Termin abzustimmen.')
p(163,'(3) Die fachliche Abstimmung mit der MA 37 zu tragwerksbezogenen Rückfragen innerhalb des vereinbarten Auftrags ist im Pauschalpreis enthalten. Der AN weist auf relevante Fristen hin; die Prüfung der Rechtskraft des Baubescheids obliegt der AG bzw. ihrem Rechtsanwalt. Eine bestimmte behördliche Entscheidung wird durch diesen Vertrag nicht vorweggenommen.')
p(164,'(4) Die Meldung zum Baubeginn erfolgt durch AG bzw. Bauführer; der AN stellt die erforderlichen statischen Beilagen bereit.')
p(165,'§ 15  Vertragsunterlagen und Ergänzungen vor Unterzeichnung')
p(166,'(1) Der vorliegende Vertrag mit Leistungsabgrenzung, Detaillierungsgrad sowie Dossier-, Termin- und Zahlungsplan bildet das konsolidierte Vertragsangebot. Der AN wird gebeten, dieses zu prüfen und firmenmäßig unterzeichnet zurückzusenden oder gewünschte Änderungen schriftlich mitzuteilen. Eine gesonderte, inhaltsgleiche Neuausstellung der Angebote ist nicht erforderlich.')
p(167,'(2) Die bereits vorliegenden Nachweise sind in Anlage 7 aufgeführt. Der AN wird höflich gebeten, vor Unterzeichnung die dort noch offenen Nachweise und Angaben zu ergänzen sowie die Versicherungsunterlagen gemäß § 13 beizulegen. Empfang der Portalunterlagen und maßgeblicher Planstand werden gemeinsam dokumentiert.')
p(169,'(4) Die Angebote ANG 839 und ANG 855 sind gemäß der E-Mail von Dagmar Zottl vom 23.09.2026 bis 31.12.2026 gültig; ANG 891 ist laut Angebot ebenfalls bis 31.12.2026 gültig. Das Vertragsdatum 01.10.2026 liegt innerhalb dieser Fristen.')
for i in range(170,176):remove(ps[i])
remove(ts[3])
p(176,'§ 16  Vertragsdauer, Beendigung und Schlussbestimmungen')
p(177,'(1) Der Vertrag endet mit vollständiger Erbringung sämtlicher vereinbarter Leistungen einschließlich Übergabe und Registrierung des Bauwerksbuchs sowie der Unterlagen zur Fertigstellungsanzeige. Nachbesserungs-, Haftungs- und Herausgabepflichten bleiben unberührt.')
p(182,'(6) Die nachstehenden Anlagen gehören zu diesem Vertrag in der Rangordnung gemäß § 1. Historische Unterlagen gelten nur für die hier beauftragten Leistungen:')
p(188,'Anlage 1 – Vereinbarter Leistungsumfang und Abgrenzung')
p(189,'Diese Anlage beschreibt den angebotenen Vertragsumfang der Fassung v3. Sie ist keine unveränderte Abschrift früherer Antworten; verbindlich wird sie mit beiderseitiger Unterzeichnung.')
p(193,'Maßgeblich für die Vollständigkeitsprüfung nach § 10. Die eingeschlossene Bemessung ist von der gesondert zu beauftragenden zeichnerischen Detailplanung zu unterscheiden.')
p(206,'D. Bauwerksbuch – Pauschale EUR 3.400,00 netto, vollständig abrechenbar nach Übergabe, Registrierung und Freigabe gemäß § 7 und § 10. Gesamt aller Grundleistungen: EUR 37.900,00 netto / EUR 45.480,00 brutto. Zahlungsziel jeweils 30 Tage nach Freigabe und prüffähiger Rechnung; keine Vorauszahlung.')
p(210,'Die Termine gelten bei beiderseitiger Unterzeichnung am 01.10.2026. Die vollständige statische Berechnung ist bis 22.10.2026 geschuldet; die Abrechnung der Dossiers erfolgt erst bei vollständiger Lieferung der jeweils dazugehörigen Pläne. Bei späterer Unterzeichnung gilt § 8 Abs. 1.')
p(211,'Anlage 5 / 5a / 5b – Dokumentation der Fragebeantwortung')
p(212,'Die Fragebeantwortungen dokumentieren die vorangegangene Abstimmung. Sie gelten ergänzend ausschließlich für die Leistungen dieses Vertrages und nach dessen Rangordnung; ausdrücklich abweichende Vereinbarungen der vorliegenden Fassung gehen vor.')
p(213,'Anlage 5: „2026-09-23 Anlage 5 - Fragenkatalog (digitale Reinschrift) korrigiert + signiert von TOMS.pdf“, 25 Seiten, unterzeichnet am 23.09.2026.')
p(214,'Anlage 5a: „2026-09-21 Anlage 5a - Fragenkatalog 18.09.2026 ausgefuellt (Original-Scan).pdf“, historische handschriftliche Fassung, 25 Seiten.')
p(215,'Anlage 5b: „2026-09-28 Fragekatalog 2 - unterzeichnet von TOMS.pdf“, 5 Seiten, unterzeichnet von DI Ferdinand Toms am 28.09.2026.')
p(216,'Die Dateien werden als gesonderte Beilagen mitgeführt. Die Unterzeichnung dieses Vertrages stellt keine nachträgliche Änderung der historischen Originale dar.')
p(217,'Die Vertragsparteien bestätigen mit Unterzeichnung die in dieser Fassung ausdrücklich vereinbarten Leistungen, Preise und Termine.')
p(218,'Anlage 6 – Ergänzungen und Zusatzangebote')
p(219,'A. Vor Unterzeichnung zu ergänzen bzw. zu bestätigen')
p(221,'B. Gesondert anzubietende Zusatzleistungen')
p(225,'Vorhandene Unterlagen sind nachstehend dokumentiert. Offene Angaben werden vor Unterzeichnung gemeinsam ergänzt; übermittelte Nachweise und der bestätigte Planstand werden diesem Vertrag beigefügt.')
p(229,'Vertragsangebot der AG – Fassung v3 mit Vertragsdatum 01.10.2026. Unterzeichnung und Annahme durch TOMS stehen bis zum Eingang der beiderseitig unterzeichneten Fassung aus.')

table(0,[['Vertragsstand','Vertragsdatum 01.10.2026 – Entwurf der Auftraggeberin, Version 3'],['Grundlagen','ANG 855 / ANG 839 / ANG 891; Besprechung 18.09.2026; unterzeichnete Fragebeantwortungen 23.09. und 28.09.2026; E-Mail TOMS 23.09.2026; Projektportal ac-wohnart.at.'],['Zweck','Festlegung von Umfang, Abgrenzung, Terminen, Festpreisen, Zahlung nach Lieferung sowie Versicherungsnachweis.']])
table(2,[['Pos.','Leistung','Grundlage','Netto EUR'],['1','Ausführungsstatik, Schal-/Bewehrungspläne und Führungsplanung Stahl/Holz','ANG 855, 1.2.1','25.000,00'],['2','Statische Betreuung','ANG 855, 1.2.2','1.500,00'],['3','Prüfingenieur','ANG 839','8.000,00'],['4','Bauwerksbuch einschließlich Registrierung','ANG 891','3.400,00'],['','Gesamt netto','','37.900,00'],['','20 % USt','','7.580,00'],['','Gesamt brutto','','45.480,00']])
table(4,[['Anlage','Inhalt'],['1','Leistungsumfang und Abgrenzung'],['2','Detaillierungsgrad je Werkstoff'],['3','Dossier- und Zahlungsplan'],['4','Termin- und Ablaufplan'],['5 / 5a / 5b','Unterzeichnete Reinschrift, Original-Scan und Fragenkatalog 2 – gesonderte Beilagen'],['6','Ergänzungen und Zusatzangebote'],['7','Nachweise, Angebote, Planstand und Empfangsbestätigung']])
table(6,[['Nr.','Bezug','Leistung','Status','Vertragliche Festlegung'],['1','§ 2','Ausführungsstatik für alle genannten Bauteile, Fortschreibung Vorbemessung','inkl.','Planstand gemäß § 1 Abs. 3'],['2','§ 3','Bemessung Knoten/Anschlüsse Stahl und Holz','inkl.','Ohne Zusatzhonorar'],['3','§ 3','Dübel-/Ankerspezifikation, Blechdicken, Schweißnahtart und -dicke','inkl.','Ohne Zusatzhonorar; positionsbezogen in der Statik'],['4','§ 3','Anschluss-, Auflager- und Verankerungskräfte','inkl.','In Berechnung und zugehörigen Plänen'],['5','§ 6','Zusätzliche Detailzeichnungen, allgemeine Verbindungsmittelspezifikation, Bauteillisten im Plan, Aussteifungsanschlüsse','separat','Positionsangebot; nur nach schriftlicher Beauftragung'],['6','§ 6','Besondere Schutz-/Klassenangaben gemäß Fragenkatalog 2 A11; Werkstatt-/Abbundplanung','separat','Bemessungskennwerte der Statik bleiben enthalten; Werkstattplanung regelmäßig durch Firmen'],['7','§ 2','Schal-/Bewehrungspläne mit Bewehrungs- und Biegelisten; Positions-/Lastpläne','inkl.','Anlage 2'],['8','§ 2','Prüfung und Freigabe Werkstattpläne Stahl/Holz sowie Lieferantennachweise','inkl.','Auch bei Planung durch Dritte'],['9','§ 2','Zwei Korrekturzyklen je Plan, Bieterfragen, digitale Planlieferung','inkl.','§ 9 Formate'],['10','§ 4','Statische Betreuung, sechs kritische Fixtermine, Startbesprechung, Bedarfstermine, Protokolle','inkl.','EUR 1.500,00; Zusatztermine nur nach § 4 Abs. 3'],['11','§ 5','Prüfingenieur, 15 Begehungen, Befunde, Prüfung, Fertigstellungsbestätigung','inkl.','EUR 8.000,00'],['12','§ 6','Baugrund-/Bestandsgrundlagen, Sichtkontrolle und bestätigte Anpassungen','inkl.','Zugriff und vollständige historische Pläne zu bestätigen'],['13','§ 6','Fremdleistungen: Brandschutzbemessung, Mengen, Verbau-/Pölzungsplanung, Abbruch-/Bauphasenplan, Bauführung, ÖBA, Beweissicherung','ausgenommen','Vollständige Abgrenzung gemäß § 6'],['14','§ 7','Bauwerksbuch: Gebäudedaten/Bewilligungen, Beschreibung, Erstprüfung/Befund, Mängel und Behebungsfristen, Prüfintervalle, befugte Person, Registrierung, Instandhaltungsplan, Prüfhinweise und digitale Übergabe','inkl.','EUR 3.400,00; § 7 Termine'],['15','§ 7','Gesonderte Foto-/Rissdokumentation und zusätzliches umfassendes Dokumentenverzeichnis mit Ablageorten','ausgenommen','Gesetzlich erforderliche Inhalte bleiben enthalten'],['16','§ 9','PDF, DWG je Revision, DXF, IFC, Planliste und Download','inkl.','Maßbezug eindeutig; Darstellung 1:50'],['17','§ 9','Native Berechnungsdatei, Excel/CSV, BTL/BVX, NC/DSTV, besondere Layerstruktur','ausgenommen','Fragenkatalog 2 Abschnitt C'],['18','§ 13','Generali-Nachweis vom 03.03.2026','akzeptiert','EUR 1,5 Mio.; zweifaches Aggregat; unbegrenzte Nachdeckung nach Bedingungen'],['19','§ 14','Einmalige Planwechselbearbeitung im beschriebenen Rahmen','inkl.','Statische Zuarbeit und Abstimmung; Architektur durch Architektin']])
steel='Führungs-/Positionsplanung und prüffähige statische Bemessung; Knoten-/Anschlussbemessung; Dübel/Anker mit Typ, Größe, Anzahl, Rand-/Achsabständen; Blechdicken und Schweißnahtart/-dicke in der Berechnung; Anschluss-, Auflager- und Ankerkräfte auf den Plänen; Auflagerdetails am Bestandsmauerwerk; Prüfung/Freigabe fremder Werkstattpläne.'
wood='Führungs-/Positionsplanung und prüffähige statische Bemessung einschließlich Knoten/Anschlüssen, Aussteifung, Scheiben und Lastpfad; eingeschlossene Dübel-/Ankerbemessung; Anschluss-, Auflager- und Ankerkräfte auf den Plänen; Auflagerdetails am Bestand; Prüfung/Freigabe fremder Abbund-/Werkstattpläne.'
excluded='Zusätzliche zeichnerische Knoten-/Anschlussdetails; allgemeine Verbindungsmittelspezifikation außerhalb § 3 Abs. 4; Bauteillisten im Plan; Details der Aussteifungsanschlüsse; besondere Schutz-/Klassenangaben nach § 6; Werkstatt-/Abbundpläne und gesonderte Listen. Gegen gesondertes Entgelt nach schriftlicher Beauftragung.'
for row,txt in [(2,steel),(3,wood)]:
    ts[7].cell(row,1).text=txt;ts[7].cell(row,2).text=excluded
ts[7].cell(7,1).text='Prüffähige statische Berechnung; Bemessungsgrundlagen mit Materialkennwerten, Normen, Lasten und Klassen; Positions-/Lastpläne; Planliste; Beschau-Punkte; Empfehlung Beweissicherung. Die statisch notwendigen Materialkennwerte bleiben unabhängig von Zusatzleistungen Teil der Berechnung.'
table(8,[['Dossier','Inhalt / Voraussetzung der Abrechnung','Termin','Anteil','Netto EUR'],['D1 Grundlagen','Objektbegehung, Planstand/Lastannahmen, System, Bemessungsgrundlagen, Beschau-Punkte, Lieferprogramm','09.10.2026','10 %','2.500,00'],['D2 Fundierung / Aufzug','Berechnung und Schal-/Bewehrungspläne samt Listen für Fundamentplatte, Unterfangung, Grube und Schacht; Lasten Verbau','16.10.2026','25 %','6.250,00'],['D3 Bestand','Ertüchtigung Decken/Wände, Durchbrüche, Auswechslungen, Feuermauern, Neu/Alt; Berechnung bis 22.10., zugehörige Pläne bis 23.10.','23.10.2026','25 %','6.250,00'],['D4 Dachgeschoss','Holz/Stahl, Dachstuhl, Gaupen, Attika, Terrassen, Aussteifung und Lastpfad; Berechnung bis 22.10., Führungspläne im Umfang § 3 bis 28.10.','28.10.2026','25 %','6.250,00'],['D5 Gesamtübergabe','Balkone, Stiegen, Restbauteile; Berechnung bis 22.10.; sämtliche geschuldeten Pläne und digitale Gesamtübergabe bis 28.10.','28.10.2026','15 %','3.750,00'],['','Summe Ausführungsstatik','','100 %','25.000,00']])
ts[9].cell(7,1).text='Summe Betreuung; Raten B1–B6 bilden den Leistungsfortschritt ab. Alle sechs Fixtermine und die zusätzliche Startbesprechung bleiben geschuldet.'
table(11,[['Nr.','Meilenstein','Termin','Verantwortlich'],['1','Unterzeichnung und vertraglicher Fristbeginn','01.10.2026','AG / AN'],['2','Bearbeitungsbeginn; Portalzugriff und Planliste bestätigen','01.10., spätestens 06.10.2026','AN / AG'],['3','Objektbegehung / Protokoll','bis 08.10.2026','AN / AG'],['4','D1 Grundlagen','09.10.2026','AN'],['5','D2 Fundierung/Aufzug vollständig','16.10.2026','AN'],['6','Vollständige prüffähige statische Berechnung D1–D5','22.10.2026','AN'],['7','D3 einschließlich Pläne vollständig','23.10.2026','AN'],['8','D4/D5 einschließlich Pläne, digitale Gesamtübergabe','28.10.2026','AN'],['9','Prüfingenieur-Bestellung/Bekanntgabe und statische Startbeilagen','vor Baubeginn','AG / AN / Bauführer'],['10','Statusmeldung per E-Mail','wöchentlich bis vollständige Planlieferung','AN'],['11','Bauwerksbuch-Vorfassung','20 Werktage vor Fertigstellungsanzeige','AN'],['12','Bauwerksbuch endgültig und registriert; Ergänzung Endbefunde gemäß § 7','10 Werktage vor Anzeige; frühere gesetzliche Frist geht vor, Bestand spätestens 31.12.2027','AN / AG']])
table(12,[['Nr.','Unterlage / Bestätigung','Termin'],['1','Annahme des Vertrags einschließlich Termin- und Zahlungsplan; tatsächliches Unterschriftsdatum','zur Unterzeichnung'],['2','Befugnis DI Toms, benanntes Team und Stellvertretung, Referenzen sowie Unabhängigkeitsbestätigung ergänzen','höflich erbeten vor Unterzeichnung'],['3','Generali-Bestätigung und Deckungs-/Polizzenunterlagen beilegen bzw. unveränderten Bestand bestätigen','höflich erbeten vor Unterzeichnung'],['4','Portalempfang und maßgebliche Planliste dokumentieren; fehlende vollständige Archivpläne benennen','spätestens 06.10.2026'],['5','Zwei Termine für Objektbegehung vorschlagen','bei Unterzeichnung'],['6','Empfehlungen weiterer Fachbeteiligter und Firmen mit Kontaktdaten','nach Möglichkeit bei Unterzeichnung']])
table(13,[['Nr.','Gesondertes Angebot erbeten','Abgrenzung'],['1','Zeichnerische Knoten- und Anschlussdetails Stahl/Holz, insbesondere 1:10/1:20','§ 6 Abs. 1 lit. a'],['2','Allgemeine Spezifikation der Verbindungsmittel','Ausgenommen die in § 3 Abs. 4 eingeschlossenen Angaben'],['3','Bauteillisten im Plan mit Position, Werkstoff, Profil/Querschnitt, Länge und Stückzahl','§ 6 Abs. 1 lit. a'],['4','Detailausarbeitung der Anschlüsse von Aussteifungen und Windverbänden','§ 6 Abs. 1 lit. a'],['5','Besondere Korrosions-/Holzschutzvorgaben und ergänzende Klassenangaben','Bemessungskennwerte der statischen Berechnung bleiben enthalten'],['6','Optional Werkstatt-/Abbundplanung und Werkstattlisten, soweit durch AN anbietbar','Sonst ausführende Betriebe; Prüfung durch AN bleibt enthalten']])
table(14,[['Nr.','Unterlage','Kennzeichnung','Aussteller','Datum','Stand / Gültigkeit'],['1','Firmenbuchauszug','FN 214744a','Landesgericht Krems','05.05.2026','vorliegend'],['2','Befugnis Gesellschaft','Bauingenieurwesen','ZT-Kammer W/NÖ/B','05.06.2026','aufrecht laut Nachweis'],['3','Befugnis DI Ferdinand Toms','noch zu ergänzen','ZT-Verzeichnis','','vor Unterzeichnung'],['4','Berufshaftpflicht','381-8983-5485','Generali','03.03.2026','01.01.2026–01.01.2027'],['5','Unabhängigkeit / Personalunion','schriftliche Bestätigung','TOMS','','zu ergänzen'],['6','Referenzen, Projektteam, Stellvertretung','Namen / Kontakte','TOMS','','zu ergänzen'],['7','Prüfingenieur-Angebot','ANG 839','TOMS','20.08.2026','31.12.2026, E-Mail 23.09.'],['8','Tragwerksplanung-Angebot','ANG 855','TOMS','03.09.2026','31.12.2026, E-Mail 23.09.'],['9','Bauwerksbuch-Angebot','ANG 891','TOMS','23.09.2026','31.12.2026'],['10','Planliste und Portalempfang','Datei / Index / Datum / Abruf','AG und AN','01.10.2026','bei Unterzeichnung festhalten'],['11','Bestätigung der Angebotsverlängerung','E-Mail Dagmar Zottl','TOMS','23.09.2026','als Beilage'],['12','Generali-Deckungs-/Polizzenunterlagen','zugehörige Bedingungen','Generali / TOMS','','noch beizulegen']])
remove(ts[15])
for section in d.sections:
    for pp in section.footer.paragraphs:
        for run in pp.runs:
            run.text=run.text.replace('v2.2','v3').replace('22.09.2026','01.10.2026')
d.core_properties.title='Werkvertrag TOMS – Schallergasse 35 – Entwurf v3 – 01.10.2026'
d.core_properties.subject='Vertragsangebot; beiderseitige Unterzeichnung ausständig'
name='2026-10-01 Werkvertrag TOMS - Schallergasse 35 - Entwurf v3'
d.save(OUT/(name+'.docx'))
# Ordered text for EVA document generation, retaining all clauses and table cells.
blocks=[]
for e in d.element.body:
    if e.tag.endswith('}p'):
        pp=Paragraph(e,d);t=pp.text.strip()
        if t:
            if t.startswith(('§ ','Anlage ')) or t=='WERKVERTRAG':t='# '+t
            blocks.append(t)
    elif e.tag.endswith('}tbl'):
        tb=Table(e,d)
        if e is ts[5]._tbl:
            blocks.extend(['Für die Auftraggeberin: A&C Wohnart Immobilien GmbH', 'Cosmin Adrian Covaciu, Geschäftsführer', 'Ort / tatsächliches Unterschriftsdatum: ____________________', 'Unterschrift: __________________________________________', 'Für den Auftragnehmer: Toms Ziviltechniker GmbH', 'Dipl.-Ing. Ferdinand Toms', 'Ort / tatsächliches Unterschriftsdatum: ____________________', 'Unterschrift / Firmenstempel: ____________________________'])
            continue
        if e is ts[0]._tbl or e is ts[1]._tbl:
            blocks.extend(' | '.join(c.text.replace('\n','; ') for c in r.cells) for r in tb.rows)
            continue
        head=[c.text.replace('\n','; ') for c in tb.rows[0].cells]
        for r in tb.rows[1:]:
            blocks.append('- '+'; '.join((head[i]+': ' if head[i] else '')+c.text.replace('\n','; ') for i,c in enumerate(r.cells) if c.text.strip()))
        if len(tb.rows)==1:blocks.append(' | '.join(head))
content='\n\n'.join(blocks)
(WORK/'contract_content.txt').write_text(content,encoding='utf-8')
# Preserve original external annexes, offers and professional documents.
ann=OUT/'Beilagen';ann.mkdir(exist_ok=True)
for pattern in ['2026-09-23 Anlage 5*','2026-09-21 Anlage 5a*','2026-09-28 Fragekatalog*','ANG 839*','ANG 855*','2026-09-23 ANG 891*']:
    for f in BASE.glob(pattern):shutil.copy2(f,ann/f.name)
for f in (BASE/'Nachweise 2026.09.23').glob('*.pdf'):shutil.copy2(f,ann/f.name)
print(json.dumps({'output':str(OUT),'docx':name+'.docx','content_chars':len(content)},ensure_ascii=False))
