import copy
import json
from pathlib import Path

ROOT = Path('outputs/dracula-food')
LANGS = ('ro', 'en', 'de')
DATE = '2026-09-25'

def T(ro, en, de):
    return dict(zip(LANGS, (ro, en, de)))

sources = []
def source(id, title, url, scope, **extra):
    sources.append(dict(id=id, title=title, url=url, accessed_at=DATE, scope=scope, **extra))

for fid in (170187, 170581, 168165, 168164, 171724):
    d = json.loads(Path(f'work/usda-{fid}.json').read_text(encoding='utf-8-sig'))
    source(f'usda-{fid}', f'USDA FoodData Central: {d["description"]}', f'https://fdc.nal.usda.gov/food-details/{fid}/nutrients', 'Generic ingredient composition, not a Dracula Food batch or product analysis.', fdc_id=fid, data_type=d['dataType'], verified_via_api=True, api_endpoint=f'https://api.nal.usda.gov/fdc/v1/food/{fid}')

source('walnut-history', 'California Walnut Board — History', 'https://walnuts.org/about-walnuts/history/', 'Persian/English walnut naming and trade history; no claim about our lot origin.')
source('hazelnut-history', 'Hazelnut Industry Office — About U.S. Hazelnuts', 'https://oregonhazelnuts.org/about/', 'Oregon orchard history; no claim about our lot origin.')
source('fps-sultanina', 'UC Davis Foundation Plant Services — Thompson Seedless (Sultanina)', 'https://fps.ucdavis.edu/FGRfamilies.cfm?varietyid=1516', 'Verified cultivar synonyms, including Sultaniye.')
source('golden-process', 'Sun-Maid — Industrial Ingredients', 'https://www.sunmaid.com/industrial/ingredients/', 'Golden colour and commercial processing examples; no assertion that Dracula Food uses these processes.')
source('green-study', 'Proteomic analyses on the browning of shade-dried Thompson seedless grape', 'https://link.springer.com/article/10.1186/s13765-021-00612-7', 'Primary research on shade drying and green raisin colour; not evidence of this product origin.', doi='10.1186/s13765-021-00612-7')
source('zante-history', 'Sun-Maid — Raisins & Dried Fruits, chapter 5', 'https://www.sunmaid.com/wp-content/uploads/2019/02/US-Edition_Ch5.pdf', 'Zante/Black Corinth distinction from currant berries.')
source('fps-varieties', 'UC Davis Foundation Plant Services — Grape Varieties', 'https://fps.ucdavis.edu/fgrvarieties.cfm', 'Muscat of Alexandria and Monukka recorded as table/raisin cultivars.')
source('fps-flame', 'UC Davis Foundation Plant Services — Flame Seedless', 'https://fps.ucdavis.edu/FGRfamilies.cfm?varietyid=648', 'Red grape cultivar released in 1973 in the USA; not product provenance.')
source('raisin-industry', 'California Raisin Marketing Board — The Raisin Industry', 'https://calraisins.org/about/the-raisin-industry/', 'Dried grapes and raisin processing categories; no historical claim for unverified commercial names.')
source('betel-botany', 'Royal Botanic Gardens, Kew — Piper betle', 'https://powo.science.kew.org/taxon/680605-1', 'Botanical identity of betel; no medicinal or health claims.')
source('anardana', 'Spices Board India — Pomegranate', 'https://www.indianspices.com/spice-catalog/pomegranate.html', 'Anardana is dried pomegranate seed with pulp used as a spice; it is not a raisin variety.')
source('nuts-storage', 'University of California — Nuts: Safe Methods for Consumers', 'https://ucfoodsafety.ucdavis.edu/sites/g/files/dgvnsk7366/files/inline-files/44384.pdf', 'Generic cool, sealed storage guidance; not a commercial shelf-life validation.')
source('recipe-pear', 'West Virginia University Extension — Walnut and Honey Baked Pears', 'https://extension.wvu.edu/food-health/recipes/2021/07/13/walnut-and-honey-baked-pears', 'Inspiration limited to the pear/walnut pairing; our quantities, plating and method are original.')
source('recipe-chocolate', 'Andrew Gravett / Great British Chefs — Chocolate and hazelnut tart', 'https://www.greatbritishchefs.com/recipes/chocolate-hazelnut-tart-andrew-gravett-recipe', 'Inspiration limited to dark chocolate with hazelnuts; original dessert cups, not a reproduction of the tart.')
source('recipe-couscous', 'Ottolenghi — Giant couscous with golden raisins, lemon and almonds', 'https://ottolenghi.co.uk/pages/recipes/giant-couscous-golden-raisins-lemon-almonds', 'Inspiration limited to fruit/grain/herb contrast; our recipes use independent ingredients and quantities.')
source('recipe-carrots', 'Ottolenghi — Roasted carrots with curry leaf dukkah', 'https://ottolenghi.co.uk/pages/recipes/roasted-carrots-curry-leaf-dukkah', 'Inspiration limited to roasted vegetables over yoghurt; original raisin versions.')
source('recipe-scones', 'King Arthur Baking — Cream Tea Scones', 'https://www.kingarthurbaking.com/recipes/cream-tea-scones-recipe', 'Inspiration: small teatime pastries. Our butter-based currant rounds are an independent formulation.')
source('recipe-rice', 'Jamie Oliver — Icelandic rice pudding', 'https://www.jamieoliver.com/recipes/rice/icelandic-rice-pudding/', 'Inspiration limited to creamy rice and fruit contrast; original cardamom versions.')
source('recipe-rum', 'Susan Reid / King Arthur Baking — Rum-Raisin Bread', 'https://www.kingarthurbaking.com/recipes/rum-raisin-bread-recipe', 'Inspiration limited to rum and raisins with bread; our baked custard cups use an independent method.')
source('recipe-oats', 'Jamie Oliver — Mothership overnight oats', 'https://www.jamieoliver.com/recipes/fruit/mothership-overnight-oats/', 'Inspiration limited to overnight soaking; independent citrus parfait formulation.')
source('recipe-aubergine', 'Ottolenghi — Bruschetta with aubergine', 'https://ottolenghi.co.uk/pages/recipes/bruschetta-aubergine', 'Inspiration limited to aubergine/pomegranate pairing; original plated recipe.')
source('recipe-berry', 'Ottolenghi — Berry platter with sheep’s labneh and orange oil', 'https://ottolenghi.co.uk/pages/recipes/berry-platter-sheeps-labneh-orange-oil', 'Inspiration limited to fruit against a creamy dairy base; our ricotta cups use their own formulation.')
source('recipe-rose', 'Nigella Lawson — Pear, Pistachio and Rose Cake', 'https://www.nigella.com/recipes/pear-pistachio-and-rose-cake', 'Inspiration limited to the rose/pistachio pairing; our cold dairy cup is not a reproduction of the cake.')
source('recipe-bark', 'Lorraine Elliott / Not Quite Nigella — Easy Easter Chocolate Bark', 'https://www.notquitenigella.com/2018/04/01/easter-chocolate-bark-recipe/', 'Inspiration limited to broken chocolate-sheet presentation; own fruit/nut combination.')

profiles = [
 # id suffix, base reference, sensory / proposed use, history, historical citations, story, recipe template
 ('nuci-dracula-farm',170187,
  T('Miez de nucă în centrul unei prezentări sobre. Propunerea culinară pune în valoare textura crocantă, contrastul cu fructe coapte și folosirea în sosuri sau deserturi.', 'Walnut kernels at the centre of an understated presentation. The culinary concept explores crunch against baked fruit, and their role in sauces and desserts.', 'Walnusskerne im Mittelpunkt einer zurückhaltenden Präsentation. Das kulinarische Konzept verbindet Biss mit gebackenem Obst und eröffnet Möglichkeiten für Saucen und Desserts.'),
  T('Denumirea „English walnut” reflectă istoria comerțului; California Walnut Board descrie legături mai vechi cu Persia. Aceasta nu stabilește originea lotului Dracula Food.', 'The name “English walnut” reflects trade history; the California Walnut Board describes earlier Persian connections. This does not establish the origin of a Dracula Food batch.', 'Die Bezeichnung „English walnut” verweist auf die Handelsgeschichte; das California Walnut Board beschreibt ältere persische Verbindungen. Das belegt nicht die Herkunft einer Dracula-Food-Charge.'),['walnut-history'],
  T('Poveste editorială: o masă de seară, lemn întunecat și o pară caldă. Nuca aduce singurul contrast sonor al farfuriei.', 'Editorial story: an evening table, dark wood and a warm pear. The walnut provides the plate’s one crisp contrast.', 'Redaktionelle Geschichte: ein Abendtisch, dunkles Holz und eine warme Birne. Die Walnuss setzt den knackigen Kontrast.'),'pear'),
 ('alune-de-padure-dracula-farm',170581,
  T('Alunele de pădure invită la contraste între crocant și cremos. Le propunem lângă ciocolată intensă, citrice sau legume coapte, într-o prezentare atent porționată.', 'Hazelnuts invite contrasts between crisp and creamy textures. We pair them with intense chocolate, citrus or roasted vegetables in a carefully portioned presentation.', 'Haselnüsse laden zum Spiel zwischen knackigen und cremigen Texturen ein. Wir kombinieren sie mit dunkler Schokolade, Zitrusfrüchten oder Ofengemüse.'),
  T('Hazelnut Industry Office consemnează livada comercială înființată de George Dorris în Oregon în 1903. Este context agricol, nu proveniența produsului nostru.', 'The Hazelnut Industry Office records George Dorris’s commercial Oregon orchard in 1903. This is agricultural context, not the provenance of our product.', 'Das Hazelnut Industry Office dokumentiert George Dorris’ kommerzielle Anlage in Oregon von 1903. Das ist Agrargeschichte, keine Herkunftsangabe unseres Produkts.'),['hazelnut-history'],
  T('Poveste editorială: negru lucios, un fir de portocală și fragmente de alună. Luxul stă în diferența dintre două texturi.', 'Editorial story: glossy black, a trace of orange and hazelnut fragments. The luxury lies in the contrast between two textures.', 'Redaktionelle Geschichte: glänzendes Schwarz, ein Hauch Orange und Haselnussstücke. Der Reiz liegt im Unterschied zweier Texturen.'),'ganache'),
 ('stafide-thompson-seedless',168165,
  T('O propunere de stafide închise la culoare pentru patiserie, sosuri și garnituri. Dulceața fructului poate echilibra o notă citrică sau sărată; profilul lotului se confirmă la selecție.', 'A dark raisin concept for pastry, sauces and side dishes. Fruit sweetness can balance citrus or savoury notes; the selected batch profile remains to be confirmed.', 'Ein Konzept dunkler Rosinen für Gebäck, Saucen und Beilagen. Fruchtsüße kann Zitrus- oder Salznoten ausgleichen; das Chargenprofil wird bei der Auswahl bestätigt.'),
  T('UC Davis înregistrează Thompson Seedless și Sultanina între denumirile aceluiași soi. Numele nu indică automat țara de cultivare.', 'UC Davis records Thompson Seedless and Sultanina as names of the same cultivar. The name does not establish the growing country.', 'UC Davis führt Thompson Seedless und Sultanina als Namen derselben Sorte. Der Name belegt nicht das Anbauland.'),['fps-sultanina'],
  T('Poveste editorială: o bijuterie întunecată între petale aurii de conopidă. O farfurie discretă care se descoperă pe rând.', 'Editorial story: a dark jewel among golden cauliflower petals. An understated plate revealed one element at a time.', 'Redaktionelle Geschichte: ein dunkles Juwel zwischen goldenen Blumenkohlblättern. Ein ruhiger Teller, der sich Schritt für Schritt erschließt.'),'vegetable'),
 ('stafide-sultaniye',168165,
  T('Selecție propusă Sultaniye pentru aluaturi fine și preparate cu cereale. Textura și culoarea finală depind de materia primă și uscare, care vor fi documentate pentru lot.', 'A proposed Sultaniye selection for fine baking and grain dishes. Final texture and colour depend on the fruit and drying process, to be documented for each batch.', 'Eine geplante Sultaniye-Auswahl für feines Gebäck und Getreidegerichte. Textur und Farbe hängen von Rohware und Trocknung ab und werden chargenbezogen dokumentiert.'),
  T('Registrul UC Davis include Sultaniye printre sinonimele Sultanina. Cele două produse din colecție sunt propuneri de selecție, nu două identități botanice demonstrate.', 'The UC Davis register lists Sultaniye among Sultanina synonyms. The two collection entries are proposed selections, not two proven botanical identities.', 'Das UC-Davis-Register nennt Sultaniye als Synonym von Sultanina. Die beiden Kollektionseinträge sind Auswahlkonzepte, keine nachgewiesenen unterschiedlichen botanischen Identitäten.'),['fps-sultanina'],
  T('Poveste editorială: o urmă de chihlimbar pe o masă neagră, cu parfum de coajă de portocală. Un ritual pentru un prânz lent.', 'Editorial story: a trace of amber on a black table, with orange zest in the air. A ritual for a leisurely lunch.', 'Redaktionelle Geschichte: eine Spur Bernstein auf einem schwarzen Tisch, dazu Orangenschalenduft. Ein Ritual für ein langsames Mittagessen.'),'grain'),
 ('stafide-golden',168164,
  T('Golden este accentul luminos al colecției. Propunerea gastronomică urmărește un contrast dulce-acrișor alături de morcovi copți și iaurt, fără a presupune o anumită tehnologie de procesare.', 'Golden is the collection’s bright accent. The culinary proposal explores sweet-sharp contrast with roasted carrots and yoghurt, without assuming a particular processing method.', 'Golden setzt den hellen Akzent der Kollektion. Der kulinarische Vorschlag verbindet süß-säuerliche Rosinen mit Ofenkarotten und Joghurt, ohne ein bestimmtes Verarbeitungsverfahren vorauszusetzen.'),
  T('Sun-Maid descrie stafide Golden obținute prin uscare mecanică și tratament cu dioxid de sulf. Este un exemplu industrial; tratamentul produsului nostru rămâne neconfirmat.', 'Sun-Maid describes Golden raisins made with mechanical drying and sulphur dioxide treatment. This is an industry example; our product’s treatment is unconfirmed.', 'Sun-Maid beschreibt Golden-Rosinen aus mechanischer Trocknung mit Schwefeldioxidbehandlung. Das ist ein Industriebeispiel; die Behandlung unseres Produkts ist unbestätigt.'),['golden-process'],
  T('Poveste editorială: o pată aurie, controlată, într-o compoziție neagră și roșie. Golden luminează farfuria fără să o domine.', 'Editorial story: a restrained golden accent in a black-and-red composition. Golden brightens the plate without overwhelming it.', 'Redaktionelle Geschichte: ein gezielter Goldakzent in einer schwarz-roten Komposition. Golden hellt den Teller auf, ohne ihn zu beherrschen.'),'vegetable'),
 ('stafide-verzi',168165,
  T('Un concept cromatic aparte pentru salate de orez și accente proaspete. Nuanța verde, calibrul și textura trebuie validate pe produsul efectiv înainte de publicarea specificației finale.', 'A distinctive colour concept for rice salads and fresh accents. Green colour, size and texture must be checked against the actual product before its specification is final.', 'Ein eigenständiges Farbkonzept für Reissalate und frische Akzente. Grünton, Größe und Textur müssen am tatsächlichen Produkt bestätigt werden.'),
  T('Un studiu din 2021 examinează brunificarea strugurilor Thompson uscați la umbră pentru stafide verzi. Metoda descrisă nu dovedește procesul sau originea selecției noastre.', 'A 2021 study examines browning in shade-dried Thompson grapes used for green raisins. It does not establish our selection’s process or provenance.', 'Eine Studie von 2021 untersucht Bräunung bei schattengetrockneten Thompson-Trauben für grüne Rosinen. Sie belegt weder Verfahren noch Herkunft unserer Auswahl.'),['green-study'],
  T('Poveste editorială: verde discret, lime și ierburi pe porțelan întunecat. O pauză luminoasă în universul Dracula Food.', 'Editorial story: subtle green, lime and herbs on dark porcelain. A bright pause in the Dracula Food world.', 'Redaktionelle Geschichte: dezentes Grün, Limette und Kräuter auf dunklem Porzellan. Eine helle Pause in der Dracula-Food-Welt.'),'grain'),
 ('stafide-corint',171724,
  T('O propunere de fruct mic pentru distribuție fină în patiserie. Corint se potrivește unui format de degustare: biscuiți fragezi, cremă rece și o notă de lămâie.', 'A small-fruit concept for an even distribution through pastry. Corinth suits a tasting format: tender bakes, cool cream and a touch of lemon.', 'Ein Kleinfruchtkonzept für eine feine Verteilung im Gebäck. Korinthen passen zu kleinen Verkostungsportionen mit mürbem Gebäck, kühler Creme und Zitrone.'),
  T('Zante Currants provin din struguri Black Corinth; nu sunt coacăze negre. Sun-Maid explică această diferență importantă pentru utilizarea în rețete.', 'Zante currants come from Black Corinth grapes; they are not blackcurrant berries. Sun-Maid explains this distinction for recipe use.', 'Zante-Korinthen stammen von Black-Corinth-Trauben; sie sind keine Schwarzen Johannisbeeren. Sun-Maid erläutert diese für Rezepte wichtige Unterscheidung.'),['zante-history'],
  T('Poveste editorială: detalii mici, așezate precis. O tavă de miniaturi pentru ceai, în care fiecare fruct contează.', 'Editorial story: small details placed with precision. A tray of tea-time miniatures where every fruit matters.', 'Redaktionelle Geschichte: kleine, präzise gesetzte Details. Ein Tablett voller Tee-Miniaturen, bei denen jede Frucht zählt.'),'scone'),
 ('stafide-muscat-alexandria',168165,
  T('Muscat de Alexandria este o propunere pentru degustări cu ricotta, citrice și pâine crocantă. Prezența sâmburilor și intensitatea aromatică vor fi precizate după selectarea lotului.', 'Muscat of Alexandria is a proposal for tastings with ricotta, citrus and crisp bread. Seed presence and aromatic intensity will be specified after batch selection.', 'Muscat of Alexandria ist für Verkostungen mit Ricotta, Zitrusfrüchten und knusprigem Brot vorgesehen. Kerne und Aromaintensität werden nach Chargenauswahl angegeben.'),
  T('UC Davis înregistrează Muscat of Alexandria pentru masă, stafide și vin; numele nu declară alcool în produs.', 'UC Davis lists Muscat of Alexandria for table fruit, raisins and wine; the name does not declare alcohol.', 'UC Davis führt Muscat of Alexandria für Tafeltrauben, Rosinen und Wein; der Name erklärt keinen Alkoholgehalt.'),['fps-varieties'],
  T('Poveste editorială: o degustare de salon, cu cremă albă și un accent de fruct auriu. Eleganța vine din spațiul lăsat liber.', 'Editorial story: a salon tasting with white cream and a golden fruit accent. Elegance comes from the space left open.', 'Redaktionelle Geschichte: eine Salonverkostung mit weißer Creme und goldener Fruchtnote. Eleganz entsteht durch bewusst freien Raum.'),'yogurt'),
 ('stafide-flame-seedless',168165,
  T('Un concept inspirat de nuanțele roșii ale soiului Flame, pentru farfurii cu sfeclă și cremă acrișoară. Culoarea strugurelui nu garantează aceeași culoare după uscare.', 'A concept inspired by Flame’s red grape colour, for plates with beetroot and tangy cream. Grape colour does not guarantee the same colour after drying.', 'Ein von Flames roten Trauben inspiriertes Konzept für Teller mit Roter Bete und säuerlicher Creme. Die Traubenfarbe garantiert nicht dieselbe Farbe nach der Trocknung.'),
  T('UC Davis indică Flame Seedless ca soi roșu lansat în SUA în 1973. Această informație descrie soiul, nu țara de proveniență a lotului comercial.', 'UC Davis records Flame Seedless as a red cultivar released in the USA in 1973. This describes the cultivar, not the commercial batch’s country of origin.', 'UC Davis verzeichnet Flame Seedless als rote, 1973 in den USA eingeführte Sorte. Das beschreibt die Sorte, nicht die Herkunft der Handelscharge.'),['fps-flame'],
  T('Poveste editorială: roșu de sfeclă, alb de iaurt și accente întunecate. O compoziție care preia culorile casei.', 'Editorial story: beetroot red, yoghurt white and dark accents. A composition drawn from the house colours.', 'Redaktionelle Geschichte: Rote-Bete-Rot, Joghurtweiß und dunkle Akzente. Eine Komposition in den Farben des Hauses.'),'vegetable'),
 ('stafide-black-monukka',168165,
  T('Black Monukka este propus pentru compoziții cu ciuperci, cereale și accente dulci. Identitatea lotului, calibrul și eventualii sâmburi trebuie documentate de furnizor.', 'Black Monukka is proposed for mushroom, grain and sweet-accent compositions. Batch identity, size and any seeds must be documented by the supplier.', 'Black Monukka ist für Kombinationen mit Pilzen, Getreide und süßen Akzenten vorgesehen. Chargenidentität, Größe und mögliche Kerne muss der Lieferant dokumentieren.'),
  T('UC Davis înregistrează Monukka ca strugure negru pentru masă și stafide. Identitatea lotului nostru rămâne de confirmat.', 'UC Davis records Monukka as a black table and raisin grape. Our batch identity remains unconfirmed.', 'UC Davis führt Monukka als schwarze Tafel- und Rosinentraube. Unsere Chargenidentität bleibt unbestätigt.'),['fps-varieties'],
  T('Poveste editorială: o cină de toamnă, ciuperci rumenite și câteva accente dulci. Un caracter întunecat, fără excese.', 'Editorial story: an autumn supper, browned mushrooms and a few sweet accents. A dark character with restraint.', 'Redaktionelle Geschichte: ein Herbstabendessen, gebräunte Pilze und wenige süße Akzente. Ein dunkler, zurückhaltender Charakter.'),'grain'),
 ('stafide-rose-red',168165,
  T('Rose Red este o denumire de lucru pentru selecția cu accent trandafiriu. Asocierea propusă este cu fructe roșii și cremă; nu presupune aromatizare cu trandafir.', 'Rose Red is a working name for a rosy-accent selection. The proposed pairing is red fruit and cream; it does not imply added rose flavour.', 'Rose Red ist ein Arbeitsname für eine Auswahl mit rosigem Akzent. Vorgesehen ist die Kombination mit roten Früchten und Creme; zugesetztes Rosenaroma ist damit nicht gemeint.'),
  T('În catalog, Rose Red rămâne o denumire comercială nevalidată. Nu îi atribuim un soi, o origine sau o tradiție istorică fără documentele furnizorului.', 'Rose Red remains an unvalidated commercial name in this catalogue. We assign no cultivar, origin or historical tradition without supplier documentation.', 'Rose Red bleibt im Katalog eine unbestätigte Handelsbezeichnung. Ohne Lieferantennachweis werden weder Sorte noch Herkunft oder historische Tradition zugeordnet.'),[],
  T('Poveste editorială: un desert în două tonuri, roșu și fildeș. Numele evocă o atmosferă, nu o rețetă secretă sau o origine.', 'Editorial story: a dessert in red and ivory. The name evokes an atmosphere, not a secret recipe or provenance.', 'Redaktionelle Geschichte: ein Dessert in Rot und Elfenbein. Der Name schafft Atmosphäre, keine geheime Rezeptur oder Herkunft.'),'yogurt'),
 ('stafide-manukka',168165,
  T('O selecție de lucru destinată deserturilor calde și preparatelor cu condimente. Grafia, identitatea soiului și eventuala origine indiană trebuie confirmate înainte de etichetare.', 'A working selection for warm desserts and spiced dishes. Spelling, cultivar identity and any Indian origin require confirmation before labelling.', 'Eine vorläufige Auswahl für warme Desserts und gewürzte Gerichte. Schreibweise, Sortenidentität und eine mögliche indische Herkunft sind vor der Etikettierung zu bestätigen.'),
  T('Manukka este denumirea din lista utilizatorului. Nu o echivalăm automat cu un soi botanic și nu îi inventăm o istorie.', 'Manukka is the name in the user’s list. We do not automatically assign a botanical cultivar or invent its history.', 'Manukka ist die Bezeichnung aus der Nutzerliste. Wir ordnen ihr weder automatisch eine botanische Sorte noch eine erfundene Geschichte zu.'),[],
  T('Poveste editorială: abur fin, cardamom și o cupă neagră. O încheiere calmă pentru o masă lungă.', 'Editorial story: a curl of steam, cardamom and a black cup. A quiet ending to a long meal.', 'Redaktionelle Geschichte: ein Hauch Dampf, Kardamom und eine schwarze Schale. Ein ruhiger Abschluss eines langen Essens.'),'rice'),
 ('stafide-rom',168165,
  T('Concept gastronomic în care stafidele întâlnesc aroma de rom. Tipul de rom sau aromă, proporțiile și alcoolul rezidual rămân de stabilit; rețeta de servire este o propunere separată.', 'A culinary concept pairing raisins with rum character. Rum or flavouring type, proportions and residual alcohol remain to be established; the serving recipe is a separate proposal.', 'Ein kulinarisches Konzept aus Rosinen und Rumcharakter. Rum- oder Aromatyp, Anteile und Restalkohol sind offen; das Servierrezept ist ein gesonderter Vorschlag.'),
  T('Asocierea rom–stafide apare în patiseria contemporană, inclusiv în rețeta lui Susan Reid publicată de King Arthur Baking. Nu revendicăm o origine exclusivă.', 'Rum and raisins feature in contemporary baking, including Susan Reid’s recipe published by King Arthur Baking. We claim no exclusive origin.', 'Rum und Rosinen erscheinen in zeitgenössischem Gebäck, etwa in Susan Reids Rezept bei King Arthur Baking. Eine exklusive Herkunft wird nicht beansprucht.'),['recipe-rum'],
  T('Poveste editorială: brioșă caldă și lumină de chihlimbar. O propunere pentru finalul cinei, cu detalii atent dozate.', 'Editorial story: warm brioche and amber light. A dinner finale with carefully measured details.', 'Redaktionelle Geschichte: warme Brioche und bernsteinfarbenes Licht. Ein Abendessen-Finale mit sorgfältig dosierten Details.'),'brioche'),
 ('stafide-suc-fructe',168165,
  T('Concept de stafide cu suc de fructe, gândit pentru gustări și deserturi de mic dejun. Fructul folosit, concentrația și eventualul adaos de zahăr sunt încă neconfirmate.', 'A fruit-juice raisin concept for snacks and breakfast desserts. Fruit type, concentration and any added sugar remain unconfirmed.', 'Ein Konzept mit Fruchtsaft-Rosinen für Snacks und Frühstücksdesserts. Fruchtart, Konzentration und möglicher Zuckerzusatz sind noch unbestätigt.'),
  T('Aceasta este o propunere contemporană de aromatizare, nu un soi botanic. Istoria furnizorului și metoda exactă de infuzare nu sunt documentate încă.', 'This is a contemporary flavouring concept, not a botanical cultivar. Supplier history and the exact infusion process are not yet documented.', 'Dies ist ein zeitgenössisches Aromakonzept, keine botanische Sorte. Lieferantengeschichte und genaues Infusionsverfahren sind noch nicht dokumentiert.'),[],
  T('Poveste editorială: un pahar înalt, straturi luminoase și o dimineață fără grabă. Fructul devine detaliul care leagă texturile.', 'Editorial story: a tall glass, bright layers and an unhurried morning. Fruit becomes the detail that connects the textures.', 'Redaktionelle Geschichte: ein hohes Glas, helle Schichten und ein Morgen ohne Eile. Die Frucht verbindet die Texturen.'),'oats'),
 ('stafide-paan',168165,
  T('Paan este numele unui concept aromatic încă în definire. Fișa nu presupune prezența frunzei de betel sau a altor ingrediente; propunerea culinară separată folosește cardamom și apă de trandafiri alimentară.', 'Paan names an aromatic concept still being defined. This sheet does not assume betel leaf or other ingredients; the separate culinary proposal uses cardamom and food-grade rosewater.', 'Paan benennt ein noch zu definierendes Aromakonzept. Diese Beschreibung setzt weder Betelblatt noch andere Zutaten voraus; der gesonderte Küchenvorschlag nutzt Kardamom und Rosenwasser in Lebensmittelqualität.'),
  T('Kew înregistrează Piper betle ca specie de plantă distinctă. Numele comercial Paan nu stabilește compoziția produsului și nu justifică afirmații despre efecte digestive.', 'Kew records Piper betle as a distinct plant species. The commercial name Paan neither establishes product composition nor supports digestive-effect claims.', 'Kew führt Piper betle als eigenständige Pflanzenart. Der Handelsname Paan belegt weder die Produktzusammensetzung noch Aussagen zur Verdauungswirkung.'),['betel-botany'],
  T('Poveste editorială: cremă rece, parfum floral discret și verde de fistic. O scenă de desert creată pentru colecție.', 'Editorial story: cool cream, a restrained floral aroma and pistachio green. A dessert scene created for the collection.', 'Redaktionelle Geschichte: kühle Creme, dezenter Blütenduft und Pistaziengrün. Eine für die Kollektion entwickelte Dessertszene.'),'yogurt'),
 ('stafide-anardana',168165,
  T('Concept de stafide cu accent de rodie. Tipul de ingredient — suc, concentrat, pudră sau anardana — și proporția sa trebuie confirmate; denumirea nu este o listă de ingrediente.', 'A raisin concept with a pomegranate accent. Ingredient form—juice, concentrate, powder or anardana—and its proportion require confirmation; the name is not an ingredient list.', 'Ein Rosinenkonzept mit Granatapfelakzent. Zutatenform — Saft, Konzentrat, Pulver oder Anardana — und Anteil müssen bestätigt werden; der Name ist keine Zutatenliste.'),
  T('Spices Board India descrie anardana ca semințe de rodie uscate cu pulpă, folosite drept condiment. Anardana nu este numele unui soi de stafide.', 'Spices Board India describes anardana as pomegranate seeds dried with pulp and used as a spice. Anardana is not a raisin cultivar.', 'Spices Board India beschreibt Anardana als mit Fruchtfleisch getrocknete Granatapfelkerne, die als Gewürz dienen. Anardana ist keine Rosinensorte.'),['anardana'],
  T('Poveste editorială: o pensulă rubinie peste vânătă coaptă. Un accent de culoare și aciditate într-o farfurie amplă.', 'Editorial story: a ruby brushstroke across roasted aubergine. A colour and acidity accent on a generous plate.', 'Redaktionelle Geschichte: ein rubinroter Pinselstrich über gebackener Aubergine. Farbe und Säure setzen den Akzent.'),'aubergine'),
 ('stafide-ciocolata-scortisoara',168165,
  T('Concept de cofetărie cu stafide, ciocolată și scorțișoară. Tipul de ciocolată, procentul de cacao, raportul de acoperire și alergenii finali vor fi declarați după stabilirea rețetei.', 'A confectionery concept with raisins, chocolate and cinnamon. Chocolate type, cocoa percentage, coating ratio and final allergens will be declared once the formulation is fixed.', 'Ein Süßwarenkonzept mit Rosinen, Schokolade und Zimt. Schokoladentyp, Kakaoanteil, Überzugsverhältnis und endgültige Allergene folgen nach Festlegung der Rezeptur.'),
  T('Aceasta este o compoziție de cofetărie propusă pentru colecție. Nu îi atribuim o rețetă istorică sau o proveniență exclusivă fără dovezi.', 'This is a confectionery composition proposed for the collection. We assign no historical recipe or exclusive provenance without evidence.', 'Dies ist eine für die Kollektion vorgeschlagene Süßwarenkomposition. Ohne Nachweis wird ihr weder ein historisches Rezept noch eine exklusive Herkunft zugeschrieben.'),[],
  T('Poveste editorială: un luciu întunecat și o urmă caldă de scorțișoară. Desertul este construit în jurul unei singure linguri perfecte.', 'Editorial story: a dark gloss and a warm trace of cinnamon. The dessert is built around one considered spoonful.', 'Redaktionelle Geschichte: dunkler Glanz und ein warmer Hauch Zimt. Das Dessert ist um einen bewusst gestalteten Löffel herum aufgebaut.'),'ganache'),
 ('stafide-vin',168165,
  T('Concept de stafide macerate în vin pentru asocieri de seară. Soiul vinului, dozajul, alcoolul rezidual și sulfiții sunt necunoscute până la confirmarea formulei.', 'A wine-macerated raisin concept for evening pairings. Wine variety, dosage, residual alcohol and sulphites are unknown until the formulation is confirmed.', 'Ein Konzept weinmazerierter Rosinen für abendliche Kombinationen. Rebsorte, Dosierung, Restalkohol und Sulfite sind bis zur Rezepturbestätigung unbekannt.'),
  T('Macerarea este aici o direcție de dezvoltare culinară. Nu există încă documente care să susțină o regiune viticolă, un an de recoltă sau o tradiție proprie produsului.', 'Maceration is a culinary development direction here. No documentation yet establishes a wine region, vintage or tradition specific to this product.', 'Mazeration ist hier eine kulinarische Entwicklungsrichtung. Eine Weinregion, ein Jahrgang oder eine produktspezifische Tradition sind noch nicht dokumentiert.'),[],
  T('Poveste editorială: o pară în nuanțe rubinii, o cremă sărată și liniștea de după cină. Un contrast pentru degustare.', 'Editorial story: a ruby-tinted pear, a savoury cream and the quiet after dinner. A contrast made for tasting.', 'Redaktionelle Geschichte: eine rubinfarbene Birne, eine salzige Creme und die Ruhe nach dem Abendessen. Ein Kontrast zum Verkosten.'),'pear'),
 ('stafide-glazurate',168165,
  T('Concept de stafide glazurate pentru mici accente de cofetărie. Tipul de glazură, zaharurile adăugate și eventualii agenți de acoperire nu sunt încă stabiliți.', 'A glazed raisin concept for small confectionery accents. Glaze type, added sugars and any coating agents have not yet been determined.', 'Ein Konzept glasierter Rosinen für kleine Patisserieakzente. Glasurtyp, zugesetzter Zucker und mögliche Überzugsmittel sind noch nicht festgelegt.'),
  T('Glazurarea descrie o finisare culinară, nu un soi de strugure. Pentru acest concept nu este confirmată o rețetă tradițională sau o compoziție comercială.', 'Glazing describes a culinary finish, not a grape cultivar. Neither a traditional recipe nor a commercial composition is confirmed for this concept.', 'Glasieren beschreibt eine kulinarische Veredelung, keine Rebsorte. Für dieses Konzept sind weder ein traditionelles Rezept noch eine Handelsrezeptur bestätigt.'),[],
  T('Poveste editorială: fragmente lucioase pe o placă de ciocolată, precum mici pietre într-o casetă. O piesă de împărțit la masă.', 'Editorial story: glossy fragments on a chocolate slab, like small stones in a case. A piece to share at the table.', 'Redaktionelle Geschichte: glänzende Stücke auf einer Schokoladenplatte wie kleine Steine in einer Schatulle. Ein Stück zum Teilen.'),'bark'),
]

notes = {
 'nutrition': T('Referință orientativă USDA pentru 100 g de ingredient generic comestibil, nu analiză a produsului Dracula Food. Soiul, umiditatea și procesarea pot schimba valorile. Glucidele USDA „by difference” includ fibrele și nu sunt direct o declarație UE de etichetare.', 'Indicative USDA reference per 100 g of a generic edible ingredient, not an analysis of the Dracula Food product. Cultivar, moisture and processing can change values. USDA carbohydrate “by difference” includes fibre and is not directly an EU labelling declaration.', 'Orientierungswerte der USDA je 100 g einer allgemeinen essbaren Zutat, keine Analyse des Dracula-Food-Produkts. Sorte, Feuchte und Verarbeitung können Werte verändern. USDA-Kohlenhydrate „by difference” enthalten Ballaststoffe und sind keine direkte EU-Nährwertdeklaration.'),
 'compound': T('Produsul final nu are încă valori nutriționale calculate. Tabelul de referință descrie numai stafidele simple; nu include suc, alcool, glazură, ciocolată sau alte adaosuri.', 'Nutrition for the final product has not been calculated. The reference table describes plain raisins only; it excludes juice, alcohol, glaze, chocolate and other additions.', 'Für das Endprodukt sind noch keine Nährwerte berechnet. Die Referenztabelle beschreibt ausschließlich einfache Rosinen; Saft, Alkohol, Glasur, Schokolade und weitere Zusätze sind nicht enthalten.'),
 'ingredients': T('Compoziția completă, procentele, aditivii și tratamentele vor fi preluate din fișa furnizorului. Denumirea și fotografia conceptului nu înlocuiesc lista de ingrediente.', 'Full composition, percentages, additives and treatments will come from the supplier specification. The concept name and image do not replace an ingredient list.', 'Vollständige Zusammensetzung, Anteile, Zusatzstoffe und Behandlungen werden aus der Lieferantenspezifikation übernommen. Konzeptname und Bild ersetzen keine Zutatenliste.'),
 'allergens': T('Declarație în așteptarea fișei furnizorului, inclusiv sulfiți și contaminare încrucișată. Nu este confirmată absența alergenilor. Alergenii rețetei de servire sunt separați de cei ai produsului.', 'Declaration pending supplier specification, including sulphites and cross-contact. Absence of allergens is not confirmed. Serving-recipe allergens are separate from product allergens.', 'Angabe ausstehend bis zur Lieferantenspezifikation, einschließlich Sulfiten und Kreuzkontakt. Allergenfreiheit ist nicht bestätigt. Allergene des Servierrezepts sind von Produktallergenen getrennt.'),
 'storage': T('Păstrați ambalajul bine închis, într-un loc răcoros și uscat, ferit de lumină și mirosuri puternice. După deschidere urmați eticheta lotului. Temperatura exactă, termenul și cerințele speciale sunt de confirmat.', 'Keep the pack tightly closed in a cool, dry place away from light and strong odours. After opening, follow the batch label. Exact temperature, shelf life and special requirements remain to be confirmed.', 'Packung gut verschlossen, kühl, trocken, lichtgeschützt und fern von starken Gerüchen aufbewahren. Nach Öffnung dem Chargenetikett folgen. Genaue Temperatur, Haltbarkeit und Sonderbedingungen sind noch zu bestätigen.'),
 'recipe_status': T('Rețetă editorială proprie, netestată în bucătărie; sursa citată inspiră doar asocierea culinară. Cantitățile aparțin rețetei de servire, nu compoziției produsului comercial.', 'Original editorial recipe, not kitchen-tested; the cited source inspires only the culinary pairing. Quantities belong to the serving recipe, not the commercial product formulation.', 'Eigenes redaktionelles Rezept, nicht in der Küche getestet; die Quelle inspiriert nur die kulinarische Kombination. Mengen gelten für das Servierrezept, nicht die Handelsrezeptur.'),
 'plain_substitute': T('Până la confirmarea formulei comerciale, gătiți cu stafide simple și ingredientele alimentare explicit enumerate mai jos.', 'Until the commercial formula is confirmed, cook with plain raisins and the food ingredients explicitly listed below.', 'Bis die Handelsrezeptur bestätigt ist, einfache Rosinen und die unten ausdrücklich genannten Lebensmittel verwenden.'),
}

# Independent recipe formulations. Shared techniques are expanded into full,
# localized recipe fields; no frontend dependency on Python or this generator.
recipes = {}
def R(key, title, servings, ingredients, steps, pairing, inspiration, allergens):
    recipes[key] = dict(title=title, servings=servings, ingredients=ingredients, steps=steps, pairing=pairing, inspiration_source_ids=inspiration, allergens=allergens)

R('pear',T('Pară coaptă, cremă de capră și nuci', 'Roasted pear, goat-cheese cream and walnuts', 'Ofenbirne mit Ziegenkäsecreme und Walnüssen'),4,
 T(['2 pere ferme','60 g miez de nucă','100 g brânză proaspătă de capră','80 g iaurt grecesc','15 g miere','10 ml ulei de măsline','10 ml oțet balsamic','4 frunze de cimbru'],['2 firm pears','60 g walnut kernels','100 g soft goat cheese','80 g Greek yoghurt','15 g honey','10 ml olive oil','10 ml balsamic vinegar','4 thyme leaves'],['2 feste Birnen','60 g Walnusskerne','100 g Ziegenfrischkäse','80 g griechischer Joghurt','15 g Honig','10 ml Olivenöl','10 ml Balsamico','4 Thymianblätter']),
 T(['Înjumătățiți perele și scoateți cotorul. Ungeți cu ulei și coaceți la 190°C timp de 20–25 de minute, până cedează ușor la vârful cuțitului.','Prăjiți nucile într-o tigaie uscată 3–4 minute la foc mediu, amestecând; răciți și tocați grosier.','Amestecați brânza cu iaurtul până obțineți o cremă. Combinați separat mierea și balsamicul.','Așezați crema în patru farfurii, adăugați câte o jumătate de pară, nuci, câteva picături de sos și cimbru. Serviți imediat.'],['Halve and core the pears. Brush with oil and roast at 190°C for 20–25 minutes, until a knife tip enters easily.','Toast walnuts in a dry pan over medium heat for 3–4 minutes, stirring; cool and chop roughly.','Mix goat cheese with yoghurt until creamy. Separately combine honey and balsamic vinegar.','Spread the cream over four plates. Add a pear half, walnuts, a few sauce drops and thyme; serve immediately.'],['Birnen halbieren und entkernen. Mit Öl bestreichen und bei 190°C 20–25 Minuten backen, bis eine Messerspitze leicht eindringt.','Walnüsse in einer trockenen Pfanne bei mittlerer Hitze 3–4 Minuten unter Rühren rösten, abkühlen lassen und grob hacken.','Ziegenkäse mit Joghurt cremig rühren. Honig und Balsamico separat mischen.','Creme auf vier Teller streichen. Je eine Birnenhälfte, Nüsse, etwas Sauce und Thymian daraufgeben und sofort servieren.']),
 T('Cu pâine crocantă și apă minerală cu lămâie.','Serve with crisp bread and lemon sparkling water.','Mit knusprigem Brot und Zitronen-Mineralwasser servieren.'),['recipe-pear'],T('Nuci, lapte; verificați etichetele celorlalte ingrediente.','Walnuts, milk; check other ingredient labels.','Walnüsse, Milch; weitere Zutatenetiketten prüfen.'))

R('ganache',T('Cupă de ciocolată, alune și portocală','Chocolate cup with hazelnuts and orange','Schokoladenbecher mit Haselnüssen und Orange'),4,
 T(['140 g ciocolată neagră','180 ml smântână pentru frișcă','50 g alune de pădure','1 portocală, coajă rasă și felii','1 praf de sare'],['140 g dark chocolate','180 ml whipping cream','50 g hazelnuts','1 orange, zest and segments','1 pinch salt'],['140 g dunkle Schokolade','180 ml Schlagsahne','50 g Haselnüsse','1 Orange, Abrieb und Filets','1 Prise Salz']),
 T(['Prăjiți alunele la 160°C timp de 10–12 minute; răciți, frecați ușor pielițele desprinse și tocați.','Tocați ciocolata. Încălziți smântâna până începe să aburească, turnați peste ciocolată și așteptați 2 minute.','Amestecați din centru până crema devine netedă, adăugați sarea și puțină coajă de portocală. Împărțiți în patru cupe și răciți 2 ore la frigider.','Adăugați alunele și câte două felii de portocală chiar înainte de servire, pentru contrast de textură.'],['Toast hazelnuts at 160°C for 10–12 minutes; cool, rub away loose skins and chop.','Chop the chocolate. Heat cream until steaming, pour over the chocolate and wait 2 minutes.','Stir from the centre until smooth, then add salt and a little orange zest. Divide between four cups and refrigerate for 2 hours.','Add the nuts and two orange segments per cup just before serving for contrasting textures.'],['Haselnüsse bei 160°C 10–12 Minuten rösten; abkühlen, lose Häutchen abreiben und hacken.','Schokolade hacken. Sahne bis zum Dampfen erhitzen, darübergeben und 2 Minuten warten.','Von der Mitte aus glatt rühren, Salz und etwas Orangenabrieb zugeben. Auf vier Becher verteilen und 2 Stunden kühlen.','Nüsse und je zwei Orangenfilets erst kurz vor dem Servieren zugeben, damit die Texturen kontrastieren.']),
 T('Cu espresso sau infuzie de coajă de portocală.','Pair with espresso or orange-peel infusion.','Dazu Espresso oder Orangenschalenaufguss.'),['recipe-chocolate'],T('Alune de pădure, lapte; ciocolata poate conține soia conform etichetei.','Hazelnuts, milk; chocolate may contain soy according to its label.','Haselnüsse, Milch; Schokolade kann laut Etikett Soja enthalten.'))

R('grain',T('Cuscus cu stafide Sultaniye și portocală','Couscous with Sultaniye raisins and orange','Couscous mit Sultaniye-Rosinen und Orange'),4,
 T(['200 g cuscus instant','250 ml apă fierbinte sau cât indică ambalajul','60 g stafide Sultaniye','1 portocală','40 g migdale feliate','20 g pătrunjel','25 ml ulei de măsline','15 ml suc de lămâie','2 g sare'],['200 g instant couscous','250 ml hot water, or as directed on pack','60 g Sultaniye raisins','1 orange','40 g flaked almonds','20 g parsley','25 ml olive oil','15 ml lemon juice','2 g salt'],['200 g Instant-Couscous','250 ml heißes Wasser oder Menge laut Packung','60 g Sultaniye-Rosinen','1 Orange','40 g Mandelblättchen','20 g Petersilie','25 ml Olivenöl','15 ml Zitronensaft','2 g Salz']),
 T(['Acoperiți cuscusul cu apa fierbinte și sarea. Lăsați 5–8 minute sau timpul de pe ambalaj, apoi afânați cu furculița.','Înmuiați stafidele în apă caldă 10 minute și scurgeți bine. Rumeniți migdalele 2–3 minute într-o tigaie uscată.','Tăiați portocala în bucăți fără membrane. Amestecați cuscusul cu stafidele, portocala, pătrunjelul, uleiul și lămâia.','Montați în inele joase pe patru farfurii și presărați migdalele; ridicați inelele și serviți călduț.'],['Cover couscous with hot water and salt. Leave for 5–8 minutes or the pack time, then fluff with a fork.','Soak raisins in warm water for 10 minutes and drain well. Toast almonds in a dry pan for 2–3 minutes.','Segment and chop the orange. Fold couscous with raisins, orange, parsley, oil and lemon juice.','Shape in low rings on four plates and scatter over almonds; lift the rings and serve warm.'],['Couscous mit heißem Wasser und Salz übergießen. 5–8 Minuten beziehungsweise nach Packungsangabe quellen lassen und mit einer Gabel lockern.','Rosinen 10 Minuten in warmem Wasser einweichen und gut abtropfen. Mandeln 2–3 Minuten trocken rösten.','Orange filetieren und zerkleinern. Couscous mit Rosinen, Orange, Petersilie, Öl und Zitronensaft vermengen.','Mit niedrigen Ringen auf vier Tellern anrichten, Mandeln darübergeben, Ringe abheben und lauwarm servieren.']),
 T('Cu legume la grătar; păstrați garnitura ușor acidulată.','Serve with grilled vegetables and keep the garnish lightly tangy.','Mit Grillgemüse servieren; die Beilage leicht säuerlich halten.'),['recipe-couscous'],T('Grâu/gluten și migdale.','Wheat/gluten and almonds.','Weizen/Gluten und Mandeln.'))

R('vegetable',T('Conopidă rumenită, stafide și cremă de iaurt','Roasted cauliflower, raisins and yoghurt cream','Gerösteter Blumenkohl mit Rosinen und Joghurtcreme'),4,
 T(['700 g conopidă în buchețele','60 g stafide Thompson Seedless','220 g iaurt grecesc','25 ml ulei de măsline','20 ml suc de lămâie','10 g pătrunjel','1 g chimion măcinat','2 g sare'],['700 g cauliflower florets','60 g Thompson Seedless raisins','220 g Greek yoghurt','25 ml olive oil','20 ml lemon juice','10 g parsley','1 g ground cumin','2 g salt'],['700 g Blumenkohlröschen','60 g Thompson-Seedless-Rosinen','220 g griechischer Joghurt','25 ml Olivenöl','20 ml Zitronensaft','10 g Petersilie','1 g gemahlener Kreuzkümmel','2 g Salz']),
 T(['Amestecați conopida cu uleiul, chimionul și jumătate din sare. Coaceți la 210°C timp de 25–30 de minute, întorcând o dată.','Înmuiați stafidele 10 minute în apă caldă, apoi scurgeți. Păstrați-le întregi pentru accente vizibile.','Amestecați iaurtul cu sucul de lămâie și sarea rămasă; întindeți câte o lingură largă pe fiecare farfurie.','Așezați conopida rumenită peste cremă, presărați stafidele și pătrunjelul. Serviți când leguma este caldă, nu fierbinte.'],['Toss cauliflower with oil, cumin and half the salt. Roast at 210°C for 25–30 minutes, turning once.','Soak raisins in warm water for 10 minutes, then drain. Keep them whole for visible accents.','Mix yoghurt with lemon juice and remaining salt; spread a broad spoonful on each plate.','Place browned cauliflower over the cream and scatter raisins and parsley. Serve with the vegetables warm rather than piping hot.'],['Blumenkohl mit Öl, Kreuzkümmel und der Hälfte des Salzes mischen. Bei 210°C 25–30 Minuten rösten und einmal wenden.','Rosinen 10 Minuten in warmem Wasser einweichen und abtropfen. Als sichtbare Akzente ganz lassen.','Joghurt mit Zitronensaft und restlichem Salz verrühren; auf jeden Teller einen breiten Löffel streichen.','Gebräunten Blumenkohl daraufsetzen und Rosinen sowie Petersilie verteilen. Gemüse warm, nicht kochend heiß servieren.']),
 T('Cu lipie caldă și o salată simplă de frunze.','Pair with warm flatbread and a simple leaf salad.','Dazu warmes Fladenbrot und einen einfachen Blattsalat.'),['recipe-carrots'],T('Lapte; lipia opțională adaugă grâu/gluten.','Milk; optional flatbread adds wheat/gluten.','Milch; optionales Fladenbrot ergänzt Weizen/Gluten.'))

R('scone',T('Mini-scones cu Corint și lămâie','Mini scones with currants and lemon','Mini-Scones mit Korinthen und Zitrone'),8,
 T(['200 g făină de grâu','7 g praf de copt','35 g zahăr','55 g unt rece','100 ml lapte','50 g stafide de Corint','1 linguriță coajă de lămâie','1 g sare','80 g iaurt pentru servire'],['200 g wheat flour','7 g baking powder','35 g sugar','55 g cold butter','100 ml milk','50 g Zante currants','1 tsp lemon zest','1 g salt','80 g yoghurt to serve'],['200 g Weizenmehl','7 g Backpulver','35 g Zucker','55 g kalte Butter','100 ml Milch','50 g Korinthen','1 TL Zitronenabrieb','1 g Salz','80 g Joghurt zum Servieren']),
 T(['Încălziți cuptorul la 200°C. Amestecați făina, praful de copt, sarea și zahărul, apoi frecați untul rece până apar firimituri.','Încorporați Corintul și coaja de lămâie. Adăugați laptele treptat și uniți aluatul fără frământare lungă.','Presați într-un disc de 2 cm grosime și tăiați opt bucăți. Așezați-le pe hârtie de copt, cu puțin spațiu între ele.','Coaceți 15–18 minute, până devin aurii. Răciți 10 minute și serviți cu iaurtul separat.'],['Heat the oven to 200°C. Mix flour, baking powder, salt and sugar; rub in cold butter until crumbly.','Fold in currants and lemon zest. Add milk gradually and bring the dough together without prolonged kneading.','Press into a 2 cm thick disc and cut eight pieces. Place on baking paper with small gaps.','Bake for 15–18 minutes until golden. Cool for 10 minutes and serve with yoghurt on the side.'],['Ofen auf 200°C vorheizen. Mehl, Backpulver, Salz und Zucker mischen; kalte Butter krümelig einarbeiten.','Korinthen und Zitronenabrieb einmischen. Milch schrittweise zugeben und den Teig ohne langes Kneten zusammenführen.','Zu einer 2 cm dicken Scheibe drücken und in acht Stücke schneiden. Mit Abstand auf Backpapier legen.','15–18 Minuten goldgelb backen. 10 Minuten abkühlen lassen und Joghurt separat reichen.']),
 T('Cu ceai negru și felii subțiri de lămâie.','Serve with black tea and thin lemon slices.','Dazu Schwarztee und dünne Zitronenscheiben.'),['recipe-scones'],T('Grâu/gluten, lapte.','Wheat/gluten, milk.','Weizen/Gluten, Milch.'))

R('yogurt',T('Ricotta aerată cu Muscat și portocală','Whipped ricotta with Muscat raisins and orange','Luftige Ricotta mit Muscat-Rosinen und Orange'),4,
 T(['250 g ricotta','100 g iaurt grecesc','60 g stafide Muscat, fără sâmburi','1 portocală','15 g miere','20 g fistic nesărat','4 frunze de mentă'],['250 g ricotta','100 g Greek yoghurt','60 g Muscat raisins, seeds removed','1 orange','15 g honey','20 g unsalted pistachios','4 mint leaves'],['250 g Ricotta','100 g griechischer Joghurt','60 g Muscat-Rosinen, entkernt','1 Orange','15 g Honig','20 g ungesalzene Pistazien','4 Minzblätter']),
 T(['Verificați stafidele și îndepărtați eventualii sâmburi. Înmuiați-le 10 minute în apă caldă, apoi scurgeți și răciți.','Bateți ricotta cu iaurtul și mierea timp de un minut. Păstrați la rece până montați farfuriile.','Curățați portocala și tăiați felii fără membrane. Tocați fisticul grosier.','Împărțiți crema în patru boluri joase. Adăugați portocala și stafidele, apoi fistic și mentă. Serviți rece.'],['Check raisins and remove any seeds. Soak in warm water for 10 minutes, then drain and cool.','Whisk ricotta with yoghurt and honey for one minute. Refrigerate until plating.','Peel and segment the orange, removing membranes. Roughly chop pistachios.','Divide cream between four shallow bowls. Add orange and raisins, then pistachios and mint; serve chilled.'],['Rosinen prüfen und mögliche Kerne entfernen. 10 Minuten in warmem Wasser einweichen, abtropfen und abkühlen.','Ricotta mit Joghurt und Honig eine Minute aufschlagen. Bis zum Anrichten kühlen.','Orange schälen und ohne Trennhäute filetieren. Pistazien grob hacken.','Creme auf vier flache Schalen verteilen. Orange, Rosinen, Pistazien und Minze dazugeben und gekühlt servieren.']),
 T('Cu ceai alb sau apă minerală simplă.','Pair with white tea or plain sparkling water.','Dazu weißen Tee oder Mineralwasser.'),['recipe-berry'],T('Lapte, fistic.','Milk, pistachios.','Milch, Pistazien.'))

R('rice',T('Orez cremos cu Manukka și cardamom','Creamy rice with Manukka raisins and cardamom','Cremiger Reis mit Manukka-Rosinen und Kardamom'),4,
 T(['100 g orez cu bob rotund','600 ml lapte','60 g stafide simple, fără sâmburi','25 g zahăr','2 păstăi de cardamom ușor zdrobite','30 ml apă','20 g fistic tocat'],['100 g short-grain rice','600 ml milk','60 g plain raisins, seeds removed','25 g sugar','2 lightly crushed cardamom pods','30 ml water','20 g chopped pistachios'],['100 g Rundkornreis','600 ml Milch','60 g einfache Rosinen, entkernt','25 g Zucker','2 leicht angedrückte Kardamomkapseln','30 ml Wasser','20 g gehackte Pistazien']),
 T(['Puneți orezul, laptele și cardamomul într-o cratiță grea. Fierbeți foarte încet 25–35 de minute, amestecând frecvent, până bobul este fraged.','Într-un vas mic încălziți stafidele cu 30 ml apă timp de 3 minute; nu trebuie să se usuce complet.','Scoateți păstăile de cardamom și încorporați zahărul. Adăugați puțin lapte dacă orezul este prea dens.','Împărțiți în patru cupe, puneți stafidele în centru și presărați fisticul. Serviți cald.'],['Place rice, milk and cardamom in a heavy pan. Simmer very gently for 25–35 minutes, stirring often, until the rice is tender.','In a small pan, warm raisins with 30 ml water for 3 minutes; do not let them dry out completely.','Remove cardamom pods and stir in sugar. Add a little milk if the pudding is too thick.','Divide between four cups, place raisins in the centre and scatter pistachios. Serve warm.'],['Reis, Milch und Kardamom in einen schweren Topf geben. 25–35 Minuten sehr sanft köcheln und häufig rühren, bis der Reis weich ist.','Rosinen separat mit 30 ml Wasser 3 Minuten erwärmen; nicht vollständig trocken werden lassen.','Kardamomkapseln entfernen und Zucker einrühren. Bei zu fester Konsistenz etwas Milch ergänzen.','Auf vier Schalen verteilen, Rosinen mittig auflegen und Pistazien darüberstreuen. Warm servieren.']),
 T('Cu infuzie de scorțișoară, fără zahăr suplimentar.','Pair with cinnamon infusion, without additional sugar.','Dazu Zimtaufguss ohne zusätzlichen Zucker.'),['recipe-rice'],T('Lapte, fistic.','Milk, pistachios.','Milch, Pistazien.'))

R('brioche',T('Cupe de brioșă cu rom și stafide','Brioche cups with rum and raisins','Briocheförmchen mit Rum und Rosinen'),4,
 T(['160 g brioșă simplă','60 g stafide simple','20 ml rom sau suc de mere pentru varianta fără alcool','200 ml lapte','1 ou','20 g zahăr','10 g unt','1 linguriță extract de vanilie'],['160 g plain brioche','60 g plain raisins','20 ml rum, or apple juice for an alcohol-free version','200 ml milk','1 egg','20 g sugar','10 g butter','1 tsp vanilla extract'],['160 g einfache Brioche','60 g einfache Rosinen','20 ml Rum oder Apfelsaft für die alkoholfreie Variante','200 ml Milch','1 Ei','20 g Zucker','10 g Butter','1 TL Vanilleextrakt']),
 T(['Încălziți cuptorul la 175°C. Ungeți patru forme mici cu unt și împărțiți brioșa tăiată în cuburi.','Lăsați stafidele 15 minute în rom sau suc și distribuiți-le peste pâine, cu lichidul rămas.','Bateți oul cu laptele, zahărul și vanilia. Turnați în forme și lăsați pâinea să absoarbă lichidul 10 minute.','Coaceți 25–30 de minute până crema este închegată inclusiv în centru. Odihniți 5 minute. Varianta cu rom poate păstra alcool după coacere.'],['Heat the oven to 175°C. Butter four small ovenproof dishes and divide diced brioche between them.','Soak raisins in rum or juice for 15 minutes and distribute over the bread with any remaining liquid.','Whisk egg, milk, sugar and vanilla. Pour into dishes and leave the bread to absorb the liquid for 10 minutes.','Bake for 25–30 minutes until the custard is set, including the centre. Rest for 5 minutes. The rum version may retain alcohol after baking.'],['Ofen auf 175°C vorheizen. Vier kleine ofenfeste Förmchen buttern und Briochewürfel darin verteilen.','Rosinen 15 Minuten in Rum oder Saft einlegen und samt restlicher Flüssigkeit über das Brot verteilen.','Ei, Milch, Zucker und Vanille verquirlen. In die Formen gießen und das Brot 10 Minuten quellen lassen.','25–30 Minuten backen, bis die Creme auch in der Mitte gestockt ist. 5 Minuten ruhen lassen. Die Rumvariante kann nach dem Backen Alkohol enthalten.']),
 T('Cu cafea; folosiți suc de mere dacă doriți o versiune fără alcool.','Serve with coffee; use apple juice when an alcohol-free version is required.','Dazu Kaffee; für eine alkoholfreie Variante Apfelsaft verwenden.'),['recipe-rum'],T('Ou, lapte, grâu/gluten; verificați brioșa.','Egg, milk, wheat/gluten; check the brioche label.','Ei, Milch, Weizen/Gluten; Briocheetikett prüfen.'))

R('oats',T('Parfait rece cu citrice și stafide','Chilled citrus and raisin parfait','Gekühltes Zitrus-Rosinen-Parfait'),4,
 T(['120 g fulgi de ovăz','250 ml lapte','200 g iaurt','60 g stafide simple','80 ml suc de portocale','1 portocală','20 g semințe de dovleac','10 g miere'],['120 g rolled oats','250 ml milk','200 g yoghurt','60 g plain raisins','80 ml orange juice','1 orange','20 g pumpkin seeds','10 g honey'],['120 g Haferflocken','250 ml Milch','200 g Joghurt','60 g einfache Rosinen','80 ml Orangensaft','1 Orange','20 g Kürbiskerne','10 g Honig']),
 T(['Amestecați ovăzul, laptele și mierea într-un recipient închis și păstrați 6–8 ore la frigider.','Înmuiați separat stafidele în suc, tot la frigider, în același interval. Scurgeți înainte de montare.','Împărțiți ovăzul în patru pahare. Adăugați un strat de iaurt și felii de portocală fără membrane.','Finisați cu stafidele și semințele de dovleac. Păstrați rece până la servire și consumați în aceeași zi.'],['Mix oats, milk and honey in a closed container and refrigerate for 6–8 hours.','Separately soak raisins in the juice in the fridge for the same time; drain before assembly.','Divide oats between four glasses. Add a layer of yoghurt and membrane-free orange segments.','Finish with raisins and pumpkin seeds. Keep refrigerated until serving and consume the same day.'],['Hafer, Milch und Honig in einem geschlossenen Behälter mischen und 6–8 Stunden kühlen.','Rosinen separat genauso lange im Saft im Kühlschrank einweichen; vor dem Anrichten abtropfen.','Hafer auf vier Gläser verteilen. Eine Schicht Joghurt und Orangenfilets ohne Trennhäute daraufgeben.','Mit Rosinen und Kürbiskernen abschließen. Bis zum Servieren kühlen und am selben Tag verzehren.']),
 T('Cu ceai rece de mentă, neîndulcit.','Pair with unsweetened chilled mint tea.','Dazu ungesüßten kalten Minztee.'),['recipe-oats'],T('Lapte; ovăzul poate conține gluten, conform etichetei.','Milk; oats may contain gluten according to the label.','Milch; Hafer kann laut Etikett Gluten enthalten.'))

R('aubergine',T('Vânătă coaptă cu stafide și rodie','Roasted aubergine with raisins and pomegranate','Ofenaubergine mit Rosinen und Granatapfel'),4,
 T(['2 vinete medii','60 g stafide simple','30 ml suc de rodie','15 ml melasă de rodie','200 g iaurt grecesc','30 ml ulei de măsline','10 ml suc de lămâie','30 g boabe de rodie','10 g pătrunjel','2 g sare'],['2 medium aubergines','60 g plain raisins','30 ml pomegranate juice','15 ml pomegranate molasses','200 g Greek yoghurt','30 ml olive oil','10 ml lemon juice','30 g pomegranate arils','10 g parsley','2 g salt'],['2 mittelgroße Auberginen','60 g einfache Rosinen','30 ml Granatapfelsaft','15 ml Granatapfelmelasse','200 g griechischer Joghurt','30 ml Olivenöl','10 ml Zitronensaft','30 g Granatapfelkerne','10 g Petersilie','2 g Salz']),
 T(['Tăiați vinetele în jumătăți, crestați pulpa și ungeți cu ulei și sare. Coaceți la 210°C timp de 35–45 de minute, până sunt complet fragede.','Încălziți stafidele cu sucul și melasa de rodie 3–4 minute la foc mic, până apare un sos ușor legat.','Amestecați iaurtul cu lămâia. Așezați o porție sub fiecare jumătate de vânătă.','Distribuiți sosul cu stafide peste vinete și terminați cu boabe de rodie și pătrunjel. Serviți cald.'],['Halve aubergines, score the flesh and brush with oil and salt. Roast at 210°C for 35–45 minutes until completely tender.','Warm raisins with pomegranate juice and molasses over low heat for 3–4 minutes, until lightly syrupy.','Mix yoghurt with lemon. Place a portion underneath each aubergine half.','Spoon raisin sauce over the aubergines and finish with pomegranate arils and parsley. Serve warm.'],['Auberginen halbieren, Fruchtfleisch einschneiden und mit Öl und Salz bestreichen. Bei 210°C 35–45 Minuten vollständig weich backen.','Rosinen mit Granatapfelsaft und Melasse 3–4 Minuten bei kleiner Hitze leicht sirupartig einkochen.','Joghurt mit Zitrone mischen. Unter jede Auberginenhälfte eine Portion setzen.','Rosinensauce darauf verteilen und mit Granatapfelkernen und Petersilie abschließen. Warm servieren.']),
 T('Cu lipie și frunze de mentă.','Serve with flatbread and mint leaves.','Mit Fladenbrot und Minzblättern servieren.'),['recipe-aubergine'],T('Lapte; lipia adaugă grâu/gluten.','Milk; flatbread adds wheat/gluten.','Milch; Fladenbrot ergänzt Weizen/Gluten.'))

R('bark',T('Fragmente de ciocolată cu stafide lucioase','Chocolate shards with glossy raisins','Schokoladensplitter mit glänzenden Rosinen'),8,
 T(['180 g ciocolată neagră','60 g stafide simple','15 g miere','10 ml apă','30 g fistic nesărat','1 linguriță coajă de portocală'],['180 g dark chocolate','60 g plain raisins','15 g honey','10 ml water','30 g unsalted pistachios','1 tsp orange zest'],['180 g dunkle Schokolade','60 g einfache Rosinen','15 g Honig','10 ml Wasser','30 g ungesalzene Pistazien','1 TL Orangenabrieb']),
 T(['Încălziți mierea cu apa într-o tigaie mică. Adăugați stafidele și amestecați 1–2 minute până devin lucioase; răciți complet pe hârtie de copt.','Topiți ciocolata într-un bol deasupra apei fierbinți, fără ca baza să atingă apa. Luați de pe foc și amestecați până devine omogenă.','Întindeți o placă de 3–4 mm pe hârtie de copt. Presărați stafidele reci, fisticul tocat și coaja de portocală.','Răciți 45–60 de minute la frigider și rupeți în opt fragmente. Păstrați la rece; glazura poate înmuia ciocolata la contact, deci montați aproape de servire.'],['Warm honey and water in a small pan. Add raisins and stir for 1–2 minutes until glossy; cool completely on baking paper.','Melt chocolate in a bowl above hot water without letting the bowl touch the water. Remove from heat and stir until smooth.','Spread a 3–4 mm sheet on baking paper. Scatter cold raisins, chopped pistachios and orange zest over it.','Refrigerate for 45–60 minutes and break into eight shards. Keep chilled; the glaze may soften chocolate where it touches, so assemble close to serving.'],['Honig und Wasser in einer kleinen Pfanne erwärmen. Rosinen 1–2 Minuten darin wenden, bis sie glänzen, und auf Backpapier ganz abkühlen.','Schokolade in einer Schüssel über heißem Wasser schmelzen, ohne Wasserkontakt der Schüssel. Vom Herd nehmen und glatt rühren.','Eine 3–4 mm dicke Platte auf Backpapier streichen. Kalte Rosinen, gehackte Pistazien und Orangenabrieb daraufstreuen.','45–60 Minuten kühlen und in acht Stücke brechen. Kühl lagern; die Glasur kann Schokolade an Kontaktstellen weich machen, daher zeitnah servieren.']),
 T('Cu cafea scurtă, câte un fragment la finalul mesei.','Serve one shard with a short coffee after the meal.','Je einen Splitter mit einem Espresso nach dem Essen servieren.'),['recipe-bark'],T('Fistic; verificați laptele și soia de pe eticheta ciocolatei.','Pistachios; check chocolate labels for milk and soy.','Pistazien; Schokoladenetikett auf Milch und Soja prüfen.'))

def replace_recipe(r, old, new):
    for lang in LANGS:
        r['ingredients'][lang] = [s.replace(old[lang], new[lang]) for s in r['ingredients'][lang]]
        r['steps'][lang] = [s.replace(old[lang], new[lang]) for s in r['steps'][lang]]

def recipe_for(id, template):
    r = copy.deepcopy(recipes[template])
    if id == 'stafide-golden':
        r['title'] = T('Morcovi copți, Golden și cremă de lămâie','Roasted carrots, Golden raisins and lemon cream','Ofenkarotten, Golden-Rosinen und Zitronencreme')
        replace_recipe(r,T('conopidă în buchețele','cauliflower florets','Blumenkohlröschen'),T('morcovi tăiați în bastonașe subțiri','carrots cut into thin batons','Karotten in dünnen Stiften'))
        replace_recipe(r,T('Thompson Seedless','Thompson Seedless','Thompson-Seedless'),T('Golden','Golden','Golden'))
        for lang in LANGS:
            r['steps'][lang] = [s.replace('conopida','morcovii').replace('Conopida','Morcovii').replace('cauliflower','carrots').replace('Blumenkohl','Karotten') for s in r['steps'][lang]]
        r['steps']['ro'][3]='Așezați morcovii rumeniți peste cremă, presărați stafidele și pătrunjelul. Serviți când legumele sunt calde, nu fierbinți.'
        r['steps']['de'][3]='Gebräunte Karotten auf die Creme setzen und Rosinen sowie Petersilie darüber verteilen. Gemüse warm, nicht kochend heiß servieren.'
    if id == 'stafide-flame-seedless':
        r['title'] = T('Sfeclă rubinie cu Flame și iaurt','Ruby beetroot with Flame raisins and yoghurt','Rubinrote Bete mit Flame-Rosinen und Joghurt')
        replace_recipe(r,T('700 g conopidă în buchețele','700 g cauliflower florets','700 g Blumenkohlröschen'),T('600 g sfeclă deja fiartă, în sferturi','600 g cooked beetroot, quartered','600 g vorgegarte Rote Bete, geviertelt'))
        replace_recipe(r,T('Thompson Seedless','Thompson Seedless','Thompson-Seedless'),T('Flame Seedless','Flame Seedless','Flame-Seedless'))
        r['steps']['ro'][0]='Amestecați sfecla deja fiartă cu uleiul, chimionul și jumătate din sare. Coaceți la 200°C timp de 18–22 de minute, până marginile se rumenesc.'
        r['steps']['en'][0]='Toss cooked beetroot with oil, cumin and half the salt. Roast at 200°C for 18–22 minutes until its edges brown.'
        r['steps']['de'][0]='Vorgegarte Rote Bete mit Öl, Kreuzkümmel und der Hälfte des Salzes mischen. Bei 200°C 18–22 Minuten rösten, bis die Ränder bräunen.'
        for lang in LANGS:
            r['steps'][lang] = [s.replace('conopida rumenită','sfecla rumenită').replace('browned cauliflower','roasted beetroot').replace('Gebräunten Blumenkohl','Geröstete Rote Bete') for s in r['steps'][lang]]
    if id == 'stafide-verzi':
        r['title']=T('Orez cu stafide verzi, lime și mentă','Rice with green raisins, lime and mint','Reis mit grünen Rosinen, Limette und Minze')
        r['ingredients']=T(['200 g orez basmati','apă și sare conform ambalajului','60 g stafide verzi','1 lime','30 g semințe de dovleac','15 g mentă','15 g pătrunjel','25 ml ulei de măsline'],['200 g basmati rice','water and salt as directed on pack','60 g green raisins','1 lime','30 g pumpkin seeds','15 g mint','15 g parsley','25 ml olive oil'],['200 g Basmatireis','Wasser und Salz nach Packungsangabe','60 g grüne Rosinen','1 Limette','30 g Kürbiskerne','15 g Minze','15 g Petersilie','25 ml Olivenöl'])
        r['steps']=T(['Fierbeți orezul conform ambalajului, scurgeți dacă este necesar și lăsați 5 minute acoperit.','Înmuiați stafidele 10 minute în apă caldă și scurgeți. Prăjiți semințele 2 minute într-o tigaie uscată.','Afânați orezul și adăugați stafidele, uleiul, coaja de lime și 15 ml suc. Încorporați ierburile tocate când orezul nu mai este fierbinte.','Montați patru porții joase și terminați cu semințele. Serviți imediat, călduț.'],['Cook rice as directed on the pack, drain if needed and rest covered for 5 minutes.','Soak raisins in warm water for 10 minutes and drain. Toast seeds in a dry pan for 2 minutes.','Fluff rice and add raisins, oil, lime zest and 15 ml juice. Fold in chopped herbs once the rice is no longer piping hot.','Arrange four low portions and finish with seeds. Serve immediately, warm.'],['Reis nach Packungsangabe garen, bei Bedarf abgießen und zugedeckt 5 Minuten ruhen lassen.','Rosinen 10 Minuten in warmem Wasser einweichen und abtropfen. Kerne 2 Minuten trocken rösten.','Reis lockern und Rosinen, Öl, Limettenabrieb und 15 ml Saft zugeben. Kräuter erst einarbeiten, wenn der Reis nicht mehr sehr heiß ist.','Vier flache Portionen anrichten und mit Kernen abschließen. Sofort lauwarm servieren.'])
        r['allergens']=notes['allergens']
    if id == 'stafide-black-monukka':
        r['title']=T('Orz perlat cu ciuperci și Black Monukka','Pearl barley with mushrooms and Black Monukka','Perlgraupen mit Pilzen und Black Monukka')
        r['ingredients']=T(['200 g orz perlat','350 g ciuperci feliate','60 g stafide Black Monukka fără sâmburi','25 ml ulei de măsline','15 ml suc de lămâie','10 g pătrunjel','2 g sare','apă conform ambalajului orzului'],['200 g pearl barley','350 g sliced mushrooms','60 g Black Monukka raisins, seeds removed','25 ml olive oil','15 ml lemon juice','10 g parsley','2 g salt','water as directed on the barley pack'],['200 g Perlgraupen','350 g Pilze in Scheiben','60 g Black-Monukka-Rosinen, entkernt','25 ml Olivenöl','15 ml Zitronensaft','10 g Petersilie','2 g Salz','Wasser nach Graupen-Packungsangabe'])
        r['steps']=T(['Fierbeți orzul în apă cu sare conform ambalajului, aproximativ 25–35 de minute, până este fraged; scurgeți.','Rumeniți ciupercile în ulei, în două tranșe, câte 6–8 minute. Nu aglomerați tigaia.','Verificați stafidele de sâmburi, înmuiați-le 10 minute în apă caldă și scurgeți. Combinați cu orzul și ciupercile.','Adăugați lămâia și pătrunjelul. Serviți în patru boluri negre, cu câteva ciuperci păstrate deasupra.'],['Cook barley in salted water according to its pack, about 25–35 minutes, until tender; drain.','Brown mushrooms in oil in two batches, 6–8 minutes each. Do not crowd the pan.','Check raisins for seeds, soak in warm water for 10 minutes and drain. Combine with barley and mushrooms.','Add lemon and parsley. Serve in four black bowls with a few reserved mushrooms on top.'],['Graupen nach Packungsangabe in Salzwasser etwa 25–35 Minuten weich garen und abgießen.','Pilze in Öl in zwei Portionen jeweils 6–8 Minuten bräunen. Pfanne nicht überfüllen.','Rosinen auf Kerne prüfen, 10 Minuten warm einweichen und abtropfen. Mit Graupen und Pilzen vermengen.','Zitrone und Petersilie zugeben. In vier schwarzen Schalen mit einigen reservierten Pilzen anrichten.'])
        r['allergens']=T('Orz/gluten.','Barley/gluten.','Gerste/Gluten.')
    if id == 'stafide-rose-red':
        r['title']=T('Cremă de ricotta, fructe roșii și Rose Red','Ricotta cream, red berries and Rose Red','Ricottacreme mit roten Beeren und Rose Red')
        replace_recipe(r,T('60 g stafide Muscat, fără sâmburi','60 g Muscat raisins, seeds removed','60 g Muscat-Rosinen, entkernt'),T('60 g stafide Rose Red, fără sâmburi','60 g Rose Red raisins, seeds removed','60 g Rose-Red-Rosinen, entkernt'))
        replace_recipe(r,T('1 portocală','1 orange','1 Orange'),T('150 g căpșuni','150 g strawberries','150 g Erdbeeren'))
        r['steps']['ro'][2]='Spălați căpșunile, îndepărtați codițele și tăiați-le în sferturi. Tocați fisticul grosier.'
        r['steps']['en'][2]='Wash and hull strawberries, then quarter them. Roughly chop pistachios.'
        r['steps']['de'][2]='Erdbeeren waschen, putzen und vierteln. Pistazien grob hacken.'
        for lang in LANGS:
            r['steps'][lang]=[s.replace('portocala','căpșunile').replace('orange and raisins','strawberries and raisins').replace('Orange, Rosinen','Erdbeeren, Rosinen') for s in r['steps'][lang]]
    if id == 'stafide-paan':
        r['inspiration_source_ids']=['recipe-rose']
        r['title']=T('Cupă florală cu stafide și cardamom','Floral raisin and cardamom cup','Floraler Rosinen-Kardamom-Becher')
        r['ingredients']=T(['250 g iaurt grecesc','150 g ricotta','60 g stafide simple','15 g miere','1 g cardamom măcinat','2 ml apă de trandafiri alimentară','20 g fistic nesărat'],['250 g Greek yoghurt','150 g ricotta','60 g plain raisins','15 g honey','1 g ground cardamom','2 ml food-grade rosewater','20 g unsalted pistachios'],['250 g griechischer Joghurt','150 g Ricotta','60 g einfache Rosinen','15 g Honig','1 g gemahlener Kardamom','2 ml Rosenwasser in Lebensmittelqualität','20 g ungesalzene Pistazien'])
        r['steps']=T(['Înmuiați stafidele 10 minute în apă caldă, scurgeți și răciți complet.','Amestecați iaurtul cu ricotta, mierea și cardamomul. Adăugați apa de trandafiri câte o picătură, până la intensitatea dorită.','Încorporați jumătate din stafide. Împărțiți crema în patru cupe și răciți 30 de minute.','Adăugați stafidele rămase și fisticul tocat. Rețeta nu conține betel, areca sau tutun.'],['Soak raisins in warm water for 10 minutes, drain and cool completely.','Mix yoghurt with ricotta, honey and cardamom. Add rosewater drop by drop to the desired intensity.','Fold in half the raisins. Divide cream between four cups and chill for 30 minutes.','Top with remaining raisins and chopped pistachios. This recipe contains no betel, areca or tobacco.'],['Rosinen 10 Minuten in warmem Wasser einweichen, abtropfen und vollständig abkühlen.','Joghurt mit Ricotta, Honig und Kardamom verrühren. Rosenwasser tropfenweise bis zur gewünschten Intensität zugeben.','Die Hälfte der Rosinen unterheben. Creme auf vier Becher verteilen und 30 Minuten kühlen.','Mit restlichen Rosinen und gehackten Pistazien abschließen. Dieses Rezept enthält weder Betel noch Areka oder Tabak.'])
    if id == 'stafide-ciocolata-scortisoara':
        r['title']=T('Ciocolată intensă cu stafide și scorțișoară','Dark chocolate with raisins and cinnamon','Dunkle Schokolade mit Rosinen und Zimt')
        replace_recipe(r,T('50 g alune de pădure','50 g hazelnuts','50 g Haselnüsse'),T('60 g stafide simple și 1 g scorțișoară','60 g plain raisins and 1 g cinnamon','60 g einfache Rosinen und 1 g Zimt'))
        r['steps']['ro'][0]='Înmuiați stafidele 10 minute în apă caldă, scurgeți și tamponați foarte bine. Păstrați un sfert pentru decor.'
        r['steps']['en'][0]='Soak raisins in warm water for 10 minutes, then drain and pat very dry. Reserve one quarter for decoration.'
        r['steps']['de'][0]='Rosinen 10 Minuten warm einweichen, abtropfen und sehr gut trocken tupfen. Ein Viertel für die Dekoration zurückhalten.'
        r['steps']['ro'][2]='Amestecați crema din centru până devine netedă. Adăugați sarea, scorțișoara și trei sferturi din stafide, împărțiți în patru cupe și răciți 2 ore.'
        r['steps']['en'][2]='Stir the cream from the centre until smooth. Add salt, cinnamon and three quarters of the raisins, divide between four cups and chill for 2 hours.'
        r['steps']['de'][2]='Creme von der Mitte aus glatt rühren. Salz, Zimt und drei Viertel der Rosinen einarbeiten, auf vier Becher verteilen und 2 Stunden kühlen.'
        r['steps']['ro'][3]='Decorați cu stafidele rămase și felii de portocală. Serviți porții mici, direct din cupe.'
        r['steps']['en'][3]='Decorate with reserved raisins and orange segments. Serve small portions directly from the cups.'
        r['steps']['de'][3]='Mit restlichen Rosinen und Orangenfilets dekorieren. Kleine Portionen direkt aus den Bechern servieren.'
        r['allergens']=T('Lapte; verificați soia și alți alergeni ai ciocolatei.','Milk; check chocolate for soy and other allergens.','Milch; Schokolade auf Soja und weitere Allergene prüfen.')
    if id == 'stafide-vin':
        r['title']=T('Pară coaptă cu stafide în vin și cremă sărată','Roasted pear with wine raisins and savoury cream','Ofenbirne mit Weinrosinen und herzhafter Creme')
        r['ingredients']=T(['2 pere ferme','60 g stafide simple','100 ml vin roșu sau suc de struguri pentru varianta fără alcool','15 g miere','100 g brânză proaspătă de capră','80 g iaurt grecesc','10 ml ulei de măsline'],['2 firm pears','60 g plain raisins','100 ml red wine, or grape juice for an alcohol-free version','15 g honey','100 g soft goat cheese','80 g Greek yoghurt','10 ml olive oil'],['2 feste Birnen','60 g einfache Rosinen','100 ml Rotwein oder Traubensaft für die alkoholfreie Variante','15 g Honig','100 g Ziegenfrischkäse','80 g griechischer Joghurt','10 ml Olivenöl'])
        r['steps']=T(['Înjumătățiți perele, scoateți cotorul și ungeți cu ulei. Coaceți la 190°C timp de 20–25 de minute, până devin fragede.','Fierbeți foarte încet stafidele cu vinul și mierea 6–8 minute, până sosul se leagă ușor. Nu flambați.','Amestecați brânza cu iaurtul. Așezați crema în patru farfurii și puneți deasupra câte o jumătate de pară.','Distribuiți stafidele și sosul. Vinul gătit poate păstra alcool; utilizați suc de struguri pentru versiunea fără alcool.'],['Halve and core pears, brush with oil and roast at 190°C for 20–25 minutes until tender.','Gently simmer raisins with wine and honey for 6–8 minutes until lightly syrupy. Do not flambé.','Mix cheese and yoghurt. Spread cream over four plates and top each with a pear half.','Distribute raisins and sauce. Cooked wine may retain alcohol; use grape juice for an alcohol-free version.'],['Birnen halbieren, entkernen, ölen und bei 190°C 20–25 Minuten weich backen.','Rosinen mit Wein und Honig 6–8 Minuten sanft köcheln, bis die Sauce leicht bindet. Nicht flambieren.','Käse und Joghurt verrühren, auf vier Teller streichen und je eine Birnenhälfte daraufsetzen.','Rosinen und Sauce verteilen. Gekochter Wein kann Alkohol enthalten; für die alkoholfreie Variante Traubensaft verwenden.'])
        r['allergens']=T('Lapte; vinul poate conține sulfiți, verificați eticheta.','Milk; wine may contain sulphites, check the label.','Milch; Wein kann Sulfite enthalten, Etikett prüfen.')
    return r

base_products = json.loads((ROOT/'food/catalog.json').read_text(encoding='utf-8')) + json.loads((ROOT/'food/raisin-drafts.json').read_text(encoding='utf-8'))['products']
lookup = {p['id']: p for p in base_products}
result = dict(schema_version=1, researched_at=DATE, brand='Dracula Food', status='editorial_review', languages=list(LANGS), sources=sources, products=[])
for i,(id,fid,intro,history,history_sources,story,template) in enumerate(profiles,1):
    original = lookup[id]
    data=json.loads(Path(f'work/usda-{fid}.json').read_text(encoding='utf-8-sig'))
    nutrient_by_number={n['nutrient']['number']:n.get('amount') for n in data['foodNutrients']}
    values={field:nutrient_by_number.get(code) for field,code in {'kcal':'208','energy_kj':'268','protein_g':'203','fat_g':'204','saturates_g':'606','carbohydrate_by_difference_g':'205','sugars_g':'269','fibre_g':'291','sodium_mg':'307'}.items()}
    compound=i>=13
    nutrition_note={lang:notes['nutrition'][lang]+(' '+notes['compound'][lang] if compound else '') for lang in LANGS}
    recipe=recipe_for(id,template)
    product=dict(id=id,sku=f'DF-{i:03d}',name=original['name'],status='editorial_review',nutrition=dict(product_values=None,reference=dict(basis_g=100,fdc_id=fid,source_id=f'usda-{fid}',food_name=data['description'],values=values),note=nutrition_note),content={})
    for lang in LANGS:
        labels=T(['Cod','Tip','Cantitate netă','Origine lot','Procesare','Calibru / umiditate','Ambalaj','Utilizare'],['Code','Type','Net quantity','Batch origin','Processing','Size / moisture','Packaging','Use'],['Code','Typ','Nettofüllmenge','Chargenherkunft','Verarbeitung','Größe / Feuchte','Verpackung','Verwendung'])[lang]
        pending=T('De confirmat prin fișa furnizorului.','To be confirmed by supplier specification.','Durch Lieferantenspezifikation zu bestätigen.')[lang]
        type_text=(T('Fruct cu coajă; specie și formă comercială de validat.','Tree nut; species and commercial form to be validated.','Schalenfrucht; Art und Handelsform zu bestätigen.') if i<=2 else T('Concept de stafide aromatizate / acoperite.','Flavoured / coated raisin concept.','Konzept aromatisierter / überzogener Rosinen.') if compound else T('Selecție propusă de struguri uscați; soi de validat pe lot.','Proposed dried-grape selection; cultivar to be validated per batch.','Geplante Auswahl getrockneter Trauben; Sorte chargenbezogen zu bestätigen.'))[lang]
        quantity=(T('Macheta existentă indică 500 g; cantitatea comercială nu este încă confirmată.','Existing mockup shows 500 g; commercial quantity is not yet confirmed.','Der vorhandene Entwurf zeigt 500 g; die Handelsmenge ist noch nicht bestätigt.')[lang] if i<=2 else pending)
        technical_values=[f'DF-{i:03d}',type_text,quantity,pending,pending,pending,T('Cutie de prezentare neagră; materialele în contact cu alimentul și închiderea sunt de confirmat.','Black presentation box; food-contact materials and closure remain to be confirmed.','Schwarze Präsentationsbox; Lebensmittelkontaktmaterialien und Verschluss sind zu bestätigen.')[lang],T('Degustare și rețeta editorială de mai jos, după verificarea etichetei ingredientelor.','Tasting and the editorial recipe below, after checking ingredient labels.','Verkostung und das untenstehende redaktionelle Rezept nach Prüfung der Zutatenetiketten.')[lang]]
        allergens=notes['allergens'][lang]
        if i==1: allergens=T('Alergen identificat: nuci. ','Identified allergen: walnuts. ','Identifiziertes Allergen: Walnüsse. ')[lang]+allergens
        if i==2: allergens=T('Alergen identificat: alune de pădure. ','Identified allergen: hazelnuts. ','Identifiziertes Allergen: Haselnüsse. ')[lang]+allergens
        p_recipe={k:(v[lang] if isinstance(v,dict) and lang in v else v) for k,v in recipe.items()}
        p_recipe['status']=notes['recipe_status'][lang]
        if compound:p_recipe['ingredient_note']=notes['plain_substitute'][lang]
        p_recipe['inspiration_note']=T('Compoziție proprie Dracula Food; consultați sursa pentru inspirația culinară, fără asociere comercială cu autorul.','An original Dracula Food composition; consult the source for culinary inspiration. No commercial association with the author is implied.','Eine eigene Dracula-Food-Komposition; die Quelle erläutert die kulinarische Inspiration. Eine geschäftliche Verbindung zum Autor wird nicht behauptet.')[lang]
        product['content'][lang]=dict(intro=intro[lang],technical=[dict(label=l,value=v) for l,v in zip(labels,technical_values)],ingredients=notes['ingredients'][lang],allergens=allergens,storage=notes['storage'][lang],storage_source_ids=['nuts-storage'] if i<=2 else [],history=dict(text=history[lang],source_ids=history_sources),brand_story=story[lang],recipe=p_recipe)
    result['products'].append(product)

assert len(result['products'])==19
source_ids={s['id'] for s in sources}
for p in result['products']:
    assert set(p['content'])==set(LANGS)
    assert p['nutrition']['product_values'] is None
    for lang,c in p['content'].items():
        assert len(c['recipe']['steps'])>=4 and len(c['technical'])==8
        assert all(s in source_ids for s in c['history']['source_ids']+c['recipe']['inspiration_source_ids'])

(ROOT/'food/product-enrichment.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines=['# Surse și metodă — Dracula Food', '', f'Cercetare verificată la {DATE}. 19 produse, 57 fișe localizate RO/EN/DE.', '',
'Fișierul `food/product-enrichment.json` conține conținut editorial pentru integrarea în DB. Nu modifică produsele, prețurile sau stocurile. `nutrition.product_values` este null pentru toate produsele: lipsesc analizele sau declarațiile furnizorului.', '',
'## Nutriție', '',
'Valorile USDA au fost citite direct din API FoodData Central, nu deduse din site-uri terțe. Unitățile sunt explicite în chei. Baza este 100 g de parte comestibilă a ingredientului generic. Glucidele „by difference” includ fibrele; nu trebuie redenumite automat drept glucide pe o etichetă UE. Energia kJ este valoarea din înregistrarea USDA, fără recalculare. Nu au fost calculate procente din necesarul zilnic sau beneficii medicale.', '',
'Pentru Golden folosim înregistrarea dedicată, iar pentru Corint înregistrarea Zante. Celelalte selecții au referința generică pentru stafide închise fără sâmburi, fără a pretinde o analiză de soi. Pentru cele șapte produse compuse, tabelul descrie exclusiv ingredientul de bază; rețeta finală poate modifica substanțial valorile.', '',
'| Referință | FDC | kcal / 100 g |', '|---|---:|---:|']
for fid in (170187,170581,168165,168164,171724):
    d=json.loads(Path(f'work/usda-{fid}.json').read_text(encoding='utf-8-sig'))
    kcal=next(n['amount'] for n in d['foodNutrients'] if n['nutrient']['number']=='208')
    lines.append(f'| {d["description"]} | {fid} | {kcal} |')
lines += ['', '## Precizări editoriale', '',
'- Rose Red este denumire comercială nevalidată; nu i-am inventat genealogie sau origine.',
'- Manukka nu este echivalat automat cu Monukka. Sultaniye și Thompson pot fi sinonime botanice; diferențierea comercială trebuie documentată.',
'- Anardana este ingredient din rodie, nu soi de stafide. Paan nu dovedește compoziția, prezența betelului ori efecte digestive.',
'- Nu afirmăm proveniență din Dracula-Farm, procesare „fără aditivi”, absență de sulfiți, certificări sau gramaje comerciale neconfirmate.',
'- Istoria factuală are surse separate; poveștile de brand sunt marcate explicit „Poveste editorială”.',
'- Cele 19 propuneri culinare sunt formulări proprii, cu cantități și pași proprii și surse de inspirație. Nu sunt reproduceri ale rețetelor autorilor și nu implică afiliere. Sunt netestate în bucătărie; timpii sunt orientativi și includ repere de textură.',
'- Alergenii rețetelor de servire sunt declarați separat de compoziția comercială. Variantele cu rom/vin pot păstra alcool; alternativa cu suc este explicită.',
'- Temperatura de depozitare, durata de viață, materialele de contact, compoziția și declarația de alergeni necesită fișele furnizorului.', '', '## Registrul surselor', '']
for s in sources:
    lines += [f'### {s["id"]}', '',f'[{s["title"]}]({s["url"]}) — consultat {s["accessed_at"]}.', '',s['scope'], '']
(ROOT/'FOOD-SOURCES.md').write_text('\n'.join(lines),encoding='utf-8')
print(json.dumps({'products':len(result['products']),'localized_sheets':sum(len(p['content']) for p in result['products']),'sources':len(sources),'output':str(ROOT/'food/product-enrichment.json')},indent=2))
