from pathlib import Path
from html import escape
import csv
out=Path('8.1 Documente necesare din proiectele anterioare');out.mkdir(exist_ok=True)
projects=[
('01 EcoWarriors AFM 650H','ROSE','EcoWarriors / AFM 650H','Confirmat de utilizator: implementare, rezultate și existența contractului și raportului final/acceptării; documente încă necitite.','Eligibilitate GSCS5.1.3 prin resurse educaționale/metode inovatoare; criterii3.6 și3.7 dacă relevanța este probată.'),
('02 Educatie pentru un mediu curat','ROSE','Educație pentru un mediu curat','Menționat public; de stabilit dacă este proiect distinct de650H.','Dacă distinct, aceeași verificare a experienței educaționale; fără dublarea aceleiași operațiuni.'),
('03 POCU 128613','ROSE','R O S E – Responsabilitate – Oportunitate – Sustenabilitatea Economică / POCU128613','Identificat public ca proiect de antreprenoriat social; contractul, perioada și închiderea sunt de confirmat.','Posibil suport pentru experiență de implementare/activități sociale relevante; NU înlocuiește automat proiectul educațional din ultimii3ani.'),
('04 AMR 58203','ROSE','AMR – Activ în mediul rural / SMIS58203','Identificat public în2015; documentele și rolul sunt de verificat.','Experiență istorică; perioada cunoscută nu îndeplinește singură cerința proiectului din ultimii3ani. Relevanța3.6/3.7 se verifică separat.'),
('05 Municipiul Sebes','Municipiul Sebeș','Proiectele relevante ale liderului','Lider confirmat; portofoliul complet relevant și rezultatele nu sunt încă în dosar.','Criteriile3.6 și3.7 privesc și solicitantul, nu doar ONG. Separat, prevenirea dublei finanțări cu proiectele curente.'),
('06 Alte proiecte relevante','Fiecare membru','Alte proiecte educaționale/sociale relevante','De completat din registrul entității; inclusiv inițiative din fonduri proprii dacă au probe suficiente.','Demonstrarea activităților relevante și verificarea perioadei, rolului și rezultatelor, după ghid.')]
common=[
('P01','Identificare și rol','Fișa proiectului: titlu exact, cod, finanțator, contract, beneficiar/partener, responsabil, perioadă inițială și finală, buget și activități proprii.','ROSE/UAT – manager proiect anterior'),
('P02','Finanțare aprobată','Contractul/decizia de finanțare semnată și actele adiționale care schimbă perioada, activitățile, parteneriatul, bugetul sau indicatorii.','ROSE/UAT – arhivă juridică'),
('P03','Conținut aprobat','Cererea/propunerea aprobată și anexele privind obiectivele, grupul țintă, activitățile, rezultate, indicatori și responsabilitățile entității.','ROSE/UAT – manager anterior'),
('P04','Parteneriat și contribuție proprie','Acordul de parteneriat și defalcarea activităților asumate efectiv de membrul care invocă experiența; pentru beneficiar unic se marchează neaplicabil.','ROSE/UAT – juridic'),
('P05','Perioada efectivă','Raport de început/progres/final și livrabile datate care probează, pentru criteriul 3.6, alternativa aplicabilă: liderul are minimum 12 luni relevante SAU liderul și fiecare partener au minimum 6 luni relevante. Separat, documentele probează încadrarea proiectului educațional în ultimii 3 ani pentru eligibilitatea ONG.','ROSE/UAT – manager anterior'),
('P06','Rezultate recepționate','Procese-verbale de recepție, aprobări ale rapoartelor, notificări de acceptare a finanțatorului, după forma prevăzută în contract. O fotografie sau o pagină web nu înlocuiește recepția.','ROSE/UAT – manager/finanțator, documente existente'),
('P07','Indicatori asumați și realizați','Tabel indicator cu definiție/unitate, țintă contractuală inițială, țintă finală aprobată, realizat acceptat, data și documentul de validare. Includeți toți indicatorii relevanți; fără medii inventate.','ROSE/UAT – monitorizare'),
('P08','Închiderea proiectului','Raportul final transmis, dovada acceptării/închiderii, notificări asupra corecțiilor sau rezervelor relevante și eventuale clarificări ale finanțatorului.','ROSE/UAT – manager/financiar'),
('P09','Beneficiari și utilizare','Situații agregate pe vârste/categorii și număr unic; liste codificate sau mostre anonimizate de prezență, utilizarea produselor și acorduri cu unități. Nu se colectează în această etapă copii integrale de acte ale minorilor.','ROSE/UAT – implementare/protecția datelor'),
('P10','Calificări și atribuții relevante','Fișele rolurilor, CV-uri și calificări ale experților care pot demonstra capacitate relevantă, împreună cu dovezile activităților entității. Experiența unei persoane nu devine automat experiența ONG.','ROSE/UAT – resurse umane'),
('P11','Relevanță pentru noul proiect','Notă de1–2pagini: activitate anterioară → probă → competență → activitate atribuită în proiectul Sebeș. Separat: eligibilitate ONG /3.6 /3.7.','Echipa de scriere și jurist'),
('P12','Portofoliu și suprapuneri','Lista proiectelor în curs/contractate, cod/program/perioadă/rol, inclusiv numărul proiectelor PEO; active, personal, participanți și perioade care ar putea coincide cu noul proiect.','ROSE/UAT – financiar și manager')]
special={
'01 EcoWarriors AFM 650H':'''Suplimentar: contractul AFM cu numărul complet650H și data; titlul contractual exact și legătura cu marcaEcoWarriors; aplicația și documentația produsului în formă sigură, manual, capturi și proces-verbal de recepție (nu este necesară instalarea unui APK pentru această verificare); modulele, planurile de lecții, materialele și ghidurile; descrierea metodei pedagogice și elementele inovatoare față de practica obișnuită; drepturile de utilizare/proprietate; utilizarea efectivă în unități și rezultatele pentru copii; vârste/categorii agregate; rapoarte de acceptare AFM; explicația relației dintre produsele cumpărate de la terți și activitatea asumată de ONG. Furnizarea unui produs de către un prestator nu demonstrează singură întregul rol invocat de ONG.
Date exacte încă necesare: început/final implementare, date recepții, ținte și rezultate acceptate. Confirmarea utilizatorului privind existența documentelor este consemnată; nu se cere reconfirmarea existenței lor.''',
'02 Educatie pentru un mediu curat':'''Înaintea dublării dosarului: identificați numărul contractului și dacă proiectul este distinct deEcoWarriors/650H. Dacă este același, folosiți trimitere la dosarul01. Dacă este distinct, adăugați aceleași probe pedagogice, perioade, recepții și rezultate. Site-ul public asociat nu este utilizat drept probă suficientă: la consultare a returnat conținut străin proiectului; se folosesc documentele originale ale organizației.''',
'03 POCU 128613':'''Contract, acord de parteneriat dacă există, raport final și indicatori validați, inclusiv beneficiari/întreprinderi sociale numai dacă sunt indicatori contractuali. Delimitați activitățile relevante pentru recrutare, intervenție socială, management și cooperare. Nu se echivalează formarea antreprenorială a adulților cu educația timpurie și nu se presupune că o perioadă veche intră în ultimii3ani.''',
'04 AMR 58203':'''Acordul și bugetul parteneruluiROSE, activități efectiv realizate, minimum6luni de experiență dacă sunt invocate, rapoarte și indicatori validați aferenți rolului. Pentru operațiunea istorică din2015 nu invocați automat condiția temporală de eligibilitate ONG din GSCS5.1.3. Rolul în grila3.6/3.7 se stabilește după domeniul activităților nou atribuite.''',
'05 Municipiul Sebes':'''Un subdosar pentru fiecare proiect relevant al liderului. Adăugați hotărâri locale, acorduri și recepții ale serviciilor educaționale/sociale, indicatori validați și perioada. Pentru proiectele curente de infrastructură/dotări: inventarul pe unitate și număr de inventar, finanțator/cod, data recepției, valoare, destinație și restricții. Se verifică distinct dotările PNRR transferate în2026 și proiectele locale invocate de specialiști; simpla existență a unei investiții nu înseamnă experiență eligibilă pe toate activitățile ori drept de redecontare.''',
'06 Alte proiecte relevante':'''Listați inițiativele relevante complet, cu finanțare publică, privată sau proprie. Pentru proiecte din fonduri proprii fără contract extern: decizie internă, program și buget aprobat, dovezi de implementare și recepție/rezultate verificabile. Pentru note conceptuale doar depuse/admisibile nu afirmați implementare. Relevanța se verifică individual; nu presupunem că orice proiect social este eligibil.'''}
intro='''LISTA DOCUMENTELOR NECESARE DIN FIECARE PROIECT ANTERIOR
07.10.2026 | Sebeș – ROMANIAN SOUL ENTITY
Confirmare primită: utilizatorul declară implementarea și rezultateleEcoWarriors și existența contractului și raportului final/acceptării. Documentele nu au fost încă analizate de echipă. Nu se reia întrebarea privind existența lor; se organizează colectarea și verificarea.

TREI VERIFICĂRI DISTINCTE
1. Eligibilitate ONG, GSCS5.1.3: minimum1proiect în ultimii3ani în domeniile enumerate, inclusiv dezvoltarea de resurse educaționale și metode pedagogice inovatoare. Nu impunem nejustificat ca această alternativă să fie exclusiv educație timpurie; relevanța și rolul ONG trebuie demonstrate.
2. Criteriul3.6: grila prezintă două alternative disjunctive de maximum1punct: solicitantul are minimum12luni relevante SAU solicitantul și fiecare partener au minimum6luni relevante. Pentru parteneriat documentăm prudent liderul și ONG; nu presupunem că experiența liderului acoperă lipsa experienței partenerului. Nu se adună punctele alternativelor.
3. Criteriul3.7: operațiuni anterioare relevante și realizarea indicatorilor. Trepte: maximum70%=0p;70,01–80%=1p;80,01–90%=2p;strict peste90,01%=3p. Textul are discontinuități între praguri; valori aflate în intervalele neacoperite necesită clarificare AM/OI. Nu inventăm rotunjiri, medii sau o regulă de agregare între indicatori/proiecte/membri. Se păstrează țintele inițiale și cele finale aprobate, cu dovezile modificărilor.
Grila3.7 nu enunță aici o limită proprie de3ani; aceasta nu se transferă automat din eligibilitatea ONG. Experiența istorică rămâne supusă relevanței pentru activitățile asumate.

ORGANIZARE
Pentru fiecare proiect: fișaP01, documenteP02–P12 aplicabile și tabelul indicatorilor. O singură copie pentru fiecare document; notați fișierul/pagina și referințele în registru. Marcajele permise:de primit/primit-neverificat/verificat/conform/neconform/neaplicabil justificat. Niciun document nu se marchează verificat doar pentru că existența lui a fost confirmată verbal.
'''
text=intro+'\nDOSAR COMUN PENTRU FIECARE PROIECT\n'+'\n\n'.join(' | '.join(x) for x in common)
for folder,owner,name,status,use in projects:
 p=out/folder;p.mkdir(exist_ok=True)
 content=f'{name}\nEntitate:{owner}\nStatut:{status}\nUtilizare:{use}\n\n'+special[folder]+'\n\nDOCUMENTE COMUNE\n'+'\n\n'.join(' | '.join(x) for x in common)
 (p/'Lista_documente.txt').write_text(content,encoding='utf-8')
 text+='\n\n'+content
 with (p/'Tabel_indicatori_de_completat.csv').open('w',encoding='utf-8-sig',newline='') as f:
  w=csv.writer(f,delimiter=';');w.writerow(['Proiect','Entitate','Indicator_definitie','Unitate','Tinta_initiala','Tinta_finala_aprobata','Act_modificare','Realizat_acceptat','Data_acceptarii','Rata_procent_de_calculat','Document_fisier_pagina','Legatura_activitate_noua','Observatii']);w.writerow([name,owner]+['']*11)
with (out/'Registru_documente_pe_proiect.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.writer(f,delimiter=';');w.writerow(['Dosar','Entitate','Proiect','ID_document','Document_necesar','Status','Fisier_pagina','Responsabil','Observatii'])
 for folder,owner,name,status,use in projects:
  for code,label,desc,resp in common:w.writerow([folder,owner,name,code,label+' – '+desc,'De primit','','',resp])
(out/'Lista_documente_pe_proiect.txt').write_text(text,encoding='utf-8')
html='<!doctype html><html lang="ro"><meta charset="utf-8"><title>Documente din proiectele anterioare</title><style>body{font:16px/1.6 Segoe UI,Arial;max-width:1050px;margin:36px auto;color:#17364a}pre{white-space:pre-wrap;font:inherit}a{color:#006498}.box{padding:22px;background:#edf5f8;border-left:5px solid #17364a}</style><h1>Documente din proiectele anterioare</h1><div class="box">Contracte, rezultate recepționate și indicatori validați – verificări separate pentru eligibilitate și punctaj.</div><p><a href="Registru_documente_pe_proiect.csv">Registru de urmărire</a></p><pre>'+escape(text)+'</pre></html>'
(out/'Lista_documente_pe_proiect.html').write_text(html,encoding='utf-8')
print('Liste create:6dosare,72pozitii documentare.')
