from pathlib import Path
import csv,json,html,hashlib
r=Path(__file__).resolve().parent;o=r/'1.2 Contractare si implementare'
rows=[]
def a(i,domain,contract,manual,specific,rule,control,status='REGULA_ANALIZATA_APLICARE_DE_VALIDAT'):
 rows.append(dict(ID=i,Domeniu=domain,Contract_general=contract,Manual_instructiune=manual,GSCS_contract_specific=specific,Regula_si_delimitare=rule,Actiune_control=control,Status=status))
a('A44-01','Versiune și ierarhie','Ordin2041 consolidare17.04.2025 ID296187; art3 ordin','Instr10/2025 art1–3; Manualv5 introducere','Anexa4 laGSCS art3; GSCS11–12','Instr10 aprobă manualv5 și încetează9/2025. Manualul nu derogă de la contract/lege. Forma270845 recuperată inițial este bază; meniul consolidărilor nu certifică forma corpului. Textul296187 conține nota Ordin714/2025 și este versiunea comparată.','Folosiți consolidarea și condițiile specifice împreună; controlați actualizările înaintea semnării/implementării. Nu preluați ramurile alternative ale modelului pentru asistență tehnică.','DOCUMENTARE_NUCLEU_INCHISA_MONITORIZARE_CONTINUA')
a('A44-02','Canal și semnătură','Art comunicări/MySMIS și obligații beneficiar','Instr11/2025 art1–4, citită integral2pag','Anexa4 art4,7; GSCS7,11,12','Contractare:acte adiționale/notificări cu aprobare; Achiziții:dosarele achizițiilor; Implementare:cereri/RP/monitorizare; Comunicare:comunicări, notificări unilaterale, planificarea lunară. Instr11 înlocuiește4/2024.','Desemnați accesuri și înlocuitori; registru transmiteri/confirmări, semnătură calificată, termene de răspuns.')
a('A44-03','Instrucțiune cu domeniu limitat','Nu modifică încadrarea generală UAT/ONG','Instr12/2026 art1–3, citită integral2pag','SebeșUAT și ONG nu sunt universități de stat','Instr12 privește posturile externe organigramei universităților de stat coordonate deMEC și încetarea6/2025 la13.07.2026. Nu este temei salarial pentru acest parteneriat.','Arhivați cu eticheta NEAPLICABIL_DIRECT, reevaluare numai dacă apare o entitate din domeniul instrucțiunii.','NEAPLICABIL_DIRECT_JUSTIFICAT')
a('A44-04','Data începerii și durată','Art2; art10(6)–(7)','Manual2.3','GSCS5.6; Anexa4 art2','Calendarul contractual determină începutul; dacă cel dinCF nu este aliniat, manualul prevede notificare în5zile lucrătoare după semnare. Prelungirea nu depășește plafonulGSCS și31.12.2029; suspendarea nu creează eligibilitate automată pentru costul perioadei suspendate.','Convertiți calendarul2027–2028 în date contractuale după semnare; revalidați vârste/cohorte și avize, fără schimbarea tacită a duratei.')
a('A44-05','Prefinanțare','Art5 și OUG133/HG829','Manual3.1, în special3.1.2–3.1.5','Anexa4 art4(a)','Dreptul se verifică distinct pe entitate după excluderile legale; nu toate instituțiile publice au același regim. Tranșa+sumele nejustificate respectă plafonul aplicabil; general30% din alocarea eligibilă, în condițiile regimului. Justificarea generală:minimum50% în90zile calendaristice de la virare, potrivit manualului și normelor actuale.','Economistul mapează UAT/ONG la OUG133, conturile, cererile, soldul și termenele pe entitate; nu aplicați automat tuturor30%×bugettotal.')
a('A44-06','Cereri de plată șiCRCP','Art6; OUG133/HG829','Manual3.3.7–3.3.8','Anexa4 art4(c)','Utilizarea sumelor în maximum5zile lucrătoare de la încasare; CRaferentăCP în maximum10zile lucrătoare de la încasare. Liderul centralizează; plățile se urmăresc pe entitate și document. Contribuția proprie urmează regimul aplicabil.','Calendar de trezorerie cu date de încasare/plată/CRCP și verificator; nu confundați10zileCRCP cu10zileRP ori achiziții.')
a('A44-07','Rambursare finală și grafic','Art3/6/7; grafic anexa3contract','Manual3.2,3.2.1','Anexa4 art4(b),(e)','CRfinală maximum90zile de la finalul implementării, cu cheltuieli eligibile și reguli de plată respectate. Graficul se actualizează; nerespectarea lui poate provoca returnarea cererii. Termenul de depunereCR nu prelungește automat eligibilitatea costului.','PlanificațiCRfinală și documentele înaintea finalului; înregistrați clarificările și răspunsurile în termenul notificat.')
a('A44-08','Contabilitate și reconciliere','Art7 obligații evidență/audit','Manual3.6','Anexa4 art4(b)','Evidență contabilă distinctă, conturi analitice proiect. Reconcilierea lunară transmisă până la20a lunii curente conform formularului legal.','Responsabil financiar UAT șiONG; reconciliere conturi/cereri/încasări/restituiri, cu registru comun verificat de lider.')
a('A44-09','Raportare progres','Art13, plan monitorizare','Manual4.1.1','Anexa4 art4(b); GSCS11','RP acoperă perioade consecutive de maximum3luni; transmis în30zile după sfârșitul perioadei și cu cel puțin10zile LUCRĂTOARE înainte deCR/CRCP. Activitățile cerute la rambursare trebuie raportate. RPfinal distinct de raportarea postimplementare.','Calendar RP–CR corelat, termene de colectare parteneri anterioare, dovezi activitate/indicator și validare manager.')
a('A44-10','Grup țintă și indicatori','Art7/13; cerere și plan monitorizare','Manual4.1.2; formulareMySMIS','GSCS3.7–3.8; bareme5.3.5','Înscriere și semnături, date de intrare păstrate, actualizarea sprijinului/ieșirii/rezultatelor. Reintrarea nu permite rescrierea istoricului inițial. Registrele interne nu substituie formulareleMySMIS.','Corelați registrele7.5 cu formularul oficial și reprezentarea legală a copilului; roluriGDPR, acces și corecții trasabile.')
a('A44-11','Dovezi costuri simplificate','Art4 eligibilitate; art6','Manual3 introducereSCO; anexa3documente','GSCS5.3.5 ED01/ED02 și15%indirecte','Baremele nu se transformă arbitrar în costreal și nu se fracționează fără baza specifică; se probează condițiile/unitățile prevăzuteGSCS. Documentelecontabile generale deSCO nu înlocuiesc dovadaunității eligibile.','Separare dosarecopil-lună de costurile reale și personal; verificareED01/ED02 pe lună și sursă de finanțare.')
a('A44-12','Achiziții înainteaCR/CP','Art7,9,12','Manual3.7; Instr11 modulAchiziții','Anexa4 art3–4,11; GSCS7.3','Dosarul achiziției se încarcă în modulAchiziții cu cel puțin10zile înainte deCR/CP, inclusiv achiziția directă și excepțiile indicate de manual. Acest text nu spune10zilelucrătoare; se distinge deRP.','Completați planul7.5 cu dataîncărcării, estimare, net/TVA, lot/metodă, oferte, conflicte, recepție; verificați cerințele pe fiecare regim UAT/ONG.')
a('A44-13','Personal public extern organigramei','Art7/10; Legea153 șiHG234 aplicabile','Manual4.4.2.2','GSCS7.4; Anexa4art7','Dosarul selecției și declarațiile de conflicte ale comisiei se transmit odată cuCRcare include primele costuri. Verificarea OI anticipată este o opțiune, nu condiție universală suplimentară.','Nominalizări, actpost, concurs, fișăpost, CV, temei salarial, pontaj cumul proiecte/acelașiangajator; nu copiați Instr12universități.')
a('A44-14','Acte adiționale','Art10(1)–(9)','Manual4.4/4.4.1; Instr11Contractare','Anexa4art7; GSCS10','Modificarea se solicită justificat cu cel puțin30zile înainte de data urmărită; aprobarea și semnarea ultimei părți determină intrarea învigoare. Nu se repară retroactiv schimbarea condițiilor care au permis selecția.','Registru schimbăriimpact eligibilitate/scor/buget; cerere inițialăMySMIS/deblocare, memoriucomparativ, actaprobat, actualizarebuget/grafic.')
a('A44-15','Notificări și buget FSE+','Art10(11),(15)','Manual4.4.2.2; Instr11','Anexa4art7','LaFSE+, transferul între articole/subcategorii în aceeași categorie este pe notificare CUaprobare, conform manualului, spre deosebire de excepția generală pentru alte fonduri. Între categorii:limita10%și condițiile textului; depășirea cere traseul corespunzător.','Nu considerați editareaExcel autorizare bugetară. Matrice tipmodificare–aprobator–preaviz–dataefectivă; praguri verificate cumulativ potrivit contractului.')
a('A44-16','Indicatori și recuperări','Art7 plăți nedatorate; art12(5),13; OUG66/OUG133','Manual4.4; anexa19metodologieindicatori','Anexa4art3,4; GSCS11','Reducerea indicatorilor/GT poate reduce finanțarea; nu se coboară sub condițiile inițiale de eligibilitate/scor. Plăți nedatorate:art7 cere5zile lucrătoare. CP nejustificate/neeligibile:art12(5) general cere5zile, dar Anexa4art4(c) descrie15zile înaintea deciziei și30zile până la executorialitate. Se reconciliază clauza/temeiul aplicabil, fără promisiunea unui termen universal15zile.','Registru separat nereguli/restituiri cu temei, datacomunicării și termenul notificat; verificați diferența general/specific/normă, cereți lămurire laAM dacă rămâne materială. Nu estimați arbitrar reducerea pentru fiecare indicator.','DIFERENTA_TERMENE_DE_RECONCILIAT')
a('A44-17','Arhivare','Art7(9)–(10); art82Reg1060','Manualcap5','Anexa4obligații; GSCS11','Documentele se păstrează până la termenul mai târziu dintre închiderea programului și expirarea obligației de durabilitate/sustenabilitate; minimum5ani de la31decembrie anul ultimei plățiAM. Termenul poate fi întrerupt conform normei. Arhivarea nu se încheie automat după3ani.','Nomenclator/dosarepepartener,originale,electronicconformlegii,accescontrolat,backup,locarhivă; termenconcret dupăplatafinală și notificărileAM.')
a('A44-18','Continuitate și data de referință','Art2(6):FSE+perioadăde laplatafinală','Manual4.3:postimplementare imediat dupăfinalimplementare','GSCS3.18:minimum3ani dupăfinalizare','Cele trei texte cer reconcilierea momentului inițial. Planul trebuie să asigure continuitate de la finalul implementării și să acopere termenul contractual calculat de la plata finală dacă această clauză este păstrată. Nu se reduce obligația la3ani fără a acoperi decalajul.','Includeți înOPEX coloane finalimplementare/platăfinală estimată/perioadăintermediară/termencalendaristic; confirmați clauza exactă la contractare sauAM dacă diferența persistă.','DIFERENTA_DE_RECONCILIAT_A33_A44')
a('A44-19','Active și postimplementare','Art7bunuri șiart2durabilitate','Manual4.3,4.1.3','GSCS3.18servicii; Anexa4obligații','Serviciile și activele sunt menținute conform scopului și rețelei/asumărilor; se raportează postimplementare și se permite verificarea ex-post. Nu se confundă costulsubset7.7cu totalul necesar.','Operatori,responsabilpermanent,bunurilocuri,mentenanță/OPEXcomplet,sursălegală,HCL/acorduri și raportanual conform graficului.')
a('A44-20','Obligații vizibilitate','Art8(18) completatOrdin714/2025; Reg1060art50','Manual4.9','GSCSvizibilitate/7.5A41','Materialelecomunicare pot fi cerute de instituțiileUE; licența cerută și drepturile preexistente trebuie asigurate. Nerespectarea cerințelor după solicitarea remedierii poate atrage diminuarea prevăzută.','Înbrief/contract furnizor includeți drepturile deutilizare necesare; verificați produsele planului și dovezile, fără dublareaindirectelor.')
fields=list(rows[0]);
with (o/'Matrice_A44_contract_manual_GSCS.csv').open('w',encoding='utf-8-sig',newline='')as f:
 w=csv.DictWriter(f,fieldnames=fields,delimiter=';');w.writeheader();w.writerows(rows)
intro='''MATRICE A44 — CONTRACT, MANUAL ȘI CONDIȚII SPECIFICE
07.10.2026 | Lectură orientată pe obligațiile de implementare

Au fost citite integral Instrucțiunile10(partea de aprobare),11 și12, secțiunile relevante din manualulv5 și din contractul general consolidat17.04.2025, confruntate cu Anexa4contractspecific șiGSCS. Nu se declară lectura integrală a209pagini incluzând toate anexele manualului. Instr9este istoric, înlocuită de10. Instr12este neaplicabilă direct parteneriatuluiUAT–ONG. Instrucțiunile completareCF au fost inventariate; validarea completă a cererii rămâne separată.

Contractul local270845 era formădebază. Copia296187 recuperată separat de coordonator conține notelemodificării din17.04.2025; meniulunei pagini nu este dovadaactualizării corpului. Se folosește textulconsolidat pentru această matrice și se verifică din nou la contractare. Manualv5nu derogă dela lege/contract. Precizările de aici nu constituie contractul semnat sau dovadă de conformare a beneficiarului.

Diferență de rezolvat: momentul de referință al sustenabilității dinGSCS/manual(finalimplementare) și contractulgeneral(platăfinală). Până la stabilirea clauzei semnate, asigurați continuitatea și includeți decalajul înplanificare; nu se scurtează unilateral obligația. Arhivarea are termen distinct, de minimum5ani conformart7și poate dura mai mult.

Surse oficiale: https://legislatie.just.ro/Public/DetaliiDocument/296187 ; https://oirvest.ro/wp-content/uploads/Manualul-beneficiarului_decembrie-2025_versiunea-5.docx ; https://oirvest.ro/wp-content/uploads/Instructiunea-nr.-10.pdf ; https://oirvest.ro/wp-content/uploads/Instructiunea-nr.-11.pdf ; https://oirvest.ro/wp-content/uploads/Instructiunea-nr-12.pdf . Ghidul șiAnexa4sunt în arhiva surse_existente.

'''
body=intro+'\n\n'.join('\n'.join(f'{k}: {v}'for k,v in x.items())for x in rows)
(o/'Matrice_A44_contract_manual_GSCS.txt').write_text(body,encoding='utf-8')
(o/'Matrice_A44_contract_manual_GSCS.html').write_text('<!doctype html><meta charset="utf-8"><title>Matrice A44</title><style>body{font:15px/1.55 system-ui;margin:30px}table{border-collapse:collapse}td,th{border:1px solid #aac;padding:10px;vertical-align:top}p{max-width:1100px}</style><h1>Matrice A44 — 20 controale</h1><p>'+html.escape(intro).replace('\n','<br>')+'</p><table><tr>'+''.join('<th>'+k+'</th>'for k in fields)+'</tr>'+''.join('<tr>'+''.join('<td>'+html.escape(x[k])+'</td>'for k in fields)+'</tr>'for x in rows)+'</table>',encoding='utf-8')
files=[p for p in o.iterdir()if p.is_file() and (p.name.startswith('Matrice_A44') or p.name.startswith('Ordin2041_consolidat') or p.name in ['Manual_beneficiar_v5_dec2025.docx','Instructiunea_10_2025_Manual_anexe.pdf','Instructiunea_11_2025.pdf','Instructiunea_12_2026.pdf'])]
(o/'Manifest_matrice_A44.json').write_text(json.dumps([{'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}for p in files],ensure_ascii=False,indent=2),encoding='utf-8')
print('A44 matrix generated:20controls.')
