from pathlib import Path
import csv,json,html,collections,hashlib,re
root=Path(__file__).resolve().parent; out=root/'7.1 Audit iterativ'
rows=list(csv.DictReader((out/'Runda1_registru.csv').open(encoding='utf-8-sig'),delimiter=';'))
by={r['ID']:r for r in rows}
def update(id,**kw):by[id].update(kw)
update('A01',Constatare='Registru juridic actualizat: 30/35 surse cu copie locală; cinci surse UE restante. Cele trei strategii suplimentare sunt recuperate. Arhiva nu este încă exhaustivă pentru toate trimiterile.',Status='PARTIAL_REMEdIAT_DOCUMENTARE',Nota='GDPR ANSPDCP recuperat; disponibilitatea fișierului nu certifică lectura integrală ori forma consolidată. Matricea juridică inventariază 94 clustere de cerințe, nu declară conformitate completă.')
update('A02',Status='PARTIAL_REMEDIAT_MATRICE',Nota='7.2 oferă matrice juridică și limitele versiunilor; rămân consolidări, anexe și trierea trimiterilor. Nu se confundă cele 955 fragmente candidate cu obligații juridice validate.')
update('A03',Nota='Confirmarea beneficiarului este păstrată. 8.1: șase dosare proiect, 72 poziții documentare, încă de primit/verificat. Nu se repetă întrebarea dacă EcoWarriors există.')
update('A12',Status='PROCEDURA_REDACTATA_VALIDARE_NECESARA',Nota='7.5 A12: filtre, prioritizare vulnerabilitate, contestații, unicitate, date și registre. Se verifică pe populația reală și se aprobă de entitățile competente; nu dovedește recrutare efectuată.')
update('A13',Status='PARTIAL_REMEDIAT_DATE_PUBLICE',Nota='HCL235/2026, citit vizual integral4pagini:12PJ în rețea, dintre care9 cu nivel timpuriu explicit(6publice+3private). Acordurile, operatorii efectivi, capacitățile și20locații nu rezultă automat din rețea.')
update('A14',Nota='Ipoteza fixă60grupe a fost eliminată din XLSX. Calculul necesar88grupe este condiționat de simultaneitatea1260preșcolari/224CES și limita22cu reducere3/CES; nu certifică rețeaua ori ilegalitatea scenariului.')
update('A21',Constatare='Controlul orientativ al personalului de îngrijire a fost corectat:35lei net/oră este screening, nu încadrare legală confirmată; netul diagnostic este circa25,75.',Status='INCHIS_REMEDIERE_MODEL',Nota='Formula cost/(1+CAM)×factor net corectă pentru ipotezele folosite; încadrarea individuală, deducerile și salariul legal rămân laA20. GSCS p37 permite personal operațional de îngrijire/sprijin/administrativ în servicii noi/extinse ca direct. Administrația generală proiectului se separă; nu eliminăm automat linia după COR/titlu.')
update('A24',Sursa='GSCG consolidat secțiunea3.8, paragrafele privind rezonabilitatea costurilor; GSCS bareme',Actiune='Minimum2oferte pentru costurile aplicabile, cu excepția echipamentelor/serviciilor cu plafoane GSCG; documentați prețurile individuale comparabile, specificații și studiul de piață. Baremele urmează regimul lor specific.',Nota='ERATĂ RUNDA1: formularea că două oferte sunt doar recomandare era greșită pentru costurile cărora li se aplică regula. Corectată în7.5A42 și în acest registru. Referința corectă este3.8, nu3.3.')
update('A29',Constatare='Calendar lunar propus în24luni ian2027–dec2028: standardMIN9luni, standardMAX12luni în doi ani școlari, complementar10luni.',Status='CALENDAR_REDACTAT_VALIDARE_NECESARA',Nota='7.5 registrul14 verificat:MAXsept2027–iun2028 plussept–oct2028;MINoct2027–iun2028;complementarsept2027–iun2028. Contractarea, vârstele, cohortele, autorizările și continuitatea rămân de validat; nu presupunem automat același copil eligibil toate12luni.')
update('A30',Constatare='EECO18MAX revizuit la18, condiționat de9PJ relevante×2anișcolari. PJ și structurile nu se numără dublu.',Status='MODEL_CORECTAT_DOVEZI_UNITATI_NECESARE',Actiune='Validați operatorii participanți, acordurile și dovada sprijinului pentru fiecare PJ/an. Clarificarea AM este necesară numai dacă speța reală nu poate fi soluționată prin definiția ghidului.',Nota='HCL235 nu este acordul celor9PJ. Numărul18 nu este indicator deja realizat. MIN2 rămâne condiționat de sprijin în ambii ani.')
update('A31',Status='METODA_REDACTATA_ALOCARI_DE_VALIDAT',Nota='7.5A31 și registrul11 justifică fiecare linie/cheie; sume147100/3576000 identice cu modelul. Marcajele100% sunt condiționate de conținutul efectiv, nu garantate prin apartenența GT. Tema10 rămâne de fundamentat strategic.')
update('A32',Status='PROCEDURA_REDACTATA_VALIDARE_NECESARA',Nota='7.5A32: monitorizare, alerte, intervenții, dovezi de ieșire și responsabilități. Pragurile interne de absență nu sunt reguli inventate de rambursare. 58/1452 rămân ținte, nu rezultate.')
update('A33',Status='DEVIZ_PARTIAL_ANGAJAMENTE_NECESARE',Nota='7.7 anualizează corect numai5componente complementare:312960lei/an/serviciu;938880lei/3ani;5servicii4694400lei/3ani. Lipsesc costurile integrale, normarea și acte de alocare. Nu închide criteriul4.2; fondurile sunt declarate asigurate.')
update('A34',Status='PROCEDURI_PARTIALE_VALIDARE_NECESARA',Nota='7.5: fluxuriGDPR, temeiuriart6/9, acces limitat, minimizare și registre; GDPR local disponibil. Politicile aplicate pe locații, siguranța copiilor, evaluarea riscurilor și aprobările nu sunt încă probate.')
update('A36',Constatare='Experiența și indicatorii istorici sunt declarați, dar actele pentru punctaj3.6/3.7 nu au fost verificate.',Actiune='Verificați dosarele8.1:3.6 permite lider≥12luni SAU lider și fiecare partener≥6luni. Verificați indicatorii contractuali și realizați validați pentru3.7, fără medie inventată sau transfer automat al ferestrei3ani din eligibilitateaONG.',Nota='Maximul real poate fi97/100 ori altul după probe. 100este plafon teoretic; nu scor câștigat.')
update('A40',Status='LIMITARE_DOCUMENTATA_CONTROALE_VERIFICATE',Nota='172formule/fișier; Verificari27–30 verifică multipli12/24 și luni≤durată; E32 avertizează parametrizarea parțială. Toate valorile actuale trec. Editarea parametrilor cere reconfigurare și audit, nu constituie optimizator automat.')
update('A41',Status='PLAN_REDACTAT_APROBARE_NECESARA',Nota='7.5A41/registrul12: produse, responsabil funcțional, calendar; alocări interne2000/20000 incluse în indirecte, fără adăugare la total. Manualul aplicabil și responsabilul nominal/aprobările rămân de verificat.')
update('A42',Status='PROCEDURA_REDACTATA_COMPLETARE_NECESARA',Nota='7.5A42/registrul13: regim entități, loturi, conflicte, recepție, oferte1/2, excepții și prețuri individuale. Costuri nete/TVA/CPV/metodă/estimări încă de completat după inventar și piață. Nu este procedură de achiziție deja desfășurată.')
def add(id,cls,rub,title,source,action,proof,owner='Jurist și manager'):
 r={k:'' for k in rows[0]};r.update(ID=id,Prioritate='P1',Clasa_rezolvare=cls,Moment='Înaintea validării finale',Rubrica=rub,Constatare=title,Sursa=source,Actiune=action,Responsabil=owner,Dovada_inchidere=proof,Status='DESCHIS');rows.append(r)
add('A43','BENEFICIAR','R4','Limita numărului de proiecte în același apel trebuie verificată separat de metoda40%AFN.','7.2J-004;GSCG','Declarație și verificare portofoliu depuneri/roluri în apel; distingeți limita de5depuneri de limita2contractePEO aferentă metodei40%.','Portofoliu complet și test juridic documentat')
add('A44','ECHIPA','R1','Contractul general complet, manualul beneficiarului și instrucțiunile aplicabile nu sunt încă reconciliate integral cu contractul specific.','7.2J-093','Recuperați versiunile aplicabile și mapați raportarea, cererile, păstrarea actelor, modificările, recuperările și obligațiile postimplementare.','Registru trimiteri/versiuni, analiză și clauze aplicabile; fără termen contractual inventat')
for r in rows:
 if r['Status']=='PARTIAL_REMEdIAT_DOCUMENTARE':r['Status']='PARTIAL_REMEDIAT_DOCUMENTARE'
with (out/'Runda2_registru.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.DictWriter(f,fieldnames=list(rows[0]),delimiter=';');w.writeheader();w.writerows(rows)
rubric=[('R1','Surse și versiuni','0,5','Nucleul documentar disponibil. Rămân5surseUE, consolidări și trimiteri neacoperite.'),('R2','Eligibilitatea entităților','0,5','ArhitecturaUAT–ONG este admisibilă; actele experienței/statutului nu sunt încă verificate.'),('R3','Parteneriat și selecție','0','Nu există încă dosar formal selecție/acord asumat.'),('R4','Capacitate financiară formală','0,5','Model40% calculabil; portofoliu/CAF/excluderi și acte încă de verificat.'),('R5','Nevoi și grup țintă','0','Procedură redactată; datele reale și metodologia aprobată/coerentă cu populația nu sunt validate.'),('R6','Fezabilitate educațională legală','0,5','Formele și restricțiile sunt analizate; operatori/capacitate/CES/autorizații nevalidate.'),('R7','Integritatea numerică','1','Recalcul independent4fișiere,172formule fiecare, zero neconcordanțe în testele efectuate; limitarea parametrizării declarată.'),('R8','Costuri, resurse și personal','0,5','Model de roluri și controlnet îmbunătățit; normare/prețuri/TVA și fundament salarial neprobate.'),('R9','Cerere și maxim de punctaj real','0,5','Grila și procedurile sunt tratate; cererea finală și probele pentru punctaj nu sunt complete.'),('R10','Continuitate și protecții','0','Există proceduri și devizsubset; lipsesc aprobări/devizintegral/dovezi aplicate pe locații.')]
text='''AUDIT ITERATIV — RUNDA 2
7 octombrie2026 | Municipiul Sebeș lider; ROMANIAN SOUL ENTITY partener

NOTA INTERNĂ DE PREGĂTIRE:4,0/10. VETO PENTRU VALIDAREA FINALĂ:ACTIV.

Aceasta este o verificare documentară de proiectare, distinctă de evaluarea oficială a grantului. Nu declară neeligibilitatea definitivă a entităților: identifică probele și deciziile fără de care eligibilitatea, fezabilitatea și punctajul nu pot fi certificate. Fondurile proprii sunt confirmate de utilizator; disponibilitatea lor nu este repusă în discuție și nu se plafonează bugetul după bilanțurile istorice.

Rubrica rămâne aceeași ca în Runda1:10controale, fiecare cu două subteste de0,5puncte. Nu schimbăm pragurile pentru a crește artificial nota. Redactarea procedurilor și îmbunătățirea modelului reprezintă progres real, dar nu înlocuiesc aprobarea lor, datele beneficiarului și dovezile cerute de subtestele încă deschise. Nota rămâne4,0/10. Nu acordăm10/10 condiționat. Auditul poate ajunge la10/10 și cu maxim demonstrabil97/100la grant dacă limita istorică este documentată și toate condițiile obligatorii sunt închise.

RUBRICA ȘI DOVEZILE
'''
text+='\n'.join(f'{a} {b}: {c}/1. {d}'for a,b,c,d in rubric)
text+='''

VERIFICAREA BUGETELOR
Au fost citite în regim fără modificare toate cele patru XLSX și recalculate independent cantități×tarife, cele33linii, repartizarea lider/ONG, personalul,15%indirecte, contribuțiile, plafoanele și raportările principale. S-au verificat formulele diagnosticului net și controalele27–30. Fiecare fișier are172formule, fără erori memorate și fără neconcordanțe în testele efectuate. Nu pretindem evaluarea exhaustivă a oricărei editări viitoare: modelele sunt parțial parametrizate. Datele exacte și hashurile sunt în Runda2_Verificare_independenta_XLSX.json.
MIN:1.058.641,80lei; directe1.002.538,80; indirecte56.103,00. Lider951.968,80; ONG106.673,00. Contribuții19.039,38lei laONG0% sau21.172,84lei laONG2%. Marja peste pragul minim este1.703,40lei.
MAX:26.272.446,00lei; directe25.707.996,00; indirecte564.450,00. Lider24.403.606,00; ONG1.868.840,00. Contribuții488.072,12lei laONG0% sau525.448,92lei laONG2%. Marja sub plafon este19.554,00lei.
Contribuția voluntarăONG2% nu aduce punctaj suplimentar conform grilei analizate. Nici apropierea de plafon nu justifică o cheltuială.
EECO18 este2înMIN și18înMAX, verificat în fișiere. MAX18reprezintă țintă condiționată9PJ×2anișcolari, nu9participări deja confirmate. Pentru fiecare PJ și an este necesară dovada sprijinului eligibil, fără multiplicarea structurilor arondate.
Tariful net orientativ este costtotal/(1+CAM)×0,585, cu CAM0,0225. Factorul este ipoteză fiscală simplificată; situația individuală poate diferi. Pragul35lei pentru îngrijire este screening, nu plafon legal certificat pentru orice încadrare.

REMEDIERI ȘI CONTROALE NOI
1. A21: rectificare diagnostic îngrijire; A40: controale multipli12/24, luni≤durată și avertizare de parametrizare. A39, contribuțiile vechi din evaluare, rămâne închisă.
2. A14: eliminată dimensionarea fixă60grupe din model. Dacă1260preșcolari și224CES sunt simultan, ceil((1260+3×224)/22)=88este o condiție agregată necesară; repartiția, vârstele, ceilalți copii și derogările se analizează individual. Nu demonstrează existența88grupe și nu transformă singură scenariul într-unul ilegal.
3. 7.5: metodologia selecției, protecția datelor, retenția/monitorizarea, alocarea temei05, vizibilitatea, achizițiile și calendarul sunt redactate;15registreCSV. Sunt proceduri propuse, fără dovadă de aprobare ori implementare. A12/A29/A31/A32/A41/A42 rămân parțial deschise.
4. Registrele11/12/14 au fost controlate: tema05=147.100/3.576.000lei; vizibilitate internă=2.000/20.000lei în indirecte; calendarul conține9luni standardMIN,12standardMAX și10complementar. Alocările temei05necesită validarea conținutului efectiv și reducere dacă folosirea este mixtă.
5. 8.1:șase dosare individuale,72poziții de documente. EcoWarriors este confirmat de beneficiar ca implementare/produse și existență de contract/raportfinal acceptat. Datele și actele vor fi verificate; nu este o experiență inventată și nu este încă dovadă juridică examinată.
6. 7.7:recalcul corect al subsetului recurent complementar:312.960lei/an/serviciu și938.880lei/3ani;5servicii=1.564.800lei/an și4.694.400lei/3ani. Nu include integral operarea, normarea, concediile, toate funcțiile și inflația. Nu închide sustenabilitatea3ani/criteriul4.2.

ERATE ȘI CLARIFICĂRI JURIDICE
A24dinRunda1 conținea o formulare prea slabă: pentru costurile aplicabile, minimum2oferte este cerința GSCG3.8, cu excepțiile acolo prevăzute pentru echipamente/servicii cu plafoane. Ofertele trebuie să permită prețul individual pe tip de bun/serviciu; un pachet eterogen cu preț global nu ajunge. Studiul de piață și justificările se păstrează; acestea nu înlocuiesc procedura legală de achiziție. Procedura7.5 a fost corectată și verificată. Referința3.3menționată intermediar de auditor era eronată; referința corectă este3.8.
GSCS5.3.2p37prevede explicit personalul operațional de îngrijire/sprijin/administrativ al serviciilor noi/extinse în categoria directă. Regula specifică este analizată distinct de administrația generală a proiectului, indirectă. J094juridic a fost corectat. Nu există temei să eliminăm automat îngrijirea numai după titlu/COR. Rămân de probat postul real, sarcinile, încadrarea și evitarea suprapunerii cu baremul. Eventuala reclasificare este scenariu condiționat de constatarea unor atribuții generale, nu reducere impusă acum.
3.6acordă maximum1punct:lider≥12luni relevante SAU lider și fiecare partener≥6luni. 3.7necesită indicatorii istorici validați; nu inventăm medie între indicatori/proiecte și nu transferăm automat fereastra3ani din eligibilitateaONG. Golurile textuale ale pragurilor se clarifică numai dacă sunt material relevante.

SURSE CITITE ȘI LIMITELE LECTURII
Au fost analizate ghidul specific final, GSCG consolidat, grilele și anexele relevante, modelul financiar și artefactele concept/evaluare/juridic/educație/SWOT/proceduri/checklist. În această rundă s-au verificat matricea juridică94clustere, nota iterației2, checklistul experienței și procedurile complete. Matricea este inventar de cerințe, nu94confirmări de conformitate.
Registrul juridic este30/35copii locale, cu5documenteUE restante; GDPR87pagini a fost recuperat de jurist și citit punctual pentru articolele relevante, nu integral. Cele3strategii(112/123/122pagini) sunt recuperate și au fost citite punctual de specialist, nu integral. 7PDFdin7.3au fost validate tehnic cuhash/pagini. Auditorul a citit vizual integral HCL235/2026,4pagini; HCL50/78/242șiSIDU au fost analizate pe fragmente relevante, nu toate anexele/inventarele. Raportul nu pretinde că toate documentele descărcate au fost citite integral.
HCL235arată12PJ în rețea și9cu nivel timpuriu explicit. Cele6publice și3private nu devin automat parteneri ori operatori finanțați deUAT. HCL50/78/242arată investiții/dotări de verificat în inventar; nu demonstrează automat dublă finanțare. Capacitatea, proprietatea, personalul și traseul plătitor/angajator/operator rămân esențiale.

CONSTĂTĂRI CARE CER ÎNCHIDERE
Eligibilitate:acteleEcoWarriors și statut, selecțieONG/acord, portofoliu pentru40%AFN și limite de participare, CAF/excluderi, bilanțuri conforme. Fondurile asigurate nu închid aceste teste formale.
Fezabilitate:nevoia locală și copii unici pe vârste/cohorte, vulnerabilitate/romi/CES fără presupuneri,9PJparticipante dacă se păstrează18unități-an,1/5servicii complementare, avize, calendar real și normare completă. Cele300locuri de mobilier,20locații,15camereCES și120persoane formate trebuie fundamentate individual.
Buget:inventarulPNRR și alte finanțări, oferte/prețuri aplicabile,TVA, temei salarial și calificări, atribuțiile entității care angajează/plătește, numărul real de luni-copil. MINare marjă mică; orice ajustare relevantă impune revalidarea pragului minim/percopil fără cheltuieli artificiale.
Cerere/punctaj:proceduri aprobate și adaptate, dovezi tematice și strategice, indicatori reali, anexe/cerere asumate, deviz integral și angajamente de continuitate. Punctajul100nu este câștigat prin ținte introduse înExcel; maximul posibil se stabilește după probe.
Echipă:terminarea arhivei/versiunilor și contractului general/manualului/instrucțiunilor; transpunerea procedurilor în cererea finală pe datele primite; controlul versiunilor între documente. Textele și calculele controlabile au fost ameliorate, dar redactarea nu substituie documentele externe.
InterpretăriAM:regimul concret al baremului versus finanțarea publică existentă, eventualele ambiguitățiEECO18, agregarea indicatorilor istorici și referințaA1.3din grilă. Se utilizează spețe concrete; nu s-a transmis nicio solicitare externă în numele beneficiarului.

REGULA RUNDEI URMĂTOARE
Registrul păstrează42constatări inițiale și adaugăA43(portofoliu depuneri, separat de40%AFN) șiA44(instrumente contractuale și implementare). Două remedieri sunt închiseA21/A39; A40este limitare acceptată explicit, restul necesită dovezile descrise. Nu se consideră închise procedurile doar pentru că există un fișier.
Se reia auditul după primirea actelor și deciziilor care schimbă rezultatul: dosar experiență, acorduri/date operatori/GT, inventare și piață, alocări juridice și sustenabilitate. Pentru fiecare modificare se actualizează constatarea, dovada, data și hashul fișierului. Repetarea aceleiași runde fără informații noi nu poate produce onest10/10.
'''
text+='\n\nREGISTRU COMPLET — RUNDA2\n'
text+='\n\n'.join(f"{r['ID']} | {r['Prioritate']} | {r['Clasa_rezolvare']} | {r['Status']}\n{r['Constatare']}\nAcțiune: {r['Actiune']}\nDovadă necesară: {r['Dovada_inchidere']}\nActualizare: {r['Nota']}"for r in rows)
text=re.sub(r'(?<=[a-zăâîșț])(?=\d)', ' ', text)
text=re.sub(r'(?<=\d)(?=[A-Za-zăâîșț])', ' ', text)
text=re.sub(r'(?<=[:;])(?=[A-Za-zăâîșț0-9])', ' ', text)
for a,b in {'ArhitecturaUAT':'Arhitectura UAT','controlnet':'control net','devizsubset':'deviz subset','devizintegral':'deviz integral','surseUE':'surse UE','laONG':'la ONG','eligibilitateaONG':'eligibilitatea ONG','regimulGDPR':'regimul GDPR','depuneri/roluri':'depuneri / roluri','criteriul4':'criteriul 4','HCL235':'HCL 235','directe25':'directe 25'}.items():text=text.replace(a,b)
(out/'Runda2_Raport.txt').write_text(text,encoding='utf-8')
body=''.join('<p>'+html.escape(p).replace('\n','<br>')+'</p>'for p in text.split('\n\n'))
(out/'Runda2_Raport.html').write_text('<!doctype html><html lang="ro"><meta charset="utf-8"><title>Audit independent — Runda2</title><style>body{font:16px/1.6 system-ui;max-width:1100px;margin:40px auto;padding:0 24px;color:#142b34}p{margin:1.1em 0}p:first-child{font-size:26px;font-weight:700}p:nth-child(2){background:#fff1cc;padding:16px;border-left:5px solid #ba7800}@media print{body{font-size:11px;margin:15px}p{break-inside:avoid}}</style>'+body+'</html>',encoding='utf-8')
manifest=[]
for p in sorted(out.glob('Runda2*')):
 if p.is_file() and p.name!='Runda2_Manifest.json':manifest.append({'file':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size})
(out/'Runda2_Manifest.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False),encoding='utf-8')
print(json.dumps({'findings':len(rows),'classes':dict(collections.Counter(r['Clasa_rezolvare']for r in rows)),'score':4,'files':len(manifest)},ensure_ascii=True))
