from pathlib import Path
import json,csv
R=Path(r'\\192.168.100.169\Comun\00.Roboti\iDempiere\Documentatie\BI_iDempiere')
L=Path(__file__).parent
rows=list(csv.DictReader((R/'02_Matrice/matrice_64_functii.csv').open(encoding='utf-8-sig')))
src=json.loads((R/'06_Surse_oficiale/surse.json').read_text(encoding='utf-8'))
# Each module is evaluated for its own documented role, not as a complete BI suite.
modules=[]
def m(name,version,license,role,source,yes='',partial='',kind='Nativ',note=''):
 modules.append(dict(name=name,version=version,license=license,role=role,source=source,yes=yes.split(','),partial=partial.split(','),kind=kind,note=note))
m('Application Dictionary','iDempiere 13','GPL-2.0','Metadate, procese și parametri','S18','Metadate,Parametri','API')
m('Report View','iDempiere 13','GPL-2.0','Vederi de raport și selecția datelor','S18 S27','SQL,Parametri','Raport tabular')
m('Print Format','iDempiere 13','GPL-2.0','Layout, grupări, totaluri și formulare','S18','Raport paginat,Raport tabular,Export PDF','Export tabelar')
m('Rapoarte din ferestre','iDempiere 13','GPL-2.0','Raportare contextuală ERP','S18','Raport tabular,Parametri,Drill-down ERP','Export tabelar')
m('Chart','iDempiere 13','GPL-2.0','Grafice configurate prin AD_Chart și datasource SQL','S18','Grafice,SQL','Dashboard')
m('Dashboard Content','iDempiere 13','GPL-2.0','Portleturi și preferințe personale','S18','Dashboard,Preferințe','Grafice,Embedding')
m('Performance Goal','iDempiere 13','GPL-2.0','Ținte, progres și restricții','S18','Ținte KPI','Dashboard')
m('Performance Measure','iDempiere 13','GPL-2.0','Măsuri, calcule și realizări','S18','Calcul KPI','SQL')
m('Ratio și Benchmark','iDempiere 13','GPL-2.0','Rapoarte între măsuri și etaloane','S18','Calcul KPI,Ținte KPI')
m('Color Schema','iDempiere 13','GPL-2.0','Culori pentru praguri KPI','S18','Praguri vizuale')
m('Alert','iDempiere 13','GPL-2.0','Reguli de excepție și destinatari','S18','Alerte,SQL','Email')
m('Scheduler și arhivare','iDempiere 13','GPL-2.0','Procese programate și arhivare','S18','Programare,Arhivare','Email')
m('Financial Report','iDempiere 13','GPL-2.0','Linii, coloane, ierarhii și formule contabile','S18','Raport financiar,Raport tabular,Parametri,Calcul KPI','Export PDF,Buget-realizat')
m('Report Cube','iDempiere 13','GPL-2.0','Sumarizare Fact_Acct, fără server MDX general','S18','Precalcul contabil','Raport financiar')
m('Jasper core','iDempiere 13; engine de inventariat','GPL-2.0 ERP; motor separat','Template Jasper și rapoarte parametrizate','S28','Raport paginat,Parametri,Export PDF','Export tabelar')
m('Info și Quick Info','iDempiere 13','GPL-2.0','Interogare contextuală și navigare ERP','S18','Parametri,Drill-down ERP','Raport tabular,SQL')
m('Rapoarte operaționale ERP','iDempiere 13','GPL-2.0','Vânzări, cumpărări, stocuri, producție, creanțe','S18','Raport tabular,Parametri,Drill-down ERP','Raport financiar,Export tabelar')
def p(name,version,license,role,source,yes='',partial='',note=''):m(name,version,license,role,source,yes,partial,'Extensie',note)
p('BX Metabase','1.0.3; manifest ERP 11; wiki 8.2','GPL-2.0 (plugin); AGPL (BI)','Metabase în form, dashboard, câmp, Quick Info și raport','S20','Embedding','Dashboard,Parametri', 'Compatibilitatea cu Eva 13 nu a fost testată. Transmiterea AD_Client_ID nu demonstrează izolarea pe organizații.')
p('ChartMaker','3.1; proiect istoric','GPL-2.0','Designer de grafice','S21','Grafice','Dashboard','Mentenanța și compatibilitatea trebuie reverificate.')
p('Jasper Reports Red1','Neconfirmată','De verificat în distribuție','Integrare/extensie rapoarte Jasper','S22','Raport paginat','Parametri,Export PDF','Distinct de Jasper core. Nu este necesară instalarea duplicată fără inventar.')
p('FreiBier Jasper starter','Neconfirmată','De verificat în distribuție','Starter Jasper, resurse și parametri de context','S23','Raport paginat','Export PDF,Export tabelar,Parametri')
p('Cash Forecast','1.0.1a sursă; wiki ERP 7.1','GPL-2.0','Proiecție încasări/plăți din documente','S25 S30','Cash-flow','Raport tabular','Nu echivalează cu forecast statistic ML.')
p('Kanban','Ramură stabilă / v2 beta; tag neconfirmat','GPL-2.0 conform wiki','Board operațional, WIP, swimlanes și sumare','S24','Kanban','Calcul KPI,Drill-down ERP','Versionarea și licența trebuie validate în artefactul ales.')
p('Request Kanban','Neconfirmată','De verificat în repository','Kanban pentru modulul Request existent','https://wiki.idempiere.org/en/Request_Kanban','Kanban','Drill-down ERP','Sursă identificată: https://github.com/ray-idempiere/tw.idempiere.requestkanban . Distinct de Kanban Dashboard general.')
p('AMERPSOFT Financial Report','Neconfirmată','De verificat în repository','Raportare financiară extinsă','S43','Raport financiar','Raport tabular,Parametri')
p('SmallBI','Neconfirmată; sursă inaccesibilă','Neconfirmată','Referință istorică de BI','S45','','','Nu este candidat eligibil fără cod, licență și compatibilitate.')
p('Information Gadget','JPiere; wiki ERP 8.2','De verificat','Gadget informativ și groupware','S26','Dashboard','Comunicare')
p('Broadcaster Dashboard','Neconfirmată','Neconfirmată','Mesaje către utilizatori','S19','Comunicare','','Funcție adiacentă BI; fără calificare OSS confirmată.')
p('EGS Advanced Charts','Anunț 2025; tag neconfirmat','Neconfirmată','Grafice avansate pentru iDempiere','S44','Grafice','Dashboard','Anunțul nu dovedește o distribuție gratuită completă.')
p('Billboard','Neconfirmată','Neconfirmată','Referință de dashboard/gadget','S19','','Dashboard')
p('ZK Charts Demo','Neconfirmată','De verificat inclusiv ZK Charts','Demonstrație vizualizare','S19','','Grafice','Un demo nu certifică dreptul de utilizare gratuită în producție.')
p('Keikai','Neconfirmată','De verificat ediția','Spreadsheet integrat','S19','','Spreadsheet','Nu calificat ca soluție complet gratuită.')
p('Excel Dashboard','Neconfirmată','Neconfirmată','Dashboard de tip spreadsheet','S19','','Spreadsheet,Dashboard')
p('Budgetary Control','Neconfirmată','De verificat','Control bugetar și disponibil','S19','Buget-realizat','Raport financiar')
p('Import Budget','Neconfirmată','De verificat','Încărcare bugete pentru raportare','S19','Import buget','Buget-realizat')
p('Payroll reporting','Distribuție de identificat','Neconfirmată','Familie de rapoarte salarizare','S19','','Raport tabular','Familie, nu un plugin unic verificat.')
p('Geo reporting','Distribuție de identificat','Neconfirmată','Familie de reprezentări geografice','S19','','Geo','Familie, nu un plugin unic verificat.')
features=[('Configurare','Metadate'),('Configurare','SQL'),('Configurare','Parametri'),('Configurare','Preferințe'),('Analiză','Calcul KPI'),('Analiză','Ținte KPI'),('Analiză','Praguri vizuale'),('Analiză','Precalcul contabil'),('Vizualizare','Grafice'),('Vizualizare','Dashboard'),('Vizualizare','Geo'),('Vizualizare','Kanban'),('Vizualizare','Spreadsheet'),('Raportare','Raport tabular'),('Raportare','Raport paginat'),('Raportare','Raport financiar'),('Raportare','Buget-realizat'),('Raportare','Cash-flow'),('Raportare','Import buget'),('Distribuție','Export PDF'),('Distribuție','Export tabelar'),('Distribuție','Programare'),('Distribuție','Alerte'),('Distribuție','Email'),('Distribuție','Arhivare'),('Integrare','Embedding'),('Integrare','Drill-down ERP'),('Integrare','API'),('Integrare','Comunicare'),('Securitate','Izolare Eva 13 testată'),('AI','Configurare AI după profil')]
versions=[['Apache Superset','6.1.0','Apache-2.0','https://github.com/apache/superset/releases/tag/6.1.0','S35 S38-S40'],['Metabase OSS','v0.64.1','AGPL-3.0; embedding are condiții distincte','https://github.com/metabase/metabase/releases/tag/v0.64.1','S06-S09'],['Knowage CE','v9.0.11','AGPL-3.0','https://github.com/KnowageLabs/Knowage-Server/releases/tag/v9.0.11','S10 S37'],['Redash','v26.9.0','BSD-2-Clause','https://github.com/getredash/redash/releases/tag/v26.9.0','S12-S14 S36'],['Lightdash OSS','2.423.2','MIT nucleu; EE exclus','https://github.com/lightdash/lightdash/releases/tag/2.423.2','S15-S17 S41-S42 S50'],['iDempiere','13, reper Eva','GPL-2.0','https://github.com/idempiere/idempiere','S18 S28'],['Eva Accounting','1c039193e0c1626cb03fb8ca37f9980a1703fd0c','Repository propriu; dependințe distincte','https://github.com/cesiroproduction/Eva-Accounting/tree/1c039193e0c1626cb03fb8ca37f9980a1703fd0c','03_Audit_Eva_Accounting']]
data=dict(rows=rows,modules=modules,moduleFeatures=features,versions=versions,sources=src)
(L/'excel_data.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
(R/'01_iDempiere/inventar_module.json').write_text(json.dumps(modules,ensure_ascii=False,indent=2),encoding='utf-8')
(R/'06_Surse_oficiale/versiuni_identificate.json').write_text(json.dumps(versions,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(modules),'modules;',len(rows),'BI functions')
