import requests, json, hashlib, concurrent.futures, re, subprocess
from pathlib import Path
from datetime import datetime, timezone
ROOT=Path(r'C:\Users\User\AppData\Local\Temp\eva-cashflow-20261008\Documentatie\Cash_Flow')
ROOT.mkdir(parents=True,exist_ok=True)
S=[]
def add(id,group,name,url): S.append(dict(id=id,group=group,title=name,url=url))
for i,slug in enumerate(['cash-flow-report','accounting-reports','payment-entry','payment-reconciliation','bank-reconciliation','bank-reconciliation-tool','payment-terms','payment-order','budgeting','multi-currency-accounting','accounting-dimensions','accounts-receivable','dunning','auto-repeat','consolidated-financial-statement']): add('E%02d'%(i+1),'ERPNext',slug,'https://docs.frappe.io/erpnext/'+slug)
for id,group,path in [('E90','ERPNext','frappe/erpnext/develop/license.txt'),('E91','ERPNext','frappe/erpnext/develop/erpnext/accounts/report/cash_flow/cash_flow.py'),('E92','ERPNext','frappe/erpnext/develop/erpnext/accounts/report/cash_flow/cash_flow.json'),('D90','Dolibarr','Dolibarr/dolibarr/develop/COPYING'),('D91','Dolibarr','Dolibarr/dolibarr/develop/htdocs/compta/bank/pre.inc.php'),('G90','GnuCash','Gnucash/gnucash/stable/LICENSE')]: add(id,group,path.split('/')[-1],'https://raw.githubusercontent.com/'+path)
for i,slug in enumerate(['Module_Banks_and_Cash','Module_Double_Entry_Accounting','Module_Customers_Invoices','Module_Suppliers_Invoices','Module_Multicurrency','Module_Loan','Module_Salaries','Module_Direct_Debit','Module_Web_Services_API_REST','Module_MultiCompany','Developer_documentation','User_documentation']): add('D%02d'%(i+1),'Dolibarr',slug,'https://wiki.dolibarr.org/index.php/'+slug)
for i,mod in enumerate(['account','account-invoice','account-payment','account-payment-sepa','account-payment-clearing','account-statement','account-statement-rule','account-statement-ofx','account-statement-coda','account-statement-mt940','account-statement-aeb43','account-budget','account-dunning','account-credit-limit','currency','company','account-invoice-history']):
 for j,page in enumerate(['index.html','design.html','usage.html']): add('T%02d%d'%(i+1,j),'Tryton',mod+' '+page,'https://docs.tryton.org/latest/modules-'+mod+'/'+page)
for id,title,url in [('G01','Manual complet','https://www.gnucash.org/docs/v5/C/gnucash-manual.pdf'),('G02','Ghid complet','https://www.gnucash.org/docs/v5/C/gnucash-guide.pdf'),('G03','Rapoarte','https://www.gnucash.org/docs/v5/C/gnucash-guide/rpt_standardrpts.html'),('G04','Programari','https://www.gnucash.org/docs/v5/C/gnucash-manual/trans-sched.html'),('G05','Descarcare','https://www.gnucash.org/download.phtml')]: add(id,'GnuCash',title,url)
for i,slug in enumerate(['Manual','Cash_Flow_Report_(Report_ID-53248)','Cash_Plan_(Window_ID-53137)','Category:Bank_Cashbook','Plugin:_CashForecasting','Plugin:_Bank_Statement_Matching','Plugin:_BX_Service_Hibiscus','Plugin:_SEPA','Plugin:_PaySelect','Accounting_basics','Payment_Selection_(Window_ID-205)','Payment_(Window_ID-195)','Bank_Statement_(Window_ID-194)','Bank_Statement_Matcher_(Window_ID-302)','Cashbook_(Window_ID-197)','Recurring_(Window_ID-266)','NF1.0_Payment_Batch','NF2.1_Payment_Selection_Improvements','JPIERE-0103:Info_Window_of_Payment_Selection']): add('I%02d'%(i+1),'iDempiere',slug,'https://wiki.idempiere.org/en/'+slug)
for id,title,url in [('P01','CashForecasting manual complet','https://raw.githubusercontent.com/pshepetko/org.idempiere.cashforecasting/master/downloads/CashForecasting_v1.0.1a.pdf'),('P02','CashForecasting licenta','https://raw.githubusercontent.com/pshepetko/org.idempiere.cashforecasting/master/COPYING'),('P03','CashForecasting manifest','https://raw.githubusercontent.com/pshepetko/org.idempiere.cashforecasting/master/META-INF/MANIFEST.MF'),('P04','CashForecasting surse complete','https://codeload.github.com/pshepetko/org.idempiere.cashforecasting/zip/refs/heads/master'),('P05','Bank matching repo','https://api.github.com/repos/nTier-Software/BankStatement-Matching'),('P06','Hibiscus repo','https://api.github.com/repos/bxservice/de.bxservice.hibiscus'),('I90','iDempiere 13 CashFlow','https://raw.githubusercontent.com/idempiere/idempiere/release-13/org.adempiere.base/src/org/globalqss/process/CashFlow.java'),('I91','iDempiere 13 CashPlan','https://raw.githubusercontent.com/idempiere/idempiere/release-13/org.adempiere.base/src/org/compiere/model/MCashPlan.java'),('I92','iDempiere 13 periodic cash plan','https://raw.githubusercontent.com/idempiere/idempiere/release-13/org.adempiere.base/src/org/globalqss/process/GeneratePeriodicCashPlanLines.java'),('I93','iDempiere 13 models','https://api.github.com/repos/idempiere/idempiere/git/trees/release-13?recursive=1'),('I94','iDempiere REST','https://bxservice.github.io/idempiere-rest-docs/docs/quickstart'),('T90','Tryton licenta','https://www.tryton.org/license'),('T91','Tryton download','https://www.tryton.org/download'),('E93','ERPNext repo','https://api.github.com/repos/frappe/erpnext'),('D93','Dolibarr repo','https://api.github.com/repos/Dolibarr/dolibarr'),('G93','GnuCash repo','https://api.github.com/repos/Gnucash/gnucash')]: add(id,'iDempiere' if id.startswith(('I','P')) else {'T':'Tryton','E':'ERPNext','D':'Dolibarr','G':'GnuCash'}[id[0]],title,url)
def get(s):
 p=ROOT/'05_Documentatii_oficiale'/s['group'];p.mkdir(parents=True,exist_ok=True)
 try:
  r=requests.get(s['url'],timeout=35,headers={'User-Agent':'EVA-CashFlow-documentation-audit/1.0'});s.update(status=r.status_code,final_url=r.url,content_type=r.headers.get('Content-Type',''),retrieved_utc=datetime.now(timezone.utc).isoformat())
  if r.status_code==200:
   ext='.pdf' if r.content.startswith(b'%PDF') else '.zip' if r.content.startswith(b'PK') else '.json' if 'json' in s['content_type'] else '.html' if 'html' in s['content_type'] else '.txt'
   f=p/(s['id']+'_'+re.sub(r'[^A-Za-z0-9_.-]','_',s['title'])[:85]+ext);f.write_bytes(r.content);s.update(local=f.relative_to(ROOT).as_posix(),bytes=len(r.content),sha256=hashlib.sha256(r.content).hexdigest())
  else:s['local']=''
 except Exception as e:s.update(status='error',error=type(e).__name__,local='')
 return s
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as ex:
 for s in ex.map(get,S): print(s['id'],s['status'],s.get('bytes',0),flush=True)
(ROOT/'06_Surse_si_verificare').mkdir(exist_ok=True)
(ROOT/'06_Surse_si_verificare'/'surse.json').write_text(json.dumps(S,ensure_ascii=False,indent=2),encoding='utf-8')
print('DONE',len(S),sum(x['status']==200 for x in S),flush=True)
